<a href="https://colab.research.google.com/github/Divya4325/Cross-Market-Analysis-Crypto-Oil-Stocks-with-SQL-and-Streamlit/blob/main/Cross_Market_Analysis_Crypto%2C_Oil_%26_Stocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.1.4)

In [ ]:
import requests
import pandas as pd
import time
all_data=[]
base_url="https://api.coingecko.com/api/v3/coins/markets"
for page in range(1,6):
  params={
      "vs_currency":"inr",
      "per_page":250,
      "order":"market_cap_desc",
      "page":page,
      "sparkline":"false"
  }
  while True:
     response=requests.get(base_url,params=params)

     if response.status_code==429:
       print("Rate limit hit.Waiting 10 seconds")
       time.sleep(10)
       continue

     if response.status_code!=200:
       print("Error:", response.text)
       break
     data=response.json()
     print(f"Page{page}---->{len(data)}coins")

     all_data.extend(data)
     break

     time.sleep(3)
  print("Total coins collected:",len(all_data))

Page1---->250coins
Total coins collected: 250
Page2---->250coins
Total coins collected: 500
Rate limit hit.Waiting 10 seconds
Page3---->250coins
Total coins collected: 750
Rate limit hit.Waiting 10 seconds
Rate limit hit.Waiting 10 seconds
Rate limit hit.Waiting 10 seconds
Rate limit hit.Waiting 10 seconds
Rate limit hit.Waiting 10 seconds
Rate limit hit.Waiting 10 seconds
Page4---->250coins
Total coins collected: 1000
Page5---->250coins
Total coins collected: 1250

In [ ]:
df=pd.DataFrame(all_data)
print(df.shape)

(1250, 26)

In [ ]:
df=pd.DataFrame(all_data)
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,6.001944e+06,119994407294852,1,1.199944e+14,3.777174e+12,6.195908e+06,...,1.999574e+07,2.100000e+07,1.118701e+07,-46.34900,2025-10-06T18:57:42.558Z,3.993420e+03,1.501959e+05,2013-07-05T00:00:00.000Z,None,2026-02-28T02:11:50.666Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1.755280e+05,21185858765073,2,2.118586e+13,1.691080e+12,1.873480e+05,...,1.206922e+08,NaN,4.319460e+05,-59.36350,2025-08-24T19:21:03.333Z,2.813000e+01,6.238597e+05,2015-10-20T00:00:00.000Z,"{'times': 38.0974640850183, 'currency': 'btc',...",2026-02-28T02:11:50.608Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,9.108000e+01,16720118883808,3,1.721803e+13,6.283411e+12,9.112000e+01,...,1.890495e+11,NaN,1.055200e+02,-13.68595,2025-01-25T16:51:57.989Z,3.686000e+01,1.470931e+02,2015-03-02T00:00:00.000Z,None,2026-02-28T02:11:50.367Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,5.584000e+04,7613682963714,4,7.613683e+12,1.000849e+11,5.760700e+04,...,1.363588e+08,2.000000e+08,1.214220e+05,-54.01120,2025-10-13T08:41:24.131Z,2.580000e+00,2.160294e+06,2017-10-19T00:00:00.000Z,None,2026-02-28T02:11:50.503Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.237900e+02,7560189717462,5,1.237365e+13,2.825874e+11,1.295400e+02,...,9.998571e+10,1.000000e+11,3.139900e+02,-60.57470,2025-07-21T15:02:00.541Z,1.593430e-01,7.758801e+04,2013-08-16T00:00:00.000Z,None,2026-02-28T02:11:50.365Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,thales,thales,Thales,https://coin-images.coingecko.com/coins/images...,1.213000e+01,778915133,1246,1.213437e+09,3.609300e+04,1.276000e+01,...,1.000000e+08,1.000000e+08,2.758000e+02,-95.60007,2021-09-16T04:45:25.758Z,7.970000e+00,5.222521e+01,2025-05-06T15:31:17.853Z,None,2026-02-28T02:12:55.317Z
1246,bitrise-token,brise,Bitgert,https://coin-images.coingecko.com/coins/images...,1.980000e-06,778496801,1247,8.402262e+08,1.188859e+08,2.020000e-06,...,4.270635e+14,1.000000e+15,1.417800e-04,-98.60809,2022-03-07T08:25:04.177Z,4.533800e-08,4.252814e+03,2021-09-09T21:36:32.800Z,None,2026-02-28T02:13:00.997Z
1247,football-fun,fun,Sport.fun,https://coin-images.coingecko.com/coins/images...,4.360000e+00,778343930,1248,4.372719e+09,4.702692e+08,4.760000e+00,...,1.000000e+09,1.000000e+09,1.108000e+01,-60.48706,2026-01-16T15:25:39.949Z,2.470000e+00,7.706582e+01,2026-02-06T00:26:12.757Z,None,2026-02-28T02:12:55.439Z
1248,unicorn-fart-dust,ufd,Unicorn Fart Dust,https://coin-images.coingecko.com/coins/images...,7.799200e-01,777048045,1249,7.770480e+08,2.325149e+08,8.302080e-01,...,9.999918e+08,9.999918e+08,3.491000e+01,-97.77407,2025-01-19T11:15:39.013Z,6.727070e-01,1.551327e+01,2026-02-06T00:20:31.805Z,None,2026-02-28T02:12:55.406Z
1249,ishares-russell-1000-growth-etf-ondo-tokenized...,iwfon,iShares Russell 1000 Growth ETF (Ondo Tokenize...,https://coin-images.coingecko.com/coins/images...,4.092800e+04,776534127,1250,7.765341e+08,4.124700e+04,4.137800e+04,...,1.897321e+04,NaN,4.477100e+04,-8.58460,2025-10-30T08:27:57.288Z,3.848000e+04,6.360850e+00,2025-09-02T16:00:13.726Z,None,2026-02-28T02:12:55.299Z

In [ ]:
columns_needed=['id', 'symbol', 'name', 'current_price', 'market_cap', 'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply', 'ath', 'atl', 'last_updated']
df=df[columns_needed]

In [ ]:
records = []
for i in all_data:
  records.append(dict(id = i['id'],
                      symbol = i['symbol'],
                      name =i['name'],
                      current_price= i['current_price'],
                      market_cap= i['market_cap'],
                      rank = i['market_cap_rank'],
                      volume = i['total_volume'],
                      circulating_supply = i['circulating_supply'],
                      total_supply = i['total_supply'],
                      All_Time_High = i['ath'],
                      All_Time_Low =i['atl'],
                      last_updated =i['last_updated']
                      ))

In [ ]:
df

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,6.001944e+06,119994407294852,1,3.777174e+12,1.999574e+07,1.999574e+07,1.118701e+07,3.993420e+03,2026-02-28T02:11:50.666Z
1,ethereum,eth,Ethereum,1.755280e+05,21185858765073,2,1.691080e+12,1.206922e+08,1.206922e+08,4.319460e+05,2.813000e+01,2026-02-28T02:11:50.608Z
2,tether,usdt,Tether,9.108000e+01,16720118883808,3,6.283411e+12,1.835826e+11,1.890495e+11,1.055200e+02,3.686000e+01,2026-02-28T02:11:50.367Z
3,binancecoin,bnb,BNB,5.584000e+04,7613682963714,4,1.000849e+11,1.363588e+08,1.363588e+08,1.214220e+05,2.580000e+00,2026-02-28T02:11:50.503Z
4,ripple,xrp,XRP,1.237900e+02,7560189717462,5,2.825874e+11,6.109038e+10,9.998571e+10,3.139900e+02,1.593430e-01,2026-02-28T02:11:50.365Z
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,thales,thales,Thales,1.213000e+01,778915133,1246,3.609300e+04,6.419084e+07,1.000000e+08,2.758000e+02,7.970000e+00,2026-02-28T02:12:55.317Z
1246,bitrise-token,brise,Bitgert,1.980000e-06,778496801,1247,1.188859e+08,3.956882e+14,4.270635e+14,1.417800e-04,4.533800e-08,2026-02-28T02:13:00.997Z
1247,football-fun,fun,Sport.fun,4.360000e+00,778343930,1248,4.702692e+08,1.780000e+08,1.000000e+09,1.108000e+01,2.470000e+00,2026-02-28T02:12:55.439Z
1248,unicorn-fart-dust,ufd,Unicorn Fart Dust,7.799200e-01,777048045,1249,2.325149e+08,9.999918e+08,9.999918e+08,3.491000e+01,6.727070e-01,2026-02-28T02:12:55.406Z
1249,ishares-russell-1000-growth-etf-ondo-tokenized...,iwfon,iShares Russell 1000 Growth ETF (Ondo Tokenize...,4.092800e+04,776534127,1250,4.124700e+04,1.897321e+04,1.897321e+04,4.477100e+04,3.848000e+04,2026-02-28T02:12:55.299Z

In [ ]:
df=df.rename(columns={
    'last_updated':'date'
})

In [ ]:
df.loc[:,'date']=pd.to_datetime(df['date']).dt.date

In [ ]:
df

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,date
0,bitcoin,btc,Bitcoin,6.001944e+06,119994407294852,1,3.777174e+12,1.999574e+07,1.999574e+07,1.118701e+07,3.993420e+03,2026-02-28
1,ethereum,eth,Ethereum,1.755280e+05,21185858765073,2,1.691080e+12,1.206922e+08,1.206922e+08,4.319460e+05,2.813000e+01,2026-02-28
2,tether,usdt,Tether,9.108000e+01,16720118883808,3,6.283411e+12,1.835826e+11,1.890495e+11,1.055200e+02,3.686000e+01,2026-02-28
3,binancecoin,bnb,BNB,5.584000e+04,7613682963714,4,1.000849e+11,1.363588e+08,1.363588e+08,1.214220e+05,2.580000e+00,2026-02-28
4,ripple,xrp,XRP,1.237900e+02,7560189717462,5,2.825874e+11,6.109038e+10,9.998571e+10,3.139900e+02,1.593430e-01,2026-02-28
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,thales,thales,Thales,1.213000e+01,778915133,1246,3.609300e+04,6.419084e+07,1.000000e+08,2.758000e+02,7.970000e+00,2026-02-28
1246,bitrise-token,brise,Bitgert,1.980000e-06,778496801,1247,1.188859e+08,3.956882e+14,4.270635e+14,1.417800e-04,4.533800e-08,2026-02-28
1247,football-fun,fun,Sport.fun,4.360000e+00,778343930,1248,4.702692e+08,1.780000e+08,1.000000e+09,1.108000e+01,2.470000e+00,2026-02-28
1248,unicorn-fart-dust,ufd,Unicorn Fart Dust,7.799200e-01,777048045,1249,2.325149e+08,9.999918e+08,9.999918e+08,3.491000e+01,6.727070e-01,2026-02-28
1249,ishares-russell-1000-growth-etf-ondo-tokenized...,iwfon,iShares Russell 1000 Growth ETF (Ondo Tokenize...,4.092800e+04,776534127,1250,4.124700e+04,1.897321e+04,1.897321e+04,4.477100e+04,3.848000e+04,2026-02-28

In [ ]:

top3=df.sort_values('market_cap_rank').head(3)
coin_ids=top3['id'].tolist()
print("Top 3 Coins:",coin_ids)

Top 3 Coins: ['bitcoin', 'ethereum', 'tether']

In [ ]:
import requests
import pandas as pd
import time

all_prices=[]

for coin in coin_ids:
    url = f"https://api.coingecko.com/api/v3/coins/{coin}/market_chart?vs_currency=inr&days=365"

    response = requests.get(url)
    if response.status_code != 200:
        print(f"Error downloading {coin}: {response.status_code}")
        continue

    data = response.json()
    if 'prices' not in data :
        print(f"No price data for {coin}")
        print(data)
        continue

    prices = data['prices']
    for p in prices:
      timestamp=p[0]
      price=p[1]
      date=pd.to_datetime(timestamp,unit='ms').date()
      all_prices.append([coin,date,price])

    print(f"Downloaded:{coin}")
    time.sleep(35)

Downloaded:bitcoin
Downloaded:ethereum
Downloaded:tether

In [ ]:
price_df=pd.DataFrame(all_prices,columns=['coin_id','date','price_inr'])

In [ ]:
price_df

      coin_id        date     price_inr
0     bitcoin  2025-03-01  7.386260e+06
1     bitcoin  2025-03-02  7.523009e+06
2     bitcoin  2025-03-03  8.244473e+06
3     bitcoin  2025-03-04  7.521258e+06
4     bitcoin  2025-03-05  7.615008e+06
...       ...         ...           ...
1093   tether  2026-02-25  9.092356e+01
1094   tether  2026-02-26  9.096825e+01
1095   tether  2026-02-27  9.099723e+01
1096   tether  2026-02-28  9.108431e+01
1097   tether  2026-02-28  9.107558e+01

[1098 rows x 3 columns]

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv"

oil_df=pd.read_csv(url)
print(oil_df)

             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10099  2026-02-17  62.53
10100  2026-02-18  65.33
10101  2026-02-19  66.66
10102  2026-02-20  66.69
10103  2026-02-23  66.36

[10104 rows x 2 columns]

In [ ]:
oil_df['Date']=pd.to_datetime(oil_df['Date'])
oil_df=oil_df[(oil_df['Date']>='2020-01-01')& (oil_df['Date']<='2026-01-31')]
oil_df=oil_df.rename(columns={
    'Date':'date',
    'Price': 'price_inr'
})

In [ ]:
print(oil_df)

            date  price_inr
8569  2020-01-02      61.17
8570  2020-01-03      63.00
8571  2020-01-06      63.27
8572  2020-01-07      62.70
8573  2020-01-08      59.65
...          ...        ...
10084 2026-01-26      60.46
10085 2026-01-27      62.04
10086 2026-01-28      62.75
10087 2026-01-29      64.77
10088 2026-01-30      64.50

[1520 rows x 2 columns]

In [ ]:
oil_df.to_csv("oil_prices.csv",index = False)
from google.colab import files
files.download("oil_prices.csv")

In [ ]:
oil_df=pd.read_csv("/content/oil_prices.csv")
oil_df

            date  price_inr
0     2020-01-02      61.17
1     2020-01-03      63.00
2     2020-01-06      63.27
3     2020-01-07      62.70
4     2020-01-08      59.65
...          ...        ...
1515  2026-01-26      60.46
1516  2026-01-27      62.04
1517  2026-01-28      62.75
1518  2026-01-29      64.77
1519  2026-01-30      64.50

[1520 rows x 2 columns]

In [ ]:
import yfinance as yf
import pandas as pd
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2025-09-30"
all_stocks=[]
for ticker_name in tickers: # Renamed loop variable to avoid conflict with `df["Ticker"]`
    df_temp = yf.download(ticker_name, start=start_date, end=end_date)
    if df_temp.empty:
        print(f"No Data for {ticker_name}")
        continue
    df_temp = df_temp.reset_index()
    # Select and rename columns to match the database schema
    df_selected = df_temp[['Date', 'Open', 'High', 'Low', 'Close', 'Volume']].copy()
    df_selected.columns = ['date', 'open', 'high', 'low', 'close', 'volume']
    df_selected['ticker'] = ticker_name
    all_stocks.append(df_selected)

final_df=pd.concat(all_stocks,ignore_index=True)
final_df

/tmp/ipython-input-421/3388515014.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_temp = yf.download(ticker_name, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-421/3388515014.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_temp = yf.download(ticker_name, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-421/3388515014.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_temp = yf.download(ticker_name, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed

,date,open,high,low,close,volume,ticker
0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3459930000,^GSPC
1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3484700000,^GSPC
2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3702460000,^GSPC
3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3435910000,^GSPC
4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3726840000,^GSPC
...,...,...,...,...,...,...,...
4304,2025-09-23,25209.000000,25261.900391,25084.650391,25169.500000,299200,^NSEI
4305,2025-09-24,25108.750000,25149.849609,25027.449219,25056.900391,244400,^NSEI
4306,2025-09-25,25034.500000,25092.699219,24878.300781,24890.849609,342500,^NSEI
4307,2025-09-26,24818.550781,24868.599609,24629.449219,24654.699219,291500,^NSEI
4308,2025-09-29,24728.550781,24791.300781,24606.199219,24634.900391,394400,^NSEI

In [ ]:
final_df=final_df.dropna(how="all")
final_df=final_df.dropna().reset_index(drop=True)
final_df['date'] = final_df['date'].dt.strftime('%Y-%m-%d')
final_df

,date,open,high,low,close,volume,ticker
0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3459930000,^GSPC
1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3484700000,^GSPC
2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3702460000,^GSPC
3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3435910000,^GSPC
4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3726840000,^GSPC
...,...,...,...,...,...,...,...
4304,2025-09-23,25209.000000,25261.900391,25084.650391,25169.500000,299200,^NSEI
4305,2025-09-24,25108.750000,25149.849609,25027.449219,25056.900391,244400,^NSEI
4306,2025-09-25,25034.500000,25092.699219,24878.300781,24890.849609,342500,^NSEI
4307,2025-09-26,24818.550781,24868.599609,24629.449219,24654.699219,291500,^NSEI
4308,2025-09-29,24728.550781,24791.300781,24606.199219,24634.900391,394400,^NSEI

In [ ]:
import sqlite3
conn=sqlite3.connect("market_database.db")
cursor=conn.cursor()
cursor.execute(""" CREATE TABLE IF NOT EXISTS cryptocurrencies
    (
      id VARCHAR(50) PRIMARY KEY,
      symbol VARCHAR(10),
      name VARCHAR(100),
      current_price DECIMAL(18,6),
      market_cap BIGINT,
      market_cap_rank INT,
      total_volume BIGINT,
      circulating_supply DECIMAL(20,6),
      total_supply DECIMAL(20,6),
      ath DECIMAL(18,6),
      atl DECIMAL(18,6),
      date DATE
    );

""")
cursor.execute(""" CREATE TABLE IF NOT EXISTS crypto_prices
    (
      coin_id VARCHAR(50),
      date DATE,
      price_inr DECIMAL(18,6),
      FOREIGN KEY(coin_id) REFERENCES cryptocurrencies(id)
    );

""")
cursor.execute(""" CREATE TABLE IF NOT EXISTS oil_prices
    (
      date DATE PRIMARY KEY,
      price_inr DECIMAL(18,6)

    );

""")
cursor.execute(""" CREATE TABLE IF NOT EXISTS oil_prices
    (
      date DATE PRIMARY KEY,
      price_inr DECIMAL(18,6)

    );

""")
cursor.execute(""" CREATE TABLE IF NOT EXISTS stock_prices
    (
      date DATE ,
      open DECIMAL(18,6),
      high DECIMAL(18,6),
      low DECIMAL(18,6),
      close DECIMAL(18,6),
      volume BIGINT,
      ticker VARCHAR(20)
    );

""")
conn.commit()

In [ ]:

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('cryptocurrencies',), ('crypto_prices',), ('oil_prices',), ('stock_prices',)]

In [ ]:
import sqlite3
import pandas as pd

# Re-establish connection and cursor just in case it was closed by a previous cell
conn=sqlite3.connect("market_database.db")
cursor=conn.cursor()

# Reconstruct df with the correct columns and format for cryptocurrencies
# This ensures the correct DataFrame is used, regardless of any global 'df' overwrites.
columns_needed=['id', 'symbol', 'name', 'current_price', 'market_cap', 'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply', 'ath', 'atl', 'last_updated']

# Assuming 'all_data' is available from previous cells
temp_df = pd.DataFrame(all_data)
temp_df = temp_df[columns_needed].copy() # Use .copy() to avoid SettingWithCopyWarning

# Rename 'last_updated' to 'date' to match the database schema
temp_df = temp_df.rename(columns={'last_updated':'date'})

# Convert 'date' column to datetime.date objects
temp_df.loc[:,'date'] = pd.to_datetime(temp_df['date']).dt.date

# Now use temp_df for insertion
cursor.executemany("""
      INSERT OR REPLACE INTO cryptocurrencies VALUES(?,?,?,?,?,?,?,?,?,?,?,?)
      """, temp_df.values.tolist())

conn.commit()

In [ ]:
cursor.executemany("""
      INSERT OR REPLACE INTO crypto_prices VALUES(?,?,?)
      """,price_df.values.tolist())

conn.commit()

In [ ]:
cursor.executemany("""
      INSERT OR REPLACE INTO oil_prices VALUES(?,?)
      """,oil_df.values.tolist())

conn.commit()

In [ ]:
cursor.executemany("""
      INSERT OR REPLACE INTO stock_prices VALUES(?,?,?,?,?,?,?)
      """,final_df.values.tolist())

conn.commit()
conn.close()

1.**Find** the top 3 cryptocurrencies by market cap.

In [ ]:


cursor.execute ("""
     SELECT name,symbol
    FROM cryptocurrencies
   ORDER BY market_cap DESC
   LIMIT 3;
""")
top3=cursor.fetchall()
for row in top3:
  print(row)

('Bitcoin', 'btc')
('Ethereum', 'eth')
('Tether', 'usdt')

**2.List all coins where circulating supply exceeds 90% of total supply.**

In [ ]:

cursor.execute("""
     SELECT name,symbol
     FROM cryptocurrencies
     WHERE total_supply>0
     AND (circulating_supply*1.0/total_supply)>=0.9;
""")
results=cursor.fetchall()
for row in results:
  print(row)

('Bitcoin', 'btc')
('Ethereum', 'eth')
('Tether', 'usdt')
('BNB', 'bnb')
('USDC', 'usdc')
('Solana', 'sol')
('TRON', 'trx')
('Dogecoin', 'doge')
('Figure Heloc', 'figr_heloc')
('USDS', 'usds')
('Bitcoin Cash', 'bch')
('LEO Token', 'leo')
('Canton', 'cc')
('Monero', 'xmr')
('Ethena USDe', 'usde')
('USD1', 'usd1')
('Litecoin', 'ltc')
('Dai', 'dai')
('PayPal USD', 'pyusd')
('Avalanche', 'avax')
('Zcash', 'zec')
('Shiba Inu', 'shib')
('Polkadot', 'dot')
('PAX Gold', 'paxg')
('BlackRock USD Institutional Digital Liquidity Fund', 'buidl')
('Circle USYC', 'usyc')
('Falcon USD', 'usdf')
('Aave', 'aave')
('Global Dollar', 'usdg')
('OKB', 'okb')
('Pepe', 'pepe')
('Sky', 'sky')
('Ripple USD', 'rlusd')
('HTX DAO', 'htx')
('NEAR Protocol', 'near')
('Ethereum Classic', 'etc')
('Internet Computer', 'icp')
('BFUSD', 'bfusd')
('POL (ex-MATIC)', 'pol')
('Superstate Short Duration U.S. Government Securities Fund (USTB)', 'ustb')
('KuCoin', 'kcs')
('Gate', 'gt')
('Cosmos Hub', 'atom')
('Quant', 'qnt')
('NEXO', 'nexo')
('USDtb', 'usdtb')
('Kaspa', 'kas')
('pippin', 'pippin')
('Spiko EU T-Bills Money Market Fund', 'eutbl')
('Algorand', 'algo')
('USDD', 'usdd')
('OUSG', 'ousg')
('Render', 'render')
('Janus Henderson Anemoy AAA CLO Fund', 'jaaa')
('VeChain', 'vet')
('Decred', 'dcr')
('Janus Henderson Anemoy Treasury Fund', 'jtrsy')
('Usual USD', 'usd0')
('Bonk', 'bonk')
('GHO', 'gho')
('A7A5', 'a7a5')
('TrueUSD', 'tusd')
('Stacks', 'stx')
('EURC', 'eurc')
('USDai', 'usdai')
('PancakeSwap', 'cake')
('Dash', 'dash')
('Tezos', 'xtz')
('JUST', 'jst')
('Kinesis Gold', 'kau')
('First Digital USD', 'fdusd')
('BitTorrent', 'btt')
('USX', 'usx')
('PRIME', 'prime')
('Chiliz', 'chz')
('Kaia', 'kaia')
('AINFT', 'nft')
('Injective', 'inj')
('Bitcoin SV', 'bsv')
('Sun Token', 'sun')
('SPX6900', 'spx')
('crvUSD', 'crvusd')
('The Graph', 'grt')
('JasmyCoin', 'jasmy')
('Maple Finance', 'syrup')
('FLOKI', 'floki')
('Legacy Frax Dollar', 'frax')
('Conflux', 'cfx')
('Telcoin', 'tel')
('AB', 'ab')
('Neutrl USD', 'nusd')
('Siren', 'siren')
('YLDS', 'ylds')
('USDa', 'usda')
('AUSD', 'ausd')
('Spiko US T-Bills Money Market Fund', 'ustbl')
('dogwifhat', 'wif')
('Blockchain Capital', 'bcap')
('Ape and Pepe', 'apepe')
('Zebec Network', 'zbcn')
('Theta Network', 'theta')
('Tradable NA Rent Financing Platform SSTN', 'pc0000031')
('SwissBorg', 'borg')
('Compound', 'comp')
('Fidelity Digital Interest Token', 'fdit')
('Ribbita by Virtuals', 'tibbir')
('GALA', 'gala')
('InfiniFi USD', 'iusd')
('Basic Attention', 'bat')
('RealLink', 'real')
('Fartcoin', 'fartcoin')
('KOGE', 'koge')
('Satoshi Stablecoin', 'satusd')
('Convex Finance', 'cvx')
('STASIS EURO', 'eurs')
('eCash', 'xec')
('Sonic', 's')
('Aster USDF', 'usdf')
('Theo Short Duration US Treasury Fund', 'thbill')
('BUILDon', 'b')
('Golem', 'glm')
('coco', 'coco')
('1INCH', '1inch')
('Apollo Diversified Credit Securitize Fund', 'acred')
('MultiversX', 'egld')
('SafePal', 'sfp')
('Rollbit Coin', 'rlb')
('GoMining Token', 'gomining')
('MimbleWimbleCoin', 'mwc')
('Ozone Chain', 'ozo')
('Pleasing USD', 'pusd')
('Synthetix', 'snx')
('GRX Chain', 'grx')
('Zano', 'zano')
('Livepeer', 'lpt')
('Quantum Resistant Ledger', 'qrl')
('Onchain Yield Coin', 'onyc')
('Frax USD', 'frxusd')
('Avant USD', 'avusd')
('Re Protocol reUSD', 'reusd')
('CASH', 'cash')
('Cap USD', 'cusd')
('Comedian', 'ban')
('Precious Metals USD', 'pmusd')
('Arweave', 'ar')
('Securitize Tokenized AAA CLO Fund', 'stac')
('AWE Network', 'awe')
('StandX DUSD', 'dusd')
('ApeCoin', 'ape')
('Melania Meme', 'melania')
('Midas mF-ONE', 'mf-one')
('Gas', 'gas')
('Pleasing Gold', 'pgold')
('MNEE USD Stablecoin', 'mnee')
('Resolv USR', 'usr')
('Ring USD', 'usdr')
('Theta Fuel', 'tfuel')
('yearn.finance', 'yfi')
('Qtum', 'qtum')
('Verge', 'xvg')
('Nexus Mutual', 'nxm')
('Ravencoin', 'rvn')
('XDAI', 'xdai')
('Anzen USDz', 'usdz')
('Kusama', 'ksm')
('Luxxcoin', 'lux')
('USDA', 'usda')
('Dog (Bitcoin)', 'dog')
('Akash Network', 'akt')
('Cheems Token', 'cheems')
('EUR CoinVertible', 'eurcv')
('Toshi', 'toshi')
('MAG7.ssi', 'mag7.ssi')
('MetaDAO', 'meta')
('Chutes', 'sn64')
('Zilliqa', 'zil')
('Matrixdock Gold', 'xaum')
('Swop', 'swop')
('AIOZ Network', 'aioz')
('Holo', 'hot')
('DigiByte', 'dgb')
('VanEck Treasury Fund', 'vbill')
('Gama Token', 'gama')
('Rekt', 'rekt')
('Mina Protocol', 'mina')
('Cygnus Finance Global USD', 'cgusd')
('Nervos Network', 'ckb')
('AgentFun.AI', 'agentfun')
('Threshold Network', 't')
('TempleDAO', 'temple')
('CoinEx', 'cet')
('BCGame Coin', 'bc')
('GMX', 'gmx')
('Brett', 'brett')
('Railgun', 'rail')
('Nano', 'xno')
('Turbo', 'turbo')
('TDCCP', 'tdccp')
('Puff The Dragon', 'puff')
('USDu', 'usdu')
('Flow', 'flow')
('币安人生 (BinanceLife)', '币安人生')
('JupUSD', 'jupusd')
('Mog Coin', 'mog')
('Jelly-My-Jelly', 'jellyjelly')
('Astar', 'astr')
('Axelar', 'axl')
('AI Companions', 'aic')
('XPR Network', 'xpr')
('UCHAIN', 'ucn')
('OpenEden OpenDollar', 'usdo')
('Siacoin', 'sc')
('Verus', 'vrsc')
('Frax (prev. FXS)', 'frax')
('Circle Internet Group (Ondo Tokenized Stock)', 'crclon')
('MegaUSD', 'usdm')
('Non-Playable Coin', 'npc')
('Biconomy', 'bico')
('VeThor', 'vtho')
('XYO Network', 'xyo')
('Decentralized Social', 'deso')
('Sushi', 'sushi')
('Anchored Coins AEUR', 'aeur')
('PYTHIA', 'pythia')
('Blur', 'blur')
('Eurite', 'euri')
('Theros', 'theros')
('cat in a dogs world', 'mew')
('Polymesh', 'polyx')
('Ondo U.S. Dollar Token', 'usdon')
('Fidelity Digital Dollar', 'fidd')
('DAI on PulseChain', 'dai')
('Kava', 'kava')
('Midas mHYPER', 'mhyper')
('Alphabet Class A (Ondo Tokenized Stock)', 'googlon')
('BankrCoin', 'bnkr')
('The White Whale', 'whitewhale')
('Pirate Chain', 'arrr')
('ORDI', 'ordi')
('Moo Deng', 'moodeng')
('USDKG', 'usdkg')
('Alloy Tether', 'ausdt')
('Waves', 'waves')
('Singularry', 'singularry')
('Midas mTBILL', 'mtbill')
('Banana For Scale', 'bananas31')
('StraitsX XUSD', 'xusd')
('Overnight.fi USD+', 'usd+')
('Popcat', 'popcat')
('Niza Global', 'niza')
('Sygnum FIUSD Liquidity Fund', 'fiusd')
('Resolv Liquidity Provider Token', 'rlp')
('Compounding OpenDollar', 'cusdo')
('Peanut the Squirrel', 'pnut')
('DUSK', 'dusk')
('would', 'would')
('Casper Network', 'cspr')
('IoTeX', 'iotx')
('BORA', 'bora')
('Hex Trust USD', 'usdx')
('Gemini Dollar', 'gusd')
('SkyAI', 'skyai')
('Constellation', 'dag')
('Ardor', 'ardr')
('Ankr Network', 'ankr')
('BurnedFi', 'burn')
('Mask Network', 'mask')
('Victoria VR', 'vr')
('SSV Network', 'ssv')
('Rocket Pool', 'rpl')
('Snek', 'snek')
('LCX', 'lcx')
('Pundi X', 'pundix')
('Austin Capitals', 'aux')
('Purr', 'purr')
('Loopring', 'lrc')
('SKALE', 'skl')
('Pax Dollar', 'usdp')
('DOVU', 'dovu')
('ICON', 'icx')
('Ontology', 'ont')
('BUSD', 'busd')
('Tellor Tributes', 'trb')
('Useless Coin', 'useless')
('affine', 'sn120')
('AtomOne', 'atone')
('Memecoin', 'meme')
('MVL', 'mvl')
('StorX', 'srx')
('iShares Silver Trust (Ondo Tokenized Stock)', 'slvon')
('Enjin Coin', 'enj')
('Aegis YUSD', 'yusd')
('Resupply USD', 'reusd')
('BIM', 'bim')
('SWFTCOIN', 'swftc')
('IOST', 'iost')
('Lista USD', 'lisusd')
('Steem', 'steem')
('Notcoin', 'not')
('EGL1', 'egl1')
('Snowbank', 'sb')
('Dogelon Mars', 'elon')
('Harmony', 'one')
('Dent', 'dent')
('Band', 'band')
('Hermez Network', 'hez')
('ARK', 'ark')
('Frankencoin', 'zchf')
('GeorgePlaysClashRoyale', 'clash')
('DEAPCOIN', 'dep')
('Illuvium', 'ilv')
('Bounce', 'auction')
('ConstitutionDAO', 'people')
('Ridges AI', 'sn62')
('Nirvana ANA', 'ana')
('AIntivirus', 'ainti')
('EthereumPoW', 'ethw')
('Hive Dollar', 'hbd')
('Helder', 'hldr')
('Targon', 'sn4')
('XT Stablecoin XTUSD', 'xtusd')
('Rootstock Infrastructure Framework', 'rif')
('USTBL', 'ustbl')
('Chintai', 'chex')
('Bancor Network', 'bnt')
('f(x) USD Saving', 'fxsave')
('Radix', 'xrd')
('COTI', 'coti')
('NKYC Token', 'nkyc')
('Liquity USD', 'lusd')
('Whiteheart', 'white')
('Dacxi', 'dxi')
('Noon USN', 'usn')
('Proprietary Trading Network', 'sn8')
('Shentu', 'ctk')
('BOLD', 'bold')
('Kujira', 'kuji')
('just a frog', 'frog')
('Micron Technology (Ondo Tokenized Stock)', 'muon')
('Pre-SP', 'psp')
('Xertra', 'strax')
('Wiki Cat', 'wkc')
('Neiro', 'neiro')
('Yield Optimizer USD', 'yousd')
('IQ', 'iq')
('Stargate Finance', 'stg')
('Rei', 'rei')
('SPDR S&P 500 ETF (Ondo Tokenized ETF)', 'spyon')
('ORE', 'ore')
('tokenbot', 'clanker')
('Sai', 'sai')
('USDX', 'usdx')
('infiniFi Locked iUSD (1week)', 'liusd')
('Audius', 'audio')
('lium', 'sn51')
('Monerium EUR emoney', 'eure')
('Score', 'sn44')
('TerraClassicUSD', 'ustc')
('Not in Employment, Education, or Training', 'neet')
('Aergo', 'aergo')
('Vultisig', 'vult')
('Synthetix sUSD', 'susd')
('Giggle Fund', 'giggle')
('Apertum', 'aptm')
('Liquity', 'lqty')
('BOOK OF MEME', 'bome')
('BLOCKv', 'vee')
('THORChain Yield', 'tcy')
('Kelp Gain', 'ageth')
('Secret', 'scrt')
('Bucket Protocol BUCK Stablecoin', 'buck')
('Solv Protocol SolvBTC Jupiter', 'solvbtc.jup')
('Monerium EUR emoney [OLD]', 'eure')
('τemplar', 'sn3')
('SMARDEX', 'sdex')
('The Grays Currency', 'ptgc')
('Cobak', 'cbk')
('USD CoinVertible', 'usdcv')
('Flux', 'flux')
('Sologenic', 'solo')
('Noble Dollar (USDN)', 'usdn')
('Honey', 'honey')
('Degen', 'degen')
('AI Rig Complex', 'arc')
('Metal DAO', 'mtl')
('Medibloc', 'med')
('WINkLink', 'win')
('NVIDIA (Ondo Tokenized Stock)', 'nvdaon')
('Main Street USD', 'msusd')
('Gyroscope GYD', 'gyd')
('ao Computer', 'ao')
('Invesco QQQ ETF (Ondo Tokenized ETF)', 'qqqon')
('Metronome Synth USD', 'msusd')
('MarsMi', 'marsmi')
('Coin98', 'c98')
('Adventure Gold', 'agld')
('SATS (Ordinals)', 'sats')
('MetaMask USD', 'musd')
('Electronic USD', 'eusd')
('Hippo Protocol', 'hp')
('Global Commercial Business', 'gcb')
('Midas mMEV', 'mmev')
('PinkSale', 'pinksale')
('Pepecoin', 'pep')
('Cartesi', 'ctsi')
('dKargo', 'dka')
('Prom', 'prom')
('TokenPocket Token', 'tpt')
('iShares Core S&P 500 ETF (Ondo Tokenized ETF)', 'ivvon')
('Huobi', 'ht')
('Adshares', 'ads')
('Usual', 'usual')
('Main Street Yield', 'msy')
('Aevo', 'aevo')
('Destra Network', 'dsync')
('Unity', 'uty')
('Decentralized Validator Token', 'dvsteth')
('Gigachad', 'giga')
('Diem', 'diem')
('Smooth Love Potion', 'slp')
('Gains Network', 'gns')
('GAIB AID', 'aid')
('Treasure', 'magic')
('Hunt', 'hunt')
('Advertise Coin', 'adco')
('USAT', 'usat')
('Moonwell', 'well')
('aixbt', 'aixbt')
('iShares 20+ Year Treasury Bond ETF (Ondo Tokenized ETF)', 'tlton')
('Hippius', 'sn75')
('Crown BRLV', 'brlv')
('HarryPotterObamaSonic10Inu (ETH)', 'bitcoin')
('Clearpool', 'cpool')
('StrikeX', 'strx')
('Goatseus Maximus', 'goat')
('Xai', 'xai')
('JPY Coin', 'jpyc')
('Palladium Network', 'plld')
('パンチ (Punch)', 'punch')
('Torch of Liberty', 'liberty')
('Mezo USD', 'musd')
('NXUSD', 'nxusd')
('MEMEX Token', 'mmx')
('Bityuan', 'bty')
('iota', 'sn9')
('JPY Coin v1', 'jpyc')
('Worldwide USD', 'wusd')
('Gradients', 'sn56')
('Carrot', 'crt')
('Hylo USD', 'hyusd')
('0xy', '0xy')
('PONKE', 'ponke')
('Vine', 'vine')
('Gold Token SA DGLD Tokenized Gold', 'dgld')
('iShares Core MSCI EAFE ETF (Ondo Tokenized ETF)', 'iefaon')
('Lorenzo Protocol', 'bank')
('Ekubo Protocol', 'ekubo')
('DORA', 'dora')
('Orizon', 'ori')
('Dialectic USD Vault', 'dusd')
('Qkacoin', 'qka')
('L2 Standard Bridged WETH (MegaETH)', 'weth')
('Kinesis Silver', 'kag')
('SOSANA', 'sosana')
('Midas mAPOLLO', 'mapollo')
('Kled AI', 'kled')
('Xphere', 'xp')
('TROLL', 'troll')
('Bonfida', 'fida')
('f(x) Protocol fxUSD', 'fxusd')
('Hydration', 'hdx')
('Coinmetro', 'xcm')
('PunkStrategy', 'pnkstr')
('DODO', 'dodo')
('Bone ShibaSwap', 'bone')
('MonbaseCoin', 'mbc')
('Chromia', 'chr')
('Solar', 'sxp')
('AVA (Travala)', 'ava')
('PulseChain Peacock', 'pcock')
('Cetus Protocol', 'cetus')
('Yochi', 'yochi')
('iShares Core US Aggregate Bond ETF (Ondo Tokenized ETF)', 'aggon')
('iShares Gold Trust (Ondo Tokenized Stock)', 'iauon')
('Osaka Protocol', 'osak')
('DIAMOND TOKEN 💎', 'dit')
('Mento Dollar', 'usdm')
('WEMIX Dollar', 'wemix$')
('Real Token', 'real')
('Midas msyrupUSDp', 'msyrupusdp')
('Artificial Liquid Intelligence', 'ali')
('Moonriver', 'movr')
('Dogs', 'dogs')
('Hegic', 'hegic')
('Hypurr Fun', 'hfun')
('A Hunters Dream', 'caw')
('Firmachain', 'fct')
('Spiko Digital Assets Cash & Carry Fund', 'spkcc')
('XSGD', 'xsgd')
('69420', '69420')
('BRLA Digital BRLA', 'brla')
('OG Fan Token', 'og')
('WAR', 'war')
('ELYSIA', 'el')
('FUNToken', 'fun')
('BENQI', 'qi')
('Firo', 'firo')
('Alchemix USD', 'alusd')
('Wilder World', 'wild')
('READY!', 'ready')
('AscendEx', 'asd')
('Tesla (Ondo Tokenized Stock)', 'tslaon')
('CoinMarketCap 20 Index DTF', 'cmc20')
('哈基米 (Hajimi)', '哈基米')
('StablR Euro', 'eurr')
('Looped Hype', 'lhype')
('Hosky', 'hosky')
('Act I The AI Prophecy', 'act')
('Mubarak', 'mubarak')
('USDM', 'usdm')
('Wanchain', 'wan')
('PolySwarm', 'nct')
('THORWallet DEX', 'tgt')
('Inverse Finance', 'inv')
("CZ's Dog", 'broccoli')
('Reactive Network', 'react')
('eSui Dollar', 'suiusde')
('CREPE', 'crepe')
('Hyperbeat Ultra HYPE', 'hbhype')
('sETH', 'seth')
('我踏马来了', '我踏马来了')
('Hydrated Dollar', 'hollar')
('JPY Coin', 'jpyc')
('Wrapped STEAMX', 'wsteamx')
('YUSD Stablecoin', 'yusd')
('GAME by Virtuals', 'game')
('Play', 'play')
('ThunderCore', 'tt')
('basilica', 'sn39')
('Freysa AI', 'fai')
('Win', 'win')
('Velas', 'vlx')
('ANDY70B', 'andy70b')
('AhaToken', 'aht')
('HOPR', 'hopr')
('Beta Finance', 'beta')
('Bitcoin Diamond', 'bcd')
('Green', 'green')
('Vanar Chain', 'vanry')
('Buttcoin', 'buttcoin')
('iShares TIPS Bond ETF (Ondo Tokenized ETF)', 'tipon')
('JOBCOIN', 'jobcoin')
('Comtech Gold', 'cgo')
('Memetern', 'mxt')
('Etherfuse USTRY', 'ustry')
('Re Protocol reUSDe', 'reusde')
('Nineteen.ai', 'sn19')
('iShares MSCI EAFE ETF (Ondo Tokenized ETF)', 'efaon')
('AdEx', 'adx')
('Midas mRe7YIELD', 'mre7yield')
('Klever', 'klv')
('Stake DAO', 'sdt')
('Bertram The Pomeranian', 'bert')
('Youves uUSD', 'uusd')
('Apu Apustaja', 'apu')
('YieldFi yToken', 'yusd')
('ChainBounty', 'bounty')
('PepeCoin', 'pepecoin')
('TG.Casino', 'tgc')
('Oraichain', 'orai')
('Ninja Squad Token', 'nst')
('Rupiah Token', 'idrt')
('iShares Core S&P Total US Stock Market ETF (Ondo Tokenized ETF)', 'itoton')
('QUP Coin', 'qup')
('Nest Alpha Vault (LP)', 'inalpha')
('Alien Worlds', 'tlm')
('BitMind', 'sn34')
('Ellipsis [OLD]', 'eps')
('CATX', 'catx')
('Just a chill guy', 'chillguy')
('Coldint', 'sn29')
('Mu Digital AZND', 'aznd')
('Squirrel By 𝓜𝓪𝓽𝓽 𝓕𝓾𝓻𝓲𝓮', 'squirrel')
('Geode Chain', 'geode')
('IXS', 'ixs')
('Anzens USDA', 'usda')
('Hermetica USDh', 'usdh')
('eUSD', 'eusd')
('Defi.money', 'money')
('Until', 'until')
('Avici', 'avici')
('USUALx', 'usualx')
('Nimiq', 'nim')
('Enzyme', 'mln')
('Rainmaker', 'rain')
('My Neighbor Alice', 'alice')
('Switch Token', 'switch')
('Boba Network', 'boba')
('Beefy', 'bifi')
('Maya Protocol', 'cacao')
('iShares Core MSCI Emerging Markets ETF (Ondo Tokenized ETF)', 'iemgon')
('Syscoin', 'sys')
('Pofu', 'pofu')
('ANDY ETH', 'andy')
('NOVA', 'sn68')
('Mobox', 'mbox')
('Dialectic BTC Vault', 'dbit')
('Epic Private Internet Cash', 'epic')
('Bytecoin', 'bcn')
('Overnight.fi USD+ (Blast)', 'usd+')
('GRIFFAIN', 'griffain')
('Foom', 'foom')
('grail', 'sn81')
('InfinitiCoin', 'inco')
('OpenKaito', 'sn5')
('McDull (Meme)', 'mcdull')
('Freedom Dollar', 'fusd')
('Epic Chain', 'epic')
('I love puppies', 'puppies')
('Peercoin', 'ppc')
('Test', 'tst')
('Ampleforth', 'ampl')
('Balancer', 'bal')
('Unicorn Fart Dust', 'ufd')
('Phoenix', 'phb')
('Kekius Maximus', 'kekius')
('404—GEN', 'sn17')
('PePeonTron', 'pepeontron')
('Stable Coin', 'sbc')
('Bitgert', 'brise')
('Uranium', 'xu3o8')
('PIVX', 'pivx')

3.**Get coins that are within 10% of their all-time-high (ATH)**

In [ ]:
cursor.execute("""
     SELECT name,symbol
     FROM cryptocurrencies
     WHERE ath>0
     AND current_price>=ath*0.9;
""")
results=cursor.fetchall()
for row in results:
  print(row)

('USDS', 'usds')
('LEO Token', 'leo')
('Ethena USDe', 'usde')
('USD1', 'usd1')
('Dai', 'dai')
('PayPal USD', 'pyusd')
('Tether Gold', 'xaut')
('PAX Gold', 'paxg')
('BlackRock USD Institutional Digital Liquidity Fund', 'buidl')
('Circle USYC', 'usyc')
('Falcon USD', 'usdf')
('Ripple USD', 'rlusd')
('BFUSD', 'bfusd')
('Superstate Short Duration U.S. Government Securities Fund (USTB)', 'ustb')
('USDtb', 'usdtb')
('\u200b\u200bStable', 'stable')
('Spiko EU T-Bills Money Market Fund', 'eutbl')
('USDD', 'usdd')
('OUSG', 'ousg')
('Janus Henderson Anemoy AAA CLO Fund', 'jaaa')
('Ondo US Dollar Yield', 'usdy')
('Janus Henderson Anemoy Treasury Fund', 'jtrsy')
('GHO', 'gho')
('EURC', 'eurc')
('Kinesis Gold', 'kau')
('First Digital USD', 'fdusd')
('USX', 'usx')
('PRIME', 'prime')
('ADI', 'adi')
('crvUSD', 'crvusd')
('Legacy Frax Dollar', 'frax')
('Neutrl USD', 'nusd')
('YLDS', 'ylds')
('USDa', 'usda')
('AUSD', 'ausd')
('Spiko US T-Bills Money Market Fund', 'ustbl')
('Fidelity Digital Interest Token', 'fdit')
('The9bit', '9bit')
('GUSD', 'gusd')
('Aster USDF', 'usdf')
('Theo Short Duration US Treasury Fund', 'thbill')
('Apollo Diversified Credit Securitize Fund', 'acred')
('Pleasing USD', 'pusd')
('GRX Chain', 'grx')
('Onchain Yield Coin', 'onyc')
('Frax USD', 'frxusd')
('Avant USD', 'avusd')
('Re Protocol reUSD', 'reusd')
('CASH', 'cash')
('Precious Metals USD', 'pmusd')
('Securitize Tokenized AAA CLO Fund', 'stac')
('StandX DUSD', 'dusd')
('Midas mF-ONE', 'mf-one')
('Tradable Singapore Fintech SSL', 'pc0000023')
('Pleasing Gold', 'pgold')
('MNEE USD Stablecoin', 'mnee')
('Resolv USR', 'usr')
('Ring USD', 'usdr')
('Anzen USDz', 'usdz')
('EUR CoinVertible', 'eurcv')
('JUSD', 'jusd')
('Matrixdock Gold', 'xaum')
('VanEck Treasury Fund', 'vbill')
('Gama Token', 'gama')
('Cygnus Finance Global USD', 'cgusd')
('Felix feUSD', 'feusd')
('USDu', 'usdu')
('JupUSD', 'jupusd')
('MegaUSD', 'usdm')
('Eurite', 'euri')
('Theros', 'theros')
('Ondo U.S. Dollar Token', 'usdon')
('Fidelity Digital Dollar', 'fidd')
('Midas mHYPER', 'mhyper')
('The Game Company', 'gmrt')
('USDKG', 'usdkg')
('Alloy Tether', 'ausdt')
('Singularry', 'singularry')
('Midas mTBILL', 'mtbill')
('Sygnum FIUSD Liquidity Fund', 'fiusd')
('Resolv Liquidity Provider Token', 'rlp')
('Compounding OpenDollar', 'cusdo')
('Austin Capitals', 'aux')
('Pax Dollar', 'usdp')
('Frankencoin', 'zchf')
('PumpMeme', 'pm')
('AIntivirus', 'ainti')
('Ryze', 'ryze')
('USTBL', 'ustbl')
('Liquity USD', 'lusd')
('Noon USN', 'usn')
('BOLD', 'bold')
('Yield Optimizer USD', 'yousd')
('MimboGameGroup', 'mgg')
('SPDR S&P 500 ETF (Ondo Tokenized ETF)', 'spyon')
('infiniFi Locked iUSD (1week)', 'liusd')
('Monerium EUR emoney', 'eure')
('MAI', 'mimatic')
('Predictions', 'prdt')
('Monerium EUR emoney [OLD]', 'eure')
('USD CoinVertible', 'usdcv')
('Noble Dollar (USDN)', 'usdn')
('Gyroscope GYD', 'gyd')
('Invesco QQQ ETF (Ondo Tokenized ETF)', 'qqqon')
('MetaMask USD', 'musd')
('Electronic USD', 'eusd')
('Midas mMEV', 'mmev')
('iShares Core S&P 500 ETF (Ondo Tokenized ETF)', 'ivvon')
('NVIDIA xStock', 'nvdax')
('Main Street Yield', 'msy')
('USDH', 'usdh')
('Unity', 'uty')
('Decentralized Validator Token', 'dvsteth')
('USAT', 'usat')
('iShares 20+ Year Treasury Bond ETF (Ondo Tokenized ETF)', 'tlton')
('Crown BRLV', 'brlv')
('Mezo USD', 'musd')
('MEMEX Token', 'mmx')
('SP500 xStock', 'spyx')
('Worldwide USD', 'wusd')
('Hylo USD', 'hyusd')
('Gold Token SA DGLD Tokenized Gold', 'dgld')
('iShares Core MSCI EAFE ETF (Ondo Tokenized ETF)', 'iefaon')
('Orizon', 'ori')
('QIE Blockchain', 'qie')
('L2 Standard Bridged WETH (MegaETH)', 'weth')
('Midas mAPOLLO', 'mapollo')
('f(x) Protocol fxUSD', 'fxusd')
('Felysyum', 'fely')
('Yochi', 'yochi')
('iShares Core US Aggregate Bond ETF (Ondo Tokenized ETF)', 'aggon')
('DIAMOND TOKEN 💎', 'dit')
('Mento Dollar', 'usdm')
('Midas msyrupUSDp', 'msyrupusdp')
('Spiko Digital Assets Cash & Carry Fund', 'spkcc')
('BRLA Digital BRLA', 'brla')
('VCRED', 'vcred')
('eSui Dollar', 'suiusde')
('Hydrated Dollar', 'hollar')
('JPY Coin', 'jpyc')
('Play', 'play')
('iShares TIPS Bond ETF (Ondo Tokenized ETF)', 'tipon')
('Comtech Gold', 'cgo')
('iShares MSCI EAFE ETF (Ondo Tokenized ETF)', 'efaon')
('Midas mRe7YIELD', 'mre7yield')
('Superfortune', 'gua')
('iShares Core S&P Total US Stock Market ETF (Ondo Tokenized ETF)', 'itoton')
('Nest Alpha Vault (LP)', 'inalpha')
('Mu Digital AZND', 'aznd')
('Hermetica USDh', 'usdh')
('eUSD', 'eusd')
('Defi.money', 'money')
('Overnight.fi USD+ (Blast)', 'usd+')
('Freedom Dollar', 'fusd')
('Gold xStock', 'gldx')
('Stable Coin', 'sbc')

**4.Find the average market cap rank of coins with volume above $1B.**

In [ ]:
cursor.execute("""
     SELECT AVG(market_cap_rank)
     FROM cryptocurrencies
     WHERE total_volume>100000000;
""")
result=cursor.fetchone()
print("Average Market cap Rank:",result[0])

Average Market cap Rank: 512.6045519203414

**5.Get the most recently updated coin.**

In [ ]:
cursor.execute("""
     SELECT name,symbol
    FROM cryptocurrencies
   ORDER BY datetime(date)
   LIMIT 1;
""")
Updated_Coin=cursor.fetchall()
print("Recently Updated Coin:",Updated_Coin)

Recently Updated Coin: [('Squirrel By 𝓜𝓪𝓽𝓽 𝓕𝓾𝓻𝓲𝓮', 'squirrel')]

**1.Find the highest daily price of Bitcoin in the last 365 days.**

In [ ]:
cursor.execute("""
    SELECT MAX(price_inr) AS highest_price
    FROM crypto_prices
    WHERE coin_id='bitcoin'
    AND date BETWEEN DATE('2026-02-22','-1 year')
    AND '2026-02-22';

""")
Highest_price=cursor.fetchone()
print("Highest daily price of Bitcoin in the last 365 days:",Highest_price[0])

Highest daily price of Bitcoin in the last 365 days: 11070472.246732509

**2.Calculate the average daily price of Ethereum in the past 1 year**

In [ ]:
cursor.execute("""
    SELECT AVG(price_inr)
    FROM crypto_prices
    WHERE coin_id='ethereum'
    AND date BETWEEN DATE('2026-02-22','-1 year')
    AND '2026-02-22';
""")
Average_price=cursor.fetchone()
print("Average daily price of Ethereum in the past 1 year:",Average_price[0])

Average daily price of Ethereum in the past 1 year: 264768.3724113165

**3.Show the daily price trend of Bitcoin in January 2025**

In [ ]:
cursor.execute("""
    SELECT date,price_inr
    FROM crypto_prices
    WHERE coin_id='bitcoin'
    AND date BETWEEN '2025-02-01'AND'2025-02-28'
    ORDER BY date;
""")
daily_price_bitcoin=cursor.fetchone()
print("Daily price trend of Bitcoin in January 2025:",daily_price_bitcoin)

Daily price trend of Bitcoin in January 2025: ('2025-02-28', 7397416.663356487)

**4.Find the coin with the highest average price over 1 year**

In [ ]:
cursor.execute("""
    SELECT coin_id,AVG(price_inr) AS avg_price
    FROM crypto_prices
    WHERE date>= DATE('now','-1 year')
    GROUP BY coin_id
    ORDER BY avg_price DESC
     LIMIT 1;
""")
top_coin=cursor.fetchone()
print("Coin with the highest average price over 1 year:",top_coin)

Coin with the highest average price over 1 year: ('bitcoin', 8666463.993398638)

**5.Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025**

In [ ]:
cursor.execute("""
    SELECT ((price_inr_sep2025-price_inr_sep2024)*100.0/
       price_inr_sep2025) AS percent_change
     FROM (
       SELECT
         (SELECT price_inr
        FROM crypto_prices
        WHERE coin_id='bitcoin'
        AND date BETWEEN '2025-09-01'AND '2025-09-30'
        ORDER BY date DESC LIMIT 1) AS price_inr_sep2025,

        (SELECT price_inr
        FROM crypto_prices
        WHERE coin_id='bitcoin'
        AND date BETWEEN '2024-09-01'AND '2024-09-30'
        ORDER BY date DESC LIMIT 1) AS price_inr_sep2024
) AS subquery_prices;
""")
result=cursor.fetchone()
print("Percentage change in Bitcoin's price between Sep 2024 and Sep 2025:",result[0])

Percentage change in Bitcoin's price between Sep 2024 and Sep 2025: None

**1.Find the highest oil price in the last 5 years**

In [ ]:
cursor.execute("""
    SELECT MAX(price_inr) AS highest_price
    FROM oil_prices
    WHERE date>= DATE('now','-5 years');
""")
highest_price=cursor.fetchone()
print("Highest oil price in the last 5 years:",highest_price[0])

Highest oil price in the last 5 years: 123.64

**2.Get the average oil price per year**

In [ ]:
cursor.execute("""
    SELECT strftime('%Y',date) AS year,
    AVG(price_inr) AS avg_price
    FROM oil_prices
    GROUP BY year
    ORDER BY year ;
""")
average_oil_price=cursor.fetchall()
for year,avg_price in average_oil_price:
  print(" average oil price per year:",average_oil_price)

 average oil price per year: [('2020', 39.16043650793651), ('2021', 68.13509960159364), ('2022', 94.90286852589641), ('2023', 77.57653225806452), ('2024', 76.63223999999997), ('2025', 65.38810483870967), ('2026', 60.03699999999999)]
 average oil price per year: [('2020', 39.16043650793651), ('2021', 68.13509960159364), ('2022', 94.90286852589641), ('2023', 77.57653225806452), ('2024', 76.63223999999997), ('2025', 65.38810483870967), ('2026', 60.03699999999999)]
 average oil price per year: [('2020', 39.16043650793651), ('2021', 68.13509960159364), ('2022', 94.90286852589641), ('2023', 77.57653225806452), ('2024', 76.63223999999997), ('2025', 65.38810483870967), ('2026', 60.03699999999999)]
 average oil price per year: [('2020', 39.16043650793651), ('2021', 68.13509960159364), ('2022', 94.90286852589641), ('2023', 77.57653225806452), ('2024', 76.63223999999997), ('2025', 65.38810483870967), ('2026', 60.03699999999999)]
 average oil price per year: [('2020', 39.16043650793651), ('2021', 68.13509960159364), ('2022', 94.90286852589641), ('2023', 77.57653225806452), ('2024', 76.63223999999997), ('2025', 65.38810483870967), ('2026', 60.03699999999999)]
 average oil price per year: [('2020', 39.16043650793651), ('2021', 68.13509960159364), ('2022', 94.90286852589641), ('2023', 77.57653225806452), ('2024', 76.63223999999997), ('2025', 65.38810483870967), ('2026', 60.03699999999999)]
 average oil price per year: [('2020', 39.16043650793651), ('2021', 68.13509960159364), ('2022', 94.90286852589641), ('2023', 77.57653225806452), ('2024', 76.63223999999997), ('2025', 65.38810483870967), ('2026', 60.03699999999999)]

**4.Show oil prices during COVID crash (March–April 2020)**

In [ ]:
cursor.execute("""
    SELECT date,price_inr
    FROM oil_prices
    WHERE date BETWEEN '2020-03-01' AND '2020-04-30'
    ORDER BY date;
""")
oil_price=cursor.fetchall()
print("oil prices during COVID crash (March–April 2020)")
for date,price_inr in oil_price:

  print(f"{date}:Rs.{price_inr}")

oil prices during COVID crash (March–April 2020)
2020-03-02:Rs.46.78
2020-03-03:Rs.47.27
2020-03-04:Rs.46.78
2020-03-05:Rs.45.9
2020-03-06:Rs.41.14
2020-03-09:Rs.31.05
2020-03-10:Rs.34.47
2020-03-11:Rs.33.13
2020-03-12:Rs.31.56
2020-03-13:Rs.31.72
2020-03-16:Rs.28.96
2020-03-17:Rs.26.96
2020-03-18:Rs.20.48
2020-03-19:Rs.25.09
2020-03-20:Rs.19.48
2020-03-23:Rs.23.33
2020-03-24:Rs.21.03
2020-03-25:Rs.20.75
2020-03-26:Rs.16.6
2020-03-27:Rs.15.48
2020-03-30:Rs.14.1
2020-03-31:Rs.20.51
2020-04-01:Rs.20.28
2020-04-02:Rs.25.18
2020-04-03:Rs.28.36
2020-04-06:Rs.26.21
2020-04-07:Rs.23.54
2020-04-08:Rs.24.97
2020-04-09:Rs.22.9
2020-04-13:Rs.22.36
2020-04-14:Rs.20.15
2020-04-15:Rs.19.96
2020-04-16:Rs.19.82
2020-04-17:Rs.18.31
2020-04-20:Rs.-36.98
2020-04-21:Rs.8.91
2020-04-22:Rs.13.64
2020-04-23:Rs.15.06
2020-04-24:Rs.15.99
2020-04-27:Rs.12.17
2020-04-28:Rs.12.4
2020-04-29:Rs.15.04
2020-04-30:Rs.19.23

**4.Find the lowest price of oil in the last 10 years**

In [ ]:
cursor.execute("""
    SELECT MIN(price_inr) AS lowest_price
    FROM oil_prices
    WHERE date>= DATE('now','-10 years');
""")
lowest_price=cursor.fetchone()
print("Highest oil price in the last 10 years:",lowest_price[0])

Highest oil price in the last 10 years: -36.98

**5.Calculate the volatility of oil prices (max-min difference per year)**

In [ ]:
cursor.execute("""
    SELECT strftime('%Y',date) AS year,
    MAX(price_inr)-MIN(price_inr) AS volatility
    FROM oil_prices
    GROUP BY year
    ORDER BY year ;
""")
results=cursor.fetchall()
print("The volatility of oil prices (max-min difference per year)")
for year,volatility in results:
 print(f"{year}: Rs.{volatility}")

The volatility of oil prices (max-min difference per year)
2020: Rs.100.25
2021: Rs.38.17
2022: Rs.52.59
2023: Rs.27.060000000000002
2024: Rs.20.959999999999994
2025: Rs.25.290000000000006
2026: Rs.8.759999999999998

**1.Get all stock prices for a given ticker**

In [ ]:
cursor.execute("""
    SELECT date,open,high,low,close,volume
    FROM stock_prices
    WHERE ticker='^IXIC'
    ORDER BY date ;
""")
results=cursor.fetchall()
print("All stock prices for ^IXIC:")
for date,open,high,low,close,volume in results:
 print(f"Date:{date}|Open:{open}|High:{high}|Low:{low}|close:{close}|volume:{volume}")

All stock prices for ^IXIC:
Date:2020-01-02|Open:9039.4599609375|High:9093.4296875|Low:9010.8896484375|close:9092.1904296875|volume:2862700000
Date:2020-01-03|Open:8976.4296875|High:9065.759765625|Low:8976.4296875|close:9020.76953125|volume:2586520000
Date:2020-01-06|Open:8943.5|High:9072.41015625|Low:8943.5|close:9071.4697265625|volume:2810450000
Date:2020-01-07|Open:9076.6396484375|High:9091.9296875|Low:9042.5498046875|close:9068.580078125|volume:2381740000
Date:2020-01-08|Open:9068.0302734375|High:9168.8896484375|Low:9059.3798828125|close:9129.240234375|volume:2472620000
Date:2020-01-09|Open:9202.26953125|High:9215.9501953125|Low:9158.5|close:9203.4296875|volume:2540960000
Date:2020-01-10|Open:9232.9501953125|High:9235.2001953125|Low:9164.66015625|close:9178.8603515625|volume:2382900000
Date:2020-01-13|Open:9213.7197265625|High:9274.490234375|Low:9193.0595703125|close:9273.9296875|volume:2536820000
Date:2020-01-14|Open:9270.6103515625|High:9298.330078125|Low:9226.490234375|close:9251.330078125|volume:2553160000
Date:2020-01-15|Open:9253.759765625|High:9298.8203125|Low:9231.1396484375|close:9258.7001953125|volume:2443220000
Date:2020-01-16|Open:9313.4501953125|High:9357.919921875|Low:9301.3203125|close:9357.1298828125|volume:2312110000
Date:2020-01-17|Open:9392.3701171875|High:9393.48046875|Low:9346.8095703125|close:9388.9404296875|volume:2542540000
Date:2020-01-21|Open:9361.0703125|High:9397.580078125|Low:9350.2001953125|close:9370.8095703125|volume:2686610000
Date:2020-01-22|Open:9413.6103515625|High:9439.2900390625|Low:9375.1298828125|close:9383.76953125|volume:2454580000
Date:2020-01-23|Open:9377.7197265625|High:9409.2001953125|Low:9334.1298828125|close:9402.48046875|volume:2465850000
Date:2020-01-24|Open:9446.2099609375|High:9451.4296875|Low:9273.23046875|close:9314.91015625|volume:2622970000
Date:2020-01-27|Open:9092.4599609375|High:9185.4501953125|Low:9088.0400390625|close:9139.3095703125|volume:2593910000
Date:2020-01-28|Open:9201.8203125|High:9288.8701171875|Low:9182.330078125|close:9269.6796875|volume:2169020000
Date:2020-01-29|Open:9318.259765625|High:9329.1201171875|Low:9249.0400390625|close:9275.16015625|volume:2234620000
Date:2020-01-30|Open:9211.150390625|High:9303|Low:9185.1796875|close:9298.9296875|volume:2345370000
Date:2020-01-31|Open:9324.330078125|High:9324.7998046875|Low:9123.2197265625|close:9150.9404296875|volume:2696090000
Date:2020-02-03|Open:9190.7197265625|High:9299.849609375|Low:9188.5498046875|close:9273.400390625|volume:2427320000
Date:2020-02-04|Open:9398.3896484375|High:9485.3798828125|Low:9374.0498046875|close:9467.9697265625|volume:2447340000
Date:2020-02-05|Open:9574.099609375|High:9574.9404296875|Low:9454.9296875|close:9508.6796875|volume:2470240000
Date:2020-02-06|Open:9540.98046875|High:9575.66015625|Low:9505.6796875|close:9572.150390625|volume:2313860000
Date:2020-02-07|Open:9526.6396484375|High:9570.08984375|Low:9496.5302734375|close:9520.509765625|volume:2243720000
Date:2020-02-10|Open:9493.6298828125|High:9628.66015625|Low:9493.6298828125|close:9628.3896484375|volume:2187520000
Date:2020-02-11|Open:9680.8896484375|High:9714.740234375|Low:9617.2099609375|close:9638.9404296875|volume:2450070000
Date:2020-02-12|Open:9688.599609375|High:9728.76953125|Low:9666.6904296875|close:9725.9599609375|volume:2366510000
Date:2020-02-13|Open:9657.0400390625|High:9748.3203125|Low:9650.01953125|close:9711.9697265625|volume:2254870000
Date:2020-02-14|Open:9728.900390625|High:9746.3603515625|Low:9693.0498046875|close:9731.1796875|volume:2226720000
Date:2020-02-18|Open:9679.0400390625|High:9747.6796875|Low:9675.7998046875|close:9732.740234375|volume:2279420000
Date:2020-02-19|Open:9782.8095703125|High:9838.3701171875|Low:9777.099609375|close:9817.1796875|volume:2470860000
Date:2020-02-20|Open:9799.2001953125|High:9820.8603515625|Low:9636.9404296875|close:9750.9697265625|volume:2745730000
Date:2020-02-21|Open:9708.009765625|High:9715.9501953125|Low:9542.330078125|close:9576.58984375|volume:2750160000
Date:2020-02-24|Open:9188.4404296875|High:9322.8798828125|Low:9166.009765625|close:9221.2802734375|volume:3188590000
Date:2020-02-25|Open:9301.2001953125|High:9315.259765625|Low:8940.490234375|close:8965.6103515625|volume:3595520000
Date:2020-02-26|Open:9011.5498046875|High:9148.3203125|Low:8927.7998046875|close:8980.7802734375|volume:3587950000
Date:2020-02-27|Open:8744.0302734375|High:8904.1103515625|Low:8562.0498046875|close:8566.48046875|volume:4559900000
Date:2020-02-28|Open:8269.740234375|High:8591.8203125|Low:8264.16015625|close:8567.3701171875|volume:5320020000
Date:2020-03-02|Open:8667.1396484375|High:8952.8095703125|Low:8543.349609375|close:8952.169921875|volume:4249020000
Date:2020-03-03|Open:8965.099609375|High:9070.3203125|Low:8602.8896484375|close:8684.08984375|volume:4336700000
Date:2020-03-04|Open:8834.099609375|High:9019.9599609375|Low:8757.66015625|close:9018.08984375|volume:3634760000
Date:2020-03-05|Open:8790.08984375|High:8921.080078125|Low:8677.3896484375|close:8738.58984375|volume:3763860000
Date:2020-03-06|Open:8469.01953125|High:8612.3603515625|Low:8375.1298828125|close:8575.6201171875|volume:4292730000
Date:2020-03-09|Open:7957.93017578125|High:8243.3095703125|Low:7943.16015625|close:7950.68017578125|volume:4554110000
Date:2020-03-10|Open:8219.759765625|High:8347.400390625|Low:7930.43017578125|close:8344.25|volume:4447260000
Date:2020-03-11|Open:8136.25|High:8181.35986328125|Low:7850.9501953125|close:7952.0498046875|volume:4302610000
Date:2020-03-12|Open:7398.580078125|High:7712.330078125|Low:7194.669921875|close:7201.7998046875|volume:5099350000
Date:2020-03-13|Open:7610.39013671875|High:7875.93017578125|Low:7219.08984375|close:7874.8798828125|volume:4701070000
Date:2020-03-16|Open:7392.72998046875|High:7422.2001953125|Low:6882.85986328125|close:6904.58984375|volume:4618120000
Date:2020-03-17|Open:7072|High:7406.22998046875|Low:6828.91015625|close:7334.77978515625|volume:4920210000
Date:2020-03-18|Open:6902.31982421875|High:7182.830078125|Low:6686.35986328125|close:6989.83984375|volume:4935000000
Date:2020-03-19|Open:6996.4501953125|High:7341.3798828125|Low:6858.3798828125|close:7150.580078125|volume:4778490000
Date:2020-03-20|Open:7248.06982421875|High:7354.43994140625|Low:6854.669921875|close:6879.52001953125|volume:5260300000
Date:2020-03-23|Open:6847.27978515625|High:6984.93994140625|Low:6631.419921875|close:6860.669921875|volume:4348410000
Date:2020-03-24|Open:7196.14990234375|High:7418.3701171875|Low:7169.85986328125|close:7417.85986328125|volume:4441080000
Date:2020-03-25|Open:7421.35986328125|High:7671.2099609375|Low:7276.39990234375|close:7384.2998046875|volume:4683630000
Date:2020-03-26|Open:7462.2099609375|High:7809.830078125|Low:7462.2099609375|close:7797.5400390625|volume:4014670000
Date:2020-03-27|Open:7554.25|High:7716.240234375|Low:7491.14013671875|close:7502.3798828125|volume:3989120000
Date:2020-03-30|Open:7583.4599609375|High:7784.35009765625|Low:7539.97021484375|close:7774.14990234375|volume:3870770000
Date:2020-03-31|Open:7740.06005859375|High:7880.31005859375|Low:7642.85986328125|close:7700.10009765625|volume:4078960000
Date:2020-04-01|Open:7459.5|High:7566.3701171875|Low:7301.97998046875|close:7360.580078125|volume:3700040000
Date:2020-04-02|Open:7317.4501953125|High:7501.7001953125|Low:7307.9501953125|close:7487.31005859375|volume:3622170000
Date:2020-04-03|Open:7477.27001953125|High:7518.72021484375|Low:7288.10986328125|close:7373.080078125|volume:3294260000
Date:2020-04-06|Open:7660.169921875|High:7938.330078125|Low:7617.7900390625|close:7913.240234375|volume:3849130000
Date:2020-04-07|Open:8129.990234375|High:8146.43017578125|Low:7881.22021484375|close:7887.259765625|volume:4085960000
Date:2020-04-08|Open:7975.72021484375|High:8114.43017578125|Low:7901.93994140625|close:8090.89990234375|volume:3487440000
Date:2020-04-09|Open:8169.009765625|High:8227.91015625|Low:8072.31982421875|close:8153.580078125|volume:4145460000
Date:2020-04-13|Open:8127.68994140625|High:8200.4404296875|Low:8035.9501953125|close:8192.419921875|volume:3184660000
Date:2020-04-14|Open:8353.2099609375|High:8531.1103515625|Low:8338.080078125|close:8515.740234375|volume:3767410000
Date:2020-04-15|Open:8355.9599609375|High:8464.66015625|Low:8308.7900390625|close:8393.1796875|volume:3347920000
Date:2020-04-16|Open:8479.1103515625|High:8560.16015625|Low:8393.26953125|close:8532.3603515625|volume:4057800000
Date:2020-04-17|Open:8667.48046875|High:8670.2998046875|Low:8531.6904296875|close:8650.1396484375|volume:4348310000
Date:2020-04-20|Open:8553.3798828125|High:8684.91015625|Low:8553.3798828125|close:8560.73046875|volume:3827370000
Date:2020-04-21|Open:8460.6904296875|High:8480.2900390625|Low:8215.6904296875|close:8263.23046875|volume:3788180000
Date:2020-04-22|Open:8434.5498046875|High:8537.3095703125|Low:8404.5400390625|close:8495.3798828125|volume:3041520000
Date:2020-04-23|Open:8528.83984375|High:8635.23046875|Low:8475.2001953125|close:8494.75|volume:3759890000
Date:2020-04-24|Open:8530.080078125|High:8642.9296875|Low:8464.419921875|close:8634.51953125|volume:3696020000
Date:2020-04-27|Open:8717.98046875|High:8754.5703125|Low:8697.3701171875|close:8730.16015625|volume:3694980000
Date:2020-04-28|Open:8825.6904296875|High:8830.5703125|Low:8600.7001953125|close:8607.73046875|volume:3730350000
Date:2020-04-29|Open:8802.7001953125|High:8957.26953125|Low:8765.009765625|close:8914.7099609375|volume:4407140000
Date:2020-04-30|Open:8911.01953125|High:8926.1103515625|Low:8825.830078125|close:8889.5498046875|volume:4335660000
Date:2020-05-01|Open:8681.2900390625|High:8754.4599609375|Low:8566.83984375|close:8604.9501953125|volume:3741300000
Date:2020-05-04|Open:8555.3203125|High:8715.8203125|Low:8537.830078125|close:8710.7099609375|volume:3443140000
Date:2020-05-05|Open:8809.66015625|High:8909.9599609375|Low:8781.3095703125|close:8809.1201171875|volume:3933550000
Date:2020-05-06|Open:8874.7001953125|High:8933.25|Low:8819.3701171875|close:8854.3896484375|volume:3656750000
Date:2020-05-07|Open:8973.7802734375|High:9015.990234375|Low:8932.8603515625|close:8979.66015625|volume:3787220000
Date:2020-05-08|Open:9056.8896484375|High:9125.98046875|Low:9018.2099609375|close:9121.3203125|volume:3813630000
Date:2020-05-11|Open:9054.91015625|High:9241.919921875|Low:9053.169921875|close:9192.33984375|volume:3925450000
Date:2020-05-12|Open:9225.150390625|High:9250.9599609375|Low:9000.0703125|close:9002.5498046875|volume:4336510000
Date:2020-05-13|Open:9006.0498046875|High:9074.16015625|Low:8752.6796875|close:8863.169921875|volume:4273210000
Date:2020-05-14|Open:8788.0400390625|High:8945.7099609375|Low:8705.25|close:8943.7197265625|volume:3965970000
Date:2020-05-15|Open:8839.990234375|High:9018.400390625|Low:8821.3798828125|close:9014.5595703125|volume:4240690000
Date:2020-05-18|Open:9177.150390625|High:9267.2197265625|Low:9154.349609375|close:9234.830078125|volume:4341820000
Date:2020-05-19|Open:9227.4599609375|High:9317.25|Low:9183.25|close:9185.099609375|volume:4193550000
Date:2020-05-20|Open:9305.6201171875|High:9392.8203125|Low:9304.2001953125|close:9375.7802734375|volume:4315500000
Date:2020-05-21|Open:9375.1904296875|High:9405.25|Low:9254.849609375|close:9284.8798828125|volume:3745270000
Date:2020-05-22|Open:9278.5498046875|High:9328.2802734375|Low:9239.41015625|close:9324.58984375|volume:3668070000
Date:2020-05-26|Open:9501.2099609375|High:9501.2099609375|Low:9333.16015625|close:9340.2197265625|volume:4448950000
Date:2020-05-27|Open:9346.1201171875|High:9414.6201171875|Low:9144.2802734375|close:9412.3603515625|volume:4489110000
Date:2020-05-28|Open:9392.990234375|High:9523.6396484375|Low:9345.2802734375|close:9368.990234375|volume:4113660000
Date:2020-05-29|Open:9382.349609375|High:9505.5498046875|Low:9324.73046875|close:9489.8701171875|volume:4742290000
Date:2020-06-01|Open:9471.419921875|High:9571.2802734375|Low:9462.3203125|close:9552.0498046875|volume:3847770000
Date:2020-06-02|Open:9566.5302734375|High:9611.2197265625|Low:9472.080078125|close:9608.3798828125|volume:3990080000
Date:2020-06-03|Open:9651.8603515625|High:9707.7802734375|Low:9627.169921875|close:9682.91015625|volume:4679030000
Date:2020-06-04|Open:9649.650390625|High:9716.1396484375|Low:9560.41015625|close:9615.8095703125|volume:6141320000
Date:2020-06-05|Open:9703.5400390625|High:9845.6904296875|Low:9685.349609375|close:9814.080078125|volume:6607730000
Date:2020-06-08|Open:9823.4404296875|High:9927.1298828125|Low:9780.6103515625|close:9924.75|volume:6197330000
Date:2020-06-09|Open:9867.1904296875|High:10002.5|Low:9863.26953125|close:9953.75|volume:5319450000
Date:2020-06-10|Open:10012.3203125|High:10086.8896484375|Low:9962.580078125|close:10020.349609375|volume:5170860000
Date:2020-06-11|Open:9791.240234375|High:9868.080078125|Low:9491.3095703125|close:9492.73046875|volume:5300850000
Date:2020-06-12|Open:9715.8701171875|High:9768.6396484375|Low:9413.6201171875|close:9588.8095703125|volume:4388990000
Date:2020-06-15|Open:9426.900390625|High:9756.0703125|Low:9403|close:9726.01953125|volume:4476010000
Date:2020-06-16|Open:9949.7802734375|High:9963.6298828125|Low:9748.3798828125|close:9895.8701171875|volume:4669320000
Date:2020-06-17|Open:9943.3095703125|High:9991.2099609375|Low:9891.8095703125|close:9910.5302734375|volume:4279700000
Date:2020-06-18|Open:9892.48046875|High:9959.2001953125|Low:9885.66015625|close:9943.0498046875|volume:4335320000
Date:2020-06-19|Open:10042.1298828125|High:10053.91015625|Low:9872.9404296875|close:9946.1201171875|volume:6093830000
Date:2020-06-22|Open:9945.490234375|High:10059.6103515625|Low:9916.599609375|close:10056.48046875|volume:4506960000
Date:2020-06-23|Open:10130.830078125|High:10221.849609375|Low:10112.4404296875|close:10131.3701171875|volume:5755170000
Date:2020-06-24|Open:10092.919921875|High:10137.5|Low:9842.2197265625|close:9909.169921875|volume:5589130000
Date:2020-06-25|Open:9899.3603515625|High:10023.2802734375|Low:9810.4697265625|close:10017|volume:4779640000
Date:2020-06-26|Open:9995.1201171875|High:10000.669921875|Low:9749.0703125|close:9757.2197265625|volume:7309380000
Date:2020-06-29|Open:9771.7197265625|High:9877.33984375|Low:9663.6103515625|close:9874.150390625|volume:4336290000
Date:2020-06-30|Open:9875.2900390625|High:10085.58984375|Low:9863.669921875|close:10058.76953125|volume:4510190000
Date:2020-07-01|Open:10063.669921875|High:10197.1904296875|Low:10048.0400390625|close:10154.6298828125|volume:4624430000
Date:2020-07-02|Open:10268.669921875|High:10310.3603515625|Low:10194.0595703125|close:10207.6298828125|volume:4038920000
Date:2020-07-06|Open:10360.3798828125|High:10462.0498046875|Low:10354.98046875|close:10433.650390625|volume:4570260000
Date:2020-07-07|Open:10412.4599609375|High:10518.98046875|Low:10337.98046875|close:10343.8896484375|volume:4337130000
Date:2020-07-08|Open:10409.349609375|High:10494.6298828125|Low:10350.9599609375|close:10492.5|volume:4030210000
Date:2020-07-09|Open:10563.7197265625|High:10578.099609375|Low:10379.91015625|close:10547.75|volume:4013180000
Date:2020-07-10|Open:10545.91015625|High:10622.349609375|Low:10447.009765625|close:10617.4404296875|volume:3537510000
Date:2020-07-13|Open:10729.919921875|High:10824.7802734375|Low:10368.0400390625|close:10390.83984375|volume:4851880000
Date:2020-07-14|Open:10310.25|High:10497.830078125|Low:10182.4599609375|close:10488.580078125|volume:4461770000
Date:2020-07-15|Open:10576.7197265625|High:10604.669921875|Low:10420.5400390625|close:10550.490234375|volume:4647070000
Date:2020-07-16|Open:10443.8701171875|High:10499.7900390625|Low:10364.3896484375|close:10473.830078125|volume:4277760000
Date:2020-07-17|Open:10500.51953125|High:10532.6201171875|Low:10421.2099609375|close:10503.1904296875|volume:4361480000
Date:2020-07-20|Open:10526.01953125|High:10783.7998046875|Low:10488.0400390625|close:10767.08984375|volume:4314630000
Date:2020-07-21|Open:10837.8798828125|High:10839.9296875|Low:10650.4599609375|close:10680.3603515625|volume:5350750000
Date:2020-07-22|Open:10687.580078125|High:10745.3203125|Low:10627.4501953125|close:10706.1298828125|volume:4128960000
Date:2020-07-23|Open:10689.5|High:10728.1201171875|Low:10407.8701171875|close:10461.419921875|volume:4501540000
Date:2020-07-24|Open:10294.41015625|High:10418.75|Low:10217.3095703125|close:10363.1796875|volume:4233390000
Date:2020-07-27|Open:10421.7001953125|High:10546.4404296875|Low:10399.8603515625|close:10536.26953125|volume:4244570000
Date:2020-07-28|Open:10509.2001953125|High:10523.6396484375|Low:10397.8701171875|close:10402.08984375|volume:3894660000
Date:2020-07-29|Open:10474.7001953125|High:10567.91015625|Low:10464|close:10542.9404296875|volume:4009640000
Date:2020-07-30|Open:10450.1201171875|High:10609.58984375|Low:10412.08984375|close:10587.8095703125|volume:4185810000
Date:2020-07-31|Open:10741.4697265625|High:10747.7998046875|Low:10557.7001953125|close:10745.26953125|volume:4438730000
Date:2020-08-03|Open:10848.6396484375|High:10927.5595703125|Low:10831.150390625|close:10902.7998046875|volume:4203890000
Date:2020-08-04|Open:10897.8896484375|High:10941.91015625|Low:10852.900390625|close:10941.169921875|volume:4016520000
Date:2020-08-05|Open:10967.8701171875|High:11002.1103515625|Low:10943.7197265625|close:10998.400390625|volume:4160740000
Date:2020-08-06|Open:10989.98046875|High:11121.1904296875|Low:10963.41015625|close:11108.0703125|volume:4120000000
Date:2020-08-07|Open:11072.5302734375|High:11126.0400390625|Low:10920.3701171875|close:11010.98046875|volume:4263930000
Date:2020-08-10|Open:11033.73046875|High:11040.240234375|Low:10849.4599609375|close:10968.3603515625|volume:4048420000
Date:2020-08-11|Open:10942.66015625|High:10989.419921875|Low:10762.7099609375|close:10782.8203125|volume:4331770000
Date:2020-08-12|Open:10878.1201171875|High:11036.7197265625|Low:10877.16015625|close:11012.240234375|volume:3745230000
Date:2020-08-13|Open:11026.8603515625|High:11124.849609375|Low:11007.5|close:11042.5|volume:3480470000
Date:2020-08-14|Open:11042.240234375|High:11058.4404296875|Low:10972.0595703125|close:11019.2998046875|volume:3514260000
Date:2020-08-17|Open:11083.25|High:11144.5302734375|Low:11080.2998046875|close:11129.73046875|volume:3214870000
Date:2020-08-18|Open:11170.75|High:11230.6201171875|Low:11103.830078125|close:11210.83984375|volume:3228590000
Date:2020-08-19|Open:11214.7998046875|High:11257.419921875|Low:11132.099609375|close:11146.4599609375|volume:3496480000
Date:2020-08-20|Open:11096.400390625|High:11283.6201171875|Low:11090.0302734375|close:11264.9501953125|volume:4215130000
Date:2020-08-21|Open:11258.4404296875|High:11326.2099609375|Low:11245.4404296875|close:11311.7998046875|volume:3929290000
Date:2020-08-24|Open:11449.25|High:11462.0498046875|Low:11297.5302734375|close:11379.7197265625|volume:3907310000
Date:2020-08-25|Open:11370.23046875|High:11468.259765625|Low:11343.0400390625|close:11466.4697265625|volume:3475280000
Date:2020-08-26|Open:11516.6201171875|High:11672.0498046875|Low:11507.4599609375|close:11665.0595703125|volume:3471520000
Date:2020-08-27|Open:11688.1904296875|High:11730.009765625|Low:11551.009765625|close:11625.33984375|volume:3547400000
Date:2020-08-28|Open:11689.2802734375|High:11708.76953125|Low:11634.76953125|close:11695.6298828125|volume:3012980000
Date:2020-08-31|Open:11718.8095703125|High:11829.83984375|Low:11697.419921875|close:11775.4599609375|volume:3612050000
Date:2020-09-01|Open:11850.9599609375|High:11945.7197265625|Low:11794.7802734375|close:11939.669921875|volume:3511060000
Date:2020-09-02|Open:12047.259765625|High:12074.0595703125|Low:11836.1796875|close:12056.4404296875|volume:3982360000
Date:2020-09-03|Open:11861.900390625|High:11894.400390625|Low:11361.3603515625|close:11458.099609375|volume:4465010000
Date:2020-09-04|Open:11396.240234375|High:11531.1796875|Low:10875.8701171875|close:11313.1298828125|volume:4284440000
Date:2020-09-08|Open:10900.7001953125|High:11131.5|Low:10837.2001953125|close:10847.6904296875|volume:3905420000

**2.Find the highest closing price for NASDAQ (^IXIC)**

In [ ]:
cursor.execute("""
    SELECT MAX(close) AS high_close_price
    FROM stock_prices
    WHERE ticker='^IXIC';
""")
high_close_price=cursor.fetchone()
print("highest closing price for NASDAQ (^IXIC):",high_close_price[0])

highest closing price for NASDAQ (^IXIC): 22788.98046875

**3.List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)**

In [ ]:
cursor.execute("""
    SELECT date,(high-low) AS intraday_diff
    FROM stock_prices
    WHERE ticker='^GSPC'
    ORDER BY intraday_diff DESC
    LIMIT 5;
""")
results=cursor.fetchall()
print("top 5 days with highest price difference (high - low) for (^GSPC):")
for date, intraday_diff in results:
  print(f"{date}:Difference = Rs.{intraday_diff}")

top 5 days with highest price difference (high - low) for (^GSPC):
2025-04-09:Difference = Rs.532.90966796875
2025-04-07:Difference = Rs.411.52978515625
2025-04-08:Difference = Rs.357.05029296875
2025-04-10:Difference = Rs.237.8798828125
2025-04-04:Difference = Rs.222.240234375

**4.Get monthly average closing price for each ticker**

In [ ]:
cursor.execute("""
    SELECT ticker,
    strftime('%Y-%m',date) AS year_month,
    AVG(close) AS avg_close
    FROM stock_prices
    GROUP BY ticker,year_month
    ORDER BY ticker,year_month;
""")
results=cursor.fetchall()
print("monthly average closing price for each ticker:")
for ticker,year_month,avg_close in results:
    print(f"{ticker}|{year_month}|Average Close: Rs.{avg_close}")

monthly average closing price for each ticker:
^GSPC|2020-01|Average Close: Rs.3278.202857607887
^GSPC|2020-02|Average Close: Rs.3277.3141832853617
^GSPC|2020-03|Average Close: Rs.2652.393632368608
^GSPC|2020-04|Average Close: Rs.2761.9752255394346
^GSPC|2020-05|Average Close: Rs.2919.6084838867187
^GSPC|2020-06|Average Close: Rs.3104.6609330610795
^GSPC|2020-07|Average Close: Rs.3207.6190962357955
^GSPC|2020-08|Average Close: Rs.3391.7100190662204
^GSPC|2020-09|Average Close: Rs.3365.516671316964
^GSPC|2020-10|Average Close: Rs.3418.6999955610795
^GSPC|2020-11|Average Close: Rs.3548.99248046875
^GSPC|2020-12|Average Close: Rs.3695.3100142045455
^GSPC|2021-01|Average Close: Rs.3793.7484323601975
^GSPC|2021-02|Average Close: Rs.3883.4321160567433
^GSPC|2021-03|Average Close: Rs.3910.5082795516305
^GSPC|2021-04|Average Close: Rs.4141.176199776785
^GSPC|2021-05|Average Close: Rs.4167.849536132812
^GSPC|2021-06|Average Close: Rs.4238.48954634233
^GSPC|2021-07|Average Close: Rs.4363.712797619048
^GSPC|2021-08|Average Close: Rs.4453.965931285511
^GSPC|2021-09|Average Close: Rs.4445.543317522322
^GSPC|2021-10|Average Close: Rs.4460.707077752976
^GSPC|2021-11|Average Close: Rs.4667.386648995535
^GSPC|2021-12|Average Close: Rs.4674.772771661932
^GSPC|2022-01|Average Close: Rs.4573.815454101563
^GSPC|2022-02|Average Close: Rs.4435.980494449013
^GSPC|2022-03|Average Close: Rs.4391.265264096467
^GSPC|2022-04|Average Close: Rs.4391.29599609375
^GSPC|2022-05|Average Close: Rs.4040.3600027901784
^GSPC|2022-06|Average Close: Rs.3898.9466843377977
^GSPC|2022-07|Average Close: Rs.3911.7294921875
^GSPC|2022-08|Average Close: Rs.4158.563083814538
^GSPC|2022-09|Average Close: Rs.3850.5204961867557
^GSPC|2022-10|Average Close: Rs.3726.050955636161
^GSPC|2022-11|Average Close: Rs.3917.488595145089
^GSPC|2022-12|Average Close: Rs.3912.3809523809523
^GSPC|2023-01|Average Close: Rs.3960.656530761719
^GSPC|2023-02|Average Close: Rs.4079.6847245065787
^GSPC|2023-03|Average Close: Rs.3968.5591457201085
^GSPC|2023-04|Average Close: Rs.4121.467362253289
^GSPC|2023-05|Average Close: Rs.4146.1731955788355
^GSPC|2023-06|Average Close: Rs.4345.372837611607
^GSPC|2023-07|Average Close: Rs.4508.07548828125
^GSPC|2023-08|Average Close: Rs.4457.358674422554
^GSPC|2023-09|Average Close: Rs.4409.094995117188
^GSPC|2023-10|Average Close: Rs.4269.400945490057
^GSPC|2023-11|Average Close: Rs.4460.063313802083
^GSPC|2023-12|Average Close: Rs.4685.051489257812
^GSPC|2024-01|Average Close: Rs.4804.491513206845
^GSPC|2024-02|Average Close: Rs.5011.96142578125
^GSPC|2024-03|Average Close: Rs.5170.572485351562
^GSPC|2024-04|Average Close: Rs.5112.492742365057
^GSPC|2024-05|Average Close: Rs.5235.225497159091
^GSPC|2024-06|Average Close: Rs.5415.140496504934
^GSPC|2024-07|Average Close: Rs.5538.004572088068
^GSPC|2024-08|Average Close: Rs.5478.214577414773
^GSPC|2024-09|Average Close: Rs.5621.26044921875
^GSPC|2024-10|Average Close: Rs.5792.319548233696
^GSPC|2024-11|Average Close: Rs.5929.915991210937
^GSPC|2024-12|Average Close: Rs.6010.908551897322
^GSPC|2025-01|Average Close: Rs.5979.51552734375
^GSPC|2025-02|Average Close: Rs.6038.689967105263
^GSPC|2025-03|Average Close: Rs.5683.983351934524
^GSPC|2025-04|Average Close: Rs.5369.495721726191
^GSPC|2025-05|Average Close: Rs.5810.919480096726
^GSPC|2025-06|Average Close: Rs.6029.951513671875
^GSPC|2025-07|Average Close: Rs.6296.498180042614
^GSPC|2025-08|Average Close: Rs.6408.949474516369
^GSPC|2025-09|Average Close: Rs.6578.79599609375
^IXIC|2020-01|Average Close: Rs.9233.35997953869
^IXIC|2020-02|Average Close: Rs.9418.85002055921
^IXIC|2020-03|Average Close: Rs.7772.205832741477
^IXIC|2020-04|Average Close: Rs.8292.407180059523
^IXIC|2020-05|Average Close: Rs.9105.65546875
^IXIC|2020-06|Average Close: Rs.9839.971324573864
^IXIC|2020-07|Average Close: Rs.10499.86270419034
^IXIC|2020-08|Average Close: Rs.11212.290504092261
^IXIC|2020-09|Average Close: Rs.11088.679966517857
^IXIC|2020-10|Average Close: Rs.11435.234108664772
^IXIC|2020-11|Average Close: Rs.11794.4615234375
^IXIC|2020-12|Average Close: Rs.12619.050914417614
^IXIC|2021-01|Average Close: Rs.13186.605777138158
^IXIC|2021-02|Average Close: Rs.13737.403628700658
^IXIC|2021-03|Average Close: Rs.13168.811820652174
^IXIC|2021-04|Average Close: Rs.13900.437965029761
^IXIC|2021-05|Average Close: Rs.13520.229052734376
^IXIC|2021-06|Average Close: Rs.14097.169078480114
^IXIC|2021-07|Average Close: Rs.14639.07287016369
^IXIC|2021-08|Average Close: Rs.14856.517711292614
^IXIC|2021-09|Average Close: Rs.15023.538550967261
^IXIC|2021-10|Average Close: Rs.14879.01232328869
^IXIC|2021-11|Average Close: Rs.15814.932896205357
^IXIC|2021-12|Average Close: Rs.15474.43172940341
^IXIC|2022-01|Average Close: Rs.14531.377490234376
^IXIC|2022-02|Average Close: Rs.13898.728412828947
^IXIC|2022-03|Average Close: Rs.13623.262950067934
^IXIC|2022-04|Average Close: Rs.13394.163037109374
^IXIC|2022-05|Average Close: Rs.11829.729538690477
^IXIC|2022-06|Average Close: Rs.11418.91908482143
^IXIC|2022-07|Average Close: Rs.11622.63154296875
^IXIC|2022-08|Average Close: Rs.12570.260402513586
^IXIC|2022-09|Average Close: Rs.11402.84998139881
^IXIC|2022-10|Average Close: Rs.10801.49428013393
^IXIC|2022-11|Average Close: Rs.10973.638113839286
^IXIC|2022-12|Average Close: Rs.10838.995814732143
^IXIC|2023-01|Average Close: Rs.11013.990966796875
^IXIC|2023-02|Average Close: Rs.11785.074321546053
^IXIC|2023-03|Average Close: Rs.11637.092221467392
^IXIC|2023-04|Average Close: Rs.12073.464740953947
^IXIC|2023-05|Average Close: Rs.12446.530495383522
^IXIC|2023-06|Average Close: Rs.13463.778134300595
^IXIC|2023-07|Average Close: Rs.14033.090966796875
^IXIC|2023-08|Average Close: Rs.13743.213018002718
^IXIC|2023-09|Average Close: Rs.13585.83955078125
^IXIC|2023-10|Average Close: Rs.13199.427689985796
^IXIC|2023-11|Average Close: Rs.13913.160574776786
^IXIC|2023-12|Average Close: Rs.14690.473974609375
^IXIC|2024-01|Average Close: Rs.15081.388160342261
^IXIC|2024-02|Average Close: Rs.15808.935009765624
^IXIC|2024-03|Average Close: Rs.16216.2955078125
^IXIC|2024-04|Average Close: Rs.15950.863547585228
^IXIC|2024-05|Average Close: Rs.16536.317160866478
^IXIC|2024-06|Average Close: Rs.17495.891652960527
^IXIC|2024-07|Average Close: Rs.17963.290926846592
^IXIC|2024-08|Average Close: Rs.17268.26886541193
^IXIC|2024-09|Average Close: Rs.17599.23017578125
^IXIC|2024-10|Average Close: Rs.18316.404636548912
^IXIC|2024-11|Average Close: Rs.18961.3357421875
^IXIC|2024-12|Average Close: Rs.19734.54175967262
^IXIC|2025-01|Average Close: Rs.19565.0439453125
^IXIC|2025-02|Average Close: Rs.19547.281455592107
^IXIC|2025-03|Average Close: Rs.17828.026506696428
^IXIC|2025-04|Average Close: Rs.16678.45972842262
^IXIC|2025-05|Average Close: Rs.18642.369233630954
^IXIC|2025-06|Average Close: Rs.19673.301171875
^IXIC|2025-07|Average Close: Rs.20784.895951704544
^IXIC|2025-08|Average Close: Rs.21383.58714657738
^IXIC|2025-09|Average Close: Rs.22165.01669921875
^NSEI|2020-01|Average Close: Rs.12183.065132472826
^NSEI|2020-02|Average Close: Rs.11948.821186266447
^NSEI|2020-03|Average Close: Rs.9426.311941964286
^NSEI|2020-04|Average Close: Rs.9063.583333333334
^NSEI|2020-05|Average Close: Rs.9192.013055098685
^NSEI|2020-06|Average Close: Rs.10116.45467862216
^NSEI|2020-07|Average Close: Rs.10897.695694633152
^NSEI|2020-08|Average Close: Rs.11318.566685267857
^NSEI|2020-09|Average Close: Rs.11336.702192826704
^NSEI|2020-10|Average Close: Rs.11789.709495907739
^NSEI|2020-11|Average Close: Rs.12592.957956414473
^NSEI|2020-12|Average Close: Rs.13550.440873579546
^NSEI|2021-01|Average Close: Rs.14284.602490234374
^NSEI|2021-02|Average Close: Rs.14956.842529296875
^NSEI|2021-03|Average Close: Rs.14835.09998139881
^NSEI|2021-04|Average Close: Rs.14613.8525390625
^NSEI|2021-05|Average Close: Rs.14983.525
^NSEI|2021-06|Average Close: Rs.15733.677201704546
^NSEI|2021-07|Average Close: Rs.15783.09765625
^NSEI|2021-08|Average Close: Rs.16470.459449404763
^NSEI|2021-09|Average Close: Rs.17508.614304315477
^NSEI|2021-10|Average Close: Rs.18020.22001953125
^NSEI|2021-11|Average Close: Rs.17718.8923828125
^NSEI|2021-12|Average Close: Rs.17174.26944633152
^NSEI|2022-01|Average Close: Rs.17770.6224609375
^NSEI|2022-02|Average Close: Rs.17225.939990234376
^NSEI|2022-03|Average Close: Rs.16864.673874627977
^NSEI|2022-04|Average Close: Rs.17419.360711348683
^NSEI|2022-05|Average Close: Rs.16271.019112723214
^NSEI|2022-06|Average Close: Rs.15933.16366299716
^NSEI|2022-07|Average Close: Rs.16299.02134486607
^NSEI|2022-08|Average Close: Rs.17579.06494140625
^NSEI|2022-09|Average Close: Rs.17544.877308238636
^NSEI|2022-10|Average Close: Rs.17406.873663651317
^NSEI|2022-11|Average Close: Rs.18311.283296130954
^NSEI|2022-12|Average Close: Rs.18385.131924715908
^NSEI|2023-01|Average Close: Rs.17968.745070684523
^NSEI|2023-02|Average Close: Rs.17739.22236328125
^NSEI|2023-03|Average Close: Rs.17225.64295014881
^NSEI|2023-04|Average Close: Rs.17710.6796875
^NSEI|2023-05|Average Close: Rs.18307.054598721592
^NSEI|2023-06|Average Close: Rs.18726.771391369046
^NSEI|2023-07|Average Close: Rs.19586.00027901786
^NSEI|2023-08|Average Close: Rs.19438.286576704544
^NSEI|2023-09|Average Close: Rs.19786.0451171875
^NSEI|2023-10|Average Close: Rs.19481.66494140625
^NSEI|2023-11|Average Close: Rs.19602.84990234375
^NSEI|2023-12|Average Close: Rs.21165.9900390625
^NSEI|2024-01|Average Close: Rs.21634.75465029762
^NSEI|2024-02|Average Close: Rs.21947.27855282738
^NSEI|2024-03|Average Close: Rs.22176.6943359375
^NSEI|2024-04|Average Close: Rs.22443.4576171875
^NSEI|2024-05|Average Close: Rs.22484.43322172619
^NSEI|2024-06|Average Close: Rs.23364.044716282893
^NSEI|2024-07|Average Close: Rs.24495.15216619318
^NSEI|2024-08|Average Close: Rs.24613.073753720237
^NSEI|2024-09|Average Close: Rs.25470.090494791668
^NSEI|2024-10|Average Close: Rs.24781.670365767044
^NSEI|2024-11|Average Close: Rs.23969.847450657893
^NSEI|2024-12|Average Close: Rs.24231.01915922619
^NSEI|2025-01|Average Close: Rs.23366.395635190216
^NSEI|2025-02|Average Close: Rs.23060.9376953125
^NSEI|2025-03|Average Close: Rs.22851.536903782893
^NSEI|2025-04|Average Close: Rs.23531.66293174342
^NSEI|2025-05|Average Close: Rs.24676.440290178572
^NSEI|2025-06|Average Close: Rs.25003.39769345238
^NSEI|2025-07|Average Close: Rs.25164.891474184784
^NSEI|2025-08|Average Close: Rs.24698.10279605263
^NSEI|2025-09|Average Close: Rs.24958.464285714286

**5.Get average trading volume of NSEI in 2024**

In [ ]:
cursor.execute("""
    SELECT AVG(volume) AS avg_volume
    FROM stock_prices
    WHERE ticker='NSEI'
    AND date BETWEEN '2024-01-01' AND '2024-12-31';

""")
avg_volume=cursor.fetchone()
print("Average trading volume of NSEI in 2024:",avg_volume[0])

Average trading volume of NSEI in 2024: None

** Join Queries (Cross-Market Analysis)**

*1.Compare Bitcoin vs Oil average price in 2025*

In [ ]:
cursor.execute("""
    SELECT
      ROUND(AVG(c.price_inr),2) AS bitcoin_avg_2025,
      ROUND(AVG(o.price_inr),2) AS oil_avg_2025
     FROM crypto_prices c
     JOIN oil_prices o
       ON c.date=o.date
     WHERE c.coin_id='bitcoin'
     AND strftime('%Y',c.date)='2025';
""")
result=cursor.fetchone()
print("Bitcoin Avg Price in 2025:",result[0])
print("Oil Avg Price in 2025:",result[0])

Bitcoin Avg Price in 2025: 8943708.43
Oil Avg Price in 2025: 8943708.43

**2.Check if Bitcoin moves with S&P 500 (correlation idea)**

In [ ]:
cursor.execute("""
    SELECT
      c.date,
      c.price_inr AS bitcoin_price,
      s.close AS sp500_price
    FROM crypto_prices c
    JOIN stock_prices s
       ON c.date=s.date
    WHERE c.coin_id='bitcoin'
    AND s.ticker='^GSPC'
    ORDER BY c.date;
""")
rows = cursor.fetchall()
correlation_df = pd.DataFrame(rows, columns=['date', 'bitcoin_price', 'sp500_price'])
correlation = correlation_df["bitcoin_price"].corr(correlation_df["sp500_price"])
print("Correlation between Bitcoin and S&P500:", correlation)

Correlation between Bitcoin and S&P500: 0.907303852697004

**3.Compare Ethereum and NASDAQ daily prices for 2025**

In [ ]:
cursor.execute("""
    SELECT
      c.date,
      c.price_inr AS ethereum_price,
      s.close AS nasdaq_close
    FROM crypto_prices c
    JOIN stock_prices s
       ON c.date=s.date
    WHERE c.coin_id='ethereum'
      AND s.ticker='^IXIC'
      AND strftime('%Y',c.date)='2025'
    ORDER BY c.date
""")
row=cursor.fetchall()
for row in row:
  print(f"Date:{row[0]}|Ethereum_price:{row[1]}|NASDAQ:{row[2]}")

Date:2025-02-28|Ethereum_price:201317.5125202556|NASDAQ:18847.279296875
Date:2025-03-03|Ethereum_price:220175.98842114926|NASDAQ:18350.189453125
Date:2025-03-04|Ethereum_price:187601.93013882774|NASDAQ:18285.16015625
Date:2025-03-05|Ethereum_price:189391.99179852934|NASDAQ:18552.73046875
Date:2025-03-06|Ethereum_price:194675.72885365813|NASDAQ:18069.259765625
Date:2025-03-07|Ethereum_price:191886.11355343607|NASDAQ:18196.220703125
Date:2025-03-10|Ethereum_price:175758.37045736366|NASDAQ:17468.3203125
Date:2025-03-11|Ethereum_price:164149.389538545|NASDAQ:17436.099609375
Date:2025-03-12|Ethereum_price:167538.8977230319|NASDAQ:17648.44921875
Date:2025-03-13|Ethereum_price:166533.75651871518|NASDAQ:17303.009765625
Date:2025-03-14|Ethereum_price:161919.08161409126|NASDAQ:17754.08984375
Date:2025-03-17|Ethereum_price:164134.74219204995|NASDAQ:17808.66015625
Date:2025-03-18|Ethereum_price:167679.9006033522|NASDAQ:17504.119140625
Date:2025-03-19|Ethereum_price:167319.001543521|NASDAQ:17750.7890625
Date:2025-03-20|Ethereum_price:177917.82793888426|NASDAQ:17691.630859375
Date:2025-03-21|Ethereum_price:171006.12473780697|NASDAQ:17784.05078125
Date:2025-03-24|Ethereum_price:172085.9718554942|NASDAQ:18188.58984375
Date:2025-03-25|Ethereum_price:177753.92370784696|NASDAQ:18271.859375
Date:2025-03-26|Ethereum_price:177052.68464483944|NASDAQ:17899.01953125
Date:2025-03-27|Ethereum_price:172151.5682806194|NASDAQ:17804.029296875
Date:2025-03-28|Ethereum_price:171697.82772804037|NASDAQ:17322.990234375
Date:2025-03-31|Ethereum_price:154426.70647452315|NASDAQ:17299.2890625
Date:2025-04-01|Ethereum_price:155840.4924805317|NASDAQ:17449.890625
Date:2025-04-02|Ethereum_price:163227.64895741257|NASDAQ:17601.05078125
Date:2025-04-03|Ethereum_price:153890.04212059852|NASDAQ:16550.609375
Date:2025-04-04|Ethereum_price:155066.27550185894|NASDAQ:15587.7900390625
Date:2025-04-07|Ethereum_price:134677.50142669896|NASDAQ:15603.259765625
Date:2025-04-08|Ethereum_price:133837.57278106204|NASDAQ:15267.91015625
Date:2025-04-09|Ethereum_price:127176.85742857557|NASDAQ:17124.970703125
Date:2025-04-10|Ethereum_price:143324.73934384843|NASDAQ:16387.310546875
Date:2025-04-11|Ethereum_price:131454.92128790365|NASDAQ:16724.4609375
Date:2025-04-14|Ethereum_price:137163.51905527923|NASDAQ:16831.48046875
Date:2025-04-15|Ethereum_price:139502.26918137303|NASDAQ:16823.169921875
Date:2025-04-16|Ethereum_price:136118.34029958773|NASDAQ:16307.16015625
Date:2025-04-17|Ethereum_price:135084.25007491114|NASDAQ:16286.4501953125
Date:2025-04-21|Ethereum_price:135372.22120159038|NASDAQ:15870.900390625
Date:2025-04-22|Ethereum_price:134334.00818529903|NASDAQ:16300.419921875
Date:2025-04-23|Ethereum_price:149984.44480204728|NASDAQ:16708.05078125
Date:2025-04-24|Ethereum_price:153384.6912264906|NASDAQ:17166.0390625
Date:2025-04-25|Ethereum_price:150793.82263866183|NASDAQ:17382.939453125
Date:2025-04-28|Ethereum_price:153154.64715995087|NASDAQ:17366.130859375
Date:2025-04-29|Ethereum_price:153246.47199208362|NASDAQ:17461.3203125
Date:2025-04-30|Ethereum_price:153045.86830616|NASDAQ:17446.33984375
Date:2025-05-01|Ethereum_price:151706.98921091956|NASDAQ:17710.740234375
Date:2025-05-02|Ethereum_price:155745.16924065605|NASDAQ:17977.73046875
Date:2025-05-05|Ethereum_price:152837.10606631296|NASDAQ:17844.240234375
Date:2025-05-06|Ethereum_price:153282.69389658255|NASDAQ:17689.66015625
Date:2025-05-07|Ethereum_price:153903.86052217713|NASDAQ:17738.16015625
Date:2025-05-08|Ethereum_price:153546.46543390723|NASDAQ:17928.140625
Date:2025-05-09|Ethereum_price:189067.0538600533|NASDAQ:17928.919921875
Date:2025-05-12|Ethereum_price:214170.10011952536|NASDAQ:18708.33984375
Date:2025-05-13|Ethereum_price:211740.19586880849|NASDAQ:19010.08984375
Date:2025-05-14|Ethereum_price:227649.06017478785|NASDAQ:19146.810546875
Date:2025-05-15|Ethereum_price:222550.86125964453|NASDAQ:19112.3203125
Date:2025-05-16|Ethereum_price:217226.91460543944|NASDAQ:19211.099609375
Date:2025-05-19|Ethereum_price:210787.9756927576|NASDAQ:19215.4609375
Date:2025-05-20|Ethereum_price:215738.55684027018|NASDAQ:19142.7109375
Date:2025-05-21|Ethereum_price:215915.19935485243|NASDAQ:18872.640625
Date:2025-05-22|Ethereum_price:219047.5756337483|NASDAQ:18925.740234375
Date:2025-05-23|Ethereum_price:228450.3696380665|NASDAQ:18737.2109375
Date:2025-05-27|Ethereum_price:218190.67523487698|NASDAQ:19199.16015625
Date:2025-05-28|Ethereum_price:227238.5848495167|NASDAQ:19100.939453125
Date:2025-05-29|Ethereum_price:228525.93909568293|NASDAQ:19175.869140625
Date:2025-05-30|Ethereum_price:224768.84403505738|NASDAQ:19113.76953125
Date:2025-06-02|Ethereum_price:217089.5740742275|NASDAQ:19242.609375
Date:2025-06-03|Ethereum_price:222777.49872829148|NASDAQ:19398.9609375
Date:2025-06-04|Ethereum_price:222455.17860950096|NASDAQ:19460.490234375
Date:2025-06-05|Ethereum_price:224236.44416331983|NASDAQ:19298.44921875
Date:2025-06-06|Ethereum_price:207961.65418872624|NASDAQ:19529.94921875
Date:2025-06-09|Ethereum_price:215217.42336418747|NASDAQ:19591.240234375
Date:2025-06-10|Ethereum_price:230255.54711844953|NASDAQ:19714.990234375
Date:2025-06-11|Ethereum_price:240556.86572695823|NASDAQ:19615.880859375
Date:2025-06-12|Ethereum_price:237276.58179525606|NASDAQ:19662.490234375
Date:2025-06-13|Ethereum_price:227345.61024210224|NASDAQ:19406.830078125
Date:2025-06-16|Ethereum_price:219421.86983518038|NASDAQ:19701.2109375
Date:2025-06-17|Ethereum_price:220541.89744913176|NASDAQ:19521.08984375
Date:2025-06-18|Ethereum_price:217182.0562912451|NASDAQ:19546.26953125
Date:2025-06-20|Ethereum_price:218767.0130883784|NASDAQ:19447.41015625
Date:2025-06-23|Ethereum_price:192852.03096719063|NASDAQ:19630.970703125
Date:2025-06-24|Ethereum_price:209315.24780590468|NASDAQ:19912.529296875
Date:2025-06-25|Ethereum_price:210338.28060317386|NASDAQ:19973.55078125
Date:2025-06-26|Ethereum_price:207894.42363255343|NASDAQ:20167.91015625
Date:2025-06-27|Ethereum_price:206903.99097231845|NASDAQ:20273.4609375
Date:2025-06-30|Ethereum_price:213866.80820581852|NASDAQ:20369.73046875
Date:2025-07-01|Ethereum_price:213247.902753943|NASDAQ:20202.890625
Date:2025-07-02|Ethereum_price:206191.53795072352|NASDAQ:20393.130859375
Date:2025-07-03|Ethereum_price:220583.0677146267|NASDAQ:20601.099609375
Date:2025-07-07|Ethereum_price:219842.28509645213|NASDAQ:20412.51953125
Date:2025-07-08|Ethereum_price:218478.50703220506|NASDAQ:20418.4609375
Date:2025-07-09|Ethereum_price:224192.01293457407|NASDAQ:20611.33984375
Date:2025-07-10|Ethereum_price:237634.3285912139|NASDAQ:20630.66015625
Date:2025-07-11|Ethereum_price:252785.18261104374|NASDAQ:20585.529296875
Date:2025-07-14|Ethereum_price:255256.0749124428|NASDAQ:20640.330078125
Date:2025-07-15|Ethereum_price:258953.02296009834|NASDAQ:20677.80078125
Date:2025-07-16|Ethereum_price:269423.17285168904|NASDAQ:20730.490234375
Date:2025-07-17|Ethereum_price:289273.06195820443|NASDAQ:20885.650390625
Date:2025-07-18|Ethereum_price:299604.7001320289|NASDAQ:20895.650390625
Date:2025-07-21|Ethereum_price:323799.5635112756|NASDAQ:20974.1796875
Date:2025-07-22|Ethereum_price:324888.02667051577|NASDAQ:20892.689453125
Date:2025-07-23|Ethereum_price:323522.2855073287|NASDAQ:21020.01953125
Date:2025-07-24|Ethereum_price:313632.80993368995|NASDAQ:21057.9609375
Date:2025-07-25|Ethereum_price:320521.28663827025|NASDAQ:21108.3203125
Date:2025-07-28|Ethereum_price:334271.3356334813|NASDAQ:21178.580078125
Date:2025-07-29|Ethereum_price:328567.3072022601|NASDAQ:21098.2890625
Date:2025-07-30|Ethereum_price:329848.44489638496|NASDAQ:21129.669921875
Date:2025-07-31|Ethereum_price:333798.49786685634|NASDAQ:21122.44921875
Date:2025-08-01|Ethereum_price:323419.73918441863|NASDAQ:20650.130859375
Date:2025-08-04|Ethereum_price:305147.6597239278|NASDAQ:21053.580078125
Date:2025-08-05|Ethereum_price:326586.85608261486|NASDAQ:20916.55078125
Date:2025-08-06|Ethereum_price:316895.55183794844|NASDAQ:21169.419921875
Date:2025-08-07|Ethereum_price:323322.0010279766|NASDAQ:21242.69921875
Date:2025-08-08|Ethereum_price:341975.0422938313|NASDAQ:21450.01953125
Date:2025-08-11|Ethereum_price:372140.5970629246|NASDAQ:21385.400390625
Date:2025-08-12|Ethereum_price:370718.8174494866|NASDAQ:21681.900390625
Date:2025-08-13|Ethereum_price:403547.06190802733|NASDAQ:21713.140625
Date:2025-08-14|Ethereum_price:416582.6051270567|NASDAQ:21710.669921875
Date:2025-08-15|Ethereum_price:399375.2127189976|NASDAQ:21622.98046875
Date:2025-08-18|Ethereum_price:392681.4189909559|NASDAQ:21629.76953125
Date:2025-08-19|Ethereum_price:376878.0982824829|NASDAQ:21314.94921875
Date:2025-08-20|Ethereum_price:354772.70430919825|NASDAQ:21172.859375
Date:2025-08-21|Ethereum_price:376832.66666282027|NASDAQ:21100.310546875
Date:2025-08-22|Ethereum_price:368766.6639472321|NASDAQ:21496.5390625
Date:2025-08-25|Ethereum_price:417273.9071184703|NASDAQ:21449.2890625
Date:2025-08-26|Ethereum_price:383869.2304155191|NASDAQ:21544.26953125
Date:2025-08-27|Ethereum_price:403346.84673449927|NASDAQ:21590.140625
Date:2025-08-28|Ethereum_price:394479.82107990474|NASDAQ:21705.16015625
Date:2025-08-29|Ethereum_price:394824.62858350464|NASDAQ:21455.55078125
Date:2025-09-02|Ethereum_price:378688.487081064|NASDAQ:21279.630859375
Date:2025-09-03|Ethereum_price:380669.0608269572|NASDAQ:21497.73046875
Date:2025-09-04|Ethereum_price:391914.25736500154|NASDAQ:21707.689453125
Date:2025-09-05|Ethereum_price:379062.50711160863|NASDAQ:21700.390625
Date:2025-09-08|Ethereum_price:379557.7315665512|NASDAQ:21798.69921875
Date:2025-09-09|Ethereum_price:379169.3803941581|NASDAQ:21879.490234375
Date:2025-09-10|Ethereum_price:380163.9598970403|NASDAQ:21886.060546875
Date:2025-09-11|Ethereum_price:382811.6356012148|NASDAQ:22043.0703125
Date:2025-09-12|Ethereum_price:393614.0739117057|NASDAQ:22141.099609375
Date:2025-09-15|Ethereum_price:406940.596240047|NASDAQ:22348.75
Date:2025-09-16|Ethereum_price:398693.42995223537|NASDAQ:22333.9609375
Date:2025-09-17|Ethereum_price:395856.797622927|NASDAQ:22261.330078125
Date:2025-09-18|Ethereum_price:403666.7568900215|NASDAQ:22470.720703125
Date:2025-09-19|Ethereum_price:404926.98327490315|NASDAQ:22631.48046875
Date:2025-09-22|Ethereum_price:392295.47524281475|NASDAQ:22788.98046875
Date:2025-09-23|Ethereum_price:370875.27142150694|NASDAQ:22573.470703125
Date:2025-09-24|Ethereum_price:369992.0919011612|NASDAQ:22497.859375
Date:2025-09-25|Ethereum_price:368312.96560615575|NASDAQ:22384.69921875
Date:2025-09-26|Ethereum_price:342937.4440185811|NASDAQ:22484.0703125
Date:2025-09-29|Ethereum_price:367286.12298418215|NASDAQ:22591.150390625

**4.Find days when oil price spiked and compare with Bitcoin price change**

In [ ]:
cursor.execute("""
  WITH oil_changes AS(
    SELECT date, price_inr,
     ROUND((price_inr-LAG(price_inr) OVER (ORDER BY date))*100.0/LAG(price_inr) OVER (ORDER BY date),2)
      AS oil_pct_change
    FROM oil_prices),
  btc_changes AS(
      SELECT date, price_inr,
       ROUND((price_inr-LAG(price_inr) OVER (ORDER BY date))*100.0/LAG(price_inr) OVER (ORDER BY date),2)
       AS btc_pct_change
     FROM crypto_prices
     WHERE coin_id='bitcoin'
  )
  SELECT
   o.date,
   o.oil_pct_change,
   b.btc_pct_change
 FROM oil_changes o
 JOIN btc_changes b
  ON o.date=b.date
 WHERE o.oil_pct_change >3
 ORDER BY o.date
""")
rows=cursor.fetchall()
for row in rows:
  print("Date:",row[0])
  print("Oil % Change:",row[1])
  print("Bitcoin % Change:",row[2])

Date: 2025-03-31
Oil % Change: 3.05
Bitcoin % Change: -0.39
Date: 2025-04-09
Oil % Change: 4.31
Bitcoin % Change: -3.13
Date: 2025-04-17
Oil % Change: 3.48
Bitcoin % Change: 0.41
Date: 2025-05-06
Oil % Change: 3.28
Bitcoin % Change: 0.1
Date: 2025-05-08
Oil % Change: 3.08
Bitcoin % Change: 0.27
Date: 2025-06-11
Oil % Change: 4.95
Bitcoin % Change: -0.16
Date: 2025-06-13
Oil % Change: 7.43
Bitcoin % Change: -2.24
Date: 2025-06-17
Oil % Change: 4.26
Bitcoin % Change: 1.3
Date: 2025-07-02
Oil % Change: 3.03
Bitcoin % Change: -1.39
Date: 2025-07-29
Oil % Change: 3.63
Bitcoin % Change: -0.88
Date: 2025-10-23
Oil % Change: 5.3
Bitcoin % Change: -1.12
Date: 2026-01-08
Oil % Change: 3.09
Bitcoin % Change: -2.88
Date: 2026-01-29
Oil % Change: 3.22
Bitcoin % Change: 0.51

**5.Compare top 3 coins daily price trend vs Nifty (^NSEI)**

In [ ]:
cursor.execute("""
    SELECT
      c.date,
      c.price_inr AS crypto_price,
      s.close AS nifty_price
    FROM crypto_prices c
    JOIN stock_prices s
       ON c.date=s.date
    WHERE c.coin_id IN ('bitcoin','ethereum','tether')
    AND s.ticker='^NSEI'
    ORDER BY c.date;
""")
rows=cursor.fetchall()
for row in rows:
  print(f"Date:{row[0]}|Coin_Crytpo_Prices{row[1]}|Nifty_prices{row[2]}")

Date:2025-02-28|Coin_Crytpo_Prices7397416.663356487|Nifty_prices22124.69921875
Date:2025-02-28|Coin_Crytpo_Prices201317.5125202556|Nifty_prices22124.69921875
Date:2025-02-28|Coin_Crytpo_Prices87.24438711142197|Nifty_prices22124.69921875
Date:2025-03-03|Coin_Crytpo_Prices8244472.61232367|Nifty_prices22119.30078125
Date:2025-03-03|Coin_Crytpo_Prices220175.98842114926|Nifty_prices22119.30078125
Date:2025-03-03|Coin_Crytpo_Prices87.47003615438128|Nifty_prices22119.30078125
Date:2025-03-04|Coin_Crytpo_Prices7521257.854514662|Nifty_prices22082.650390625
Date:2025-03-04|Coin_Crytpo_Prices187601.93013882774|Nifty_prices22082.650390625
Date:2025-03-04|Coin_Crytpo_Prices87.26461166558117|Nifty_prices22082.650390625
Date:2025-03-05|Coin_Crytpo_Prices7615008.334491884|Nifty_prices22337.30078125
Date:2025-03-05|Coin_Crytpo_Prices189391.99179852934|Nifty_prices22337.30078125
Date:2025-03-05|Coin_Crytpo_Prices87.19760153544729|Nifty_prices22337.30078125
Date:2025-03-06|Coin_Crytpo_Prices7869430.047939962|Nifty_prices22544.69921875
Date:2025-03-06|Coin_Crytpo_Prices194675.72885365813|Nifty_prices22544.69921875
Date:2025-03-06|Coin_Crytpo_Prices86.85293459270139|Nifty_prices22544.69921875
Date:2025-03-07|Coin_Crytpo_Prices7841736.557001183|Nifty_prices22552.5
Date:2025-03-07|Coin_Crytpo_Prices191886.11355343607|Nifty_prices22552.5
Date:2025-03-07|Coin_Crytpo_Prices87.130685741554|Nifty_prices22552.5
Date:2025-03-10|Coin_Crytpo_Prices7035607.792612969|Nifty_prices22460.30078125
Date:2025-03-10|Coin_Crytpo_Prices175758.37045736366|Nifty_prices22460.30078125
Date:2025-03-10|Coin_Crytpo_Prices87.10034733623596|Nifty_prices22460.30078125
Date:2025-03-11|Coin_Crytpo_Prices6882112.04135304|Nifty_prices22497.900390625
Date:2025-03-11|Coin_Crytpo_Prices164149.389538545|Nifty_prices22497.900390625
Date:2025-03-11|Coin_Crytpo_Prices87.29978709002062|Nifty_prices22497.900390625
Date:2025-03-12|Coin_Crytpo_Prices7220111.199834512|Nifty_prices22470.5
Date:2025-03-12|Coin_Crytpo_Prices167538.8977230319|Nifty_prices22470.5
Date:2025-03-12|Coin_Crytpo_Prices87.17692699400506|Nifty_prices22470.5
Date:2025-03-13|Coin_Crytpo_Prices7311397.167011021|Nifty_prices22397.19921875
Date:2025-03-13|Coin_Crytpo_Prices166533.75651871518|Nifty_prices22397.19921875
Date:2025-03-13|Coin_Crytpo_Prices87.13812439531706|Nifty_prices22397.19921875
Date:2025-03-17|Coin_Crytpo_Prices7182714.546311197|Nifty_prices22508.75
Date:2025-03-17|Coin_Crytpo_Prices164134.74219204995|Nifty_prices22508.75
Date:2025-03-17|Coin_Crytpo_Prices86.93794292174915|Nifty_prices22508.75
Date:2025-03-18|Coin_Crytpo_Prices7307625.213417549|Nifty_prices22834.30078125
Date:2025-03-18|Coin_Crytpo_Prices167679.9006033522|Nifty_prices22834.30078125
Date:2025-03-18|Coin_Crytpo_Prices86.91162498732017|Nifty_prices22834.30078125
Date:2025-03-19|Coin_Crytpo_Prices7166130.900539224|Nifty_prices22907.599609375
Date:2025-03-19|Coin_Crytpo_Prices167319.001543521|Nifty_prices22907.599609375
Date:2025-03-19|Coin_Crytpo_Prices86.55062124305569|Nifty_prices22907.599609375
Date:2025-03-20|Coin_Crytpo_Prices7495414.341859128|Nifty_prices23190.650390625
Date:2025-03-20|Coin_Crytpo_Prices177917.82793888426|Nifty_prices23190.650390625
Date:2025-03-20|Coin_Crytpo_Prices86.35903278492714|Nifty_prices23190.650390625
Date:2025-03-21|Coin_Crytpo_Prices7275140.94449613|Nifty_prices23350.400390625
Date:2025-03-21|Coin_Crytpo_Prices171006.12473780697|Nifty_prices23350.400390625
Date:2025-03-21|Coin_Crytpo_Prices86.27903846450975|Nifty_prices23350.400390625
Date:2025-03-24|Coin_Crytpo_Prices7377568.408827406|Nifty_prices23658.349609375
Date:2025-03-24|Coin_Crytpo_Prices172085.9718554942|Nifty_prices23658.349609375
Date:2025-03-24|Coin_Crytpo_Prices85.99487545180361|Nifty_prices23658.349609375
Date:2025-03-25|Coin_Crytpo_Prices7471026.999919416|Nifty_prices23668.650390625
Date:2025-03-25|Coin_Crytpo_Prices177753.92370784696|Nifty_prices23668.650390625
Date:2025-03-25|Coin_Crytpo_Prices85.56623682089695|Nifty_prices23668.650390625
Date:2025-03-26|Coin_Crytpo_Prices7490943.665690553|Nifty_prices23486.849609375
Date:2025-03-26|Coin_Crytpo_Prices177052.68464483944|Nifty_prices23486.849609375
Date:2025-03-26|Coin_Crytpo_Prices85.60505163395878|Nifty_prices23486.849609375
Date:2025-03-27|Coin_Crytpo_Prices7448415.462567322|Nifty_prices23591.94921875
Date:2025-03-27|Coin_Crytpo_Prices172151.5682806194|Nifty_prices23591.94921875
Date:2025-03-27|Coin_Crytpo_Prices85.65936651729078|Nifty_prices23591.94921875
Date:2025-03-28|Coin_Crytpo_Prices7474953.075439318|Nifty_prices23519.349609375
Date:2025-03-28|Coin_Crytpo_Prices171697.82772804037|Nifty_prices23519.349609375
Date:2025-03-28|Coin_Crytpo_Prices85.67335919646858|Nifty_prices23519.349609375
Date:2025-04-01|Coin_Crytpo_Prices7049110.1215911815|Nifty_prices23165.69921875
Date:2025-04-01|Coin_Crytpo_Prices155840.4924805317|Nifty_prices23165.69921875
Date:2025-04-01|Coin_Crytpo_Prices85.41206359379504|Nifty_prices23165.69921875
Date:2025-04-02|Coin_Crytpo_Prices7295181.762562074|Nifty_prices23332.349609375
Date:2025-04-02|Coin_Crytpo_Prices163227.64895741257|Nifty_prices23332.349609375
Date:2025-04-02|Coin_Crytpo_Prices85.5849496864284|Nifty_prices23332.349609375
Date:2025-04-03|Coin_Crytpo_Prices7072204.244187081|Nifty_prices23250.099609375
Date:2025-04-03|Coin_Crytpo_Prices153890.04212059852|Nifty_prices23250.099609375
Date:2025-04-03|Coin_Crytpo_Prices85.6761598207736|Nifty_prices23250.099609375
Date:2025-04-04|Coin_Crytpo_Prices7092361.1660758825|Nifty_prices22904.44921875
Date:2025-04-04|Coin_Crytpo_Prices155066.27550185894|Nifty_prices22904.44921875
Date:2025-04-04|Coin_Crytpo_Prices85.24511390484845|Nifty_prices22904.44921875
Date:2025-04-07|Coin_Crytpo_Prices6689389.08502666|Nifty_prices22161.599609375
Date:2025-04-07|Coin_Crytpo_Prices134677.50142669896|Nifty_prices22161.599609375
Date:2025-04-07|Coin_Crytpo_Prices85.45426169674982|Nifty_prices22161.599609375
Date:2025-04-08|Coin_Crytpo_Prices6810911.664670934|Nifty_prices22535.849609375
Date:2025-04-08|Coin_Crytpo_Prices133837.57278106204|Nifty_prices22535.849609375
Date:2025-04-08|Coin_Crytpo_Prices85.98356950367794|Nifty_prices22535.849609375
Date:2025-04-09|Coin_Crytpo_Prices6597493.475585312|Nifty_prices22399.150390625
Date:2025-04-09|Coin_Crytpo_Prices127176.85742857557|Nifty_prices22399.150390625
Date:2025-04-09|Coin_Crytpo_Prices86.35241410213946|Nifty_prices22399.150390625
Date:2025-04-11|Coin_Crytpo_Prices6866025.560636041|Nifty_prices22828.55078125
Date:2025-04-11|Coin_Crytpo_Prices131454.92128790365|Nifty_prices22828.55078125
Date:2025-04-11|Coin_Crytpo_Prices86.21000906223857|Nifty_prices22828.55078125
Date:2025-04-15|Coin_Crytpo_Prices7271599.950976666|Nifty_prices23328.55078125
Date:2025-04-15|Coin_Crytpo_Prices139502.26918137303|Nifty_prices23328.55078125
Date:2025-04-15|Coin_Crytpo_Prices86.02483249955277|Nifty_prices23328.55078125
Date:2025-04-16|Coin_Crytpo_Prices7171572.949306771|Nifty_prices23437.19921875
Date:2025-04-16|Coin_Crytpo_Prices136118.34029958773|Nifty_prices23437.19921875
Date:2025-04-16|Coin_Crytpo_Prices85.72212946217893|Nifty_prices23437.19921875
Date:2025-04-17|Coin_Crytpo_Prices7201187.29755112|Nifty_prices23851.650390625
Date:2025-04-17|Coin_Crytpo_Prices135084.25007491114|Nifty_prices23851.650390625
Date:2025-04-17|Coin_Crytpo_Prices85.62082361532676|Nifty_prices23851.650390625
Date:2025-04-21|Coin_Crytpo_Prices7263849.726468839|Nifty_prices24125.55078125
Date:2025-04-21|Coin_Crytpo_Prices135372.22120159038|Nifty_prices24125.55078125
Date:2025-04-21|Coin_Crytpo_Prices85.38151888919427|Nifty_prices24125.55078125
Date:2025-04-22|Coin_Crytpo_Prices7447341.987486609|Nifty_prices24167.25
Date:2025-04-22|Coin_Crytpo_Prices134334.00818529903|Nifty_prices24167.25
Date:2025-04-22|Coin_Crytpo_Prices85.15997232308388|Nifty_prices24167.25
Date:2025-04-23|Coin_Crytpo_Prices7975735.892697773|Nifty_prices24328.94921875
Date:2025-04-23|Coin_Crytpo_Prices149984.44480204728|Nifty_prices24328.94921875
Date:2025-04-23|Coin_Crytpo_Prices85.26928353549717|Nifty_prices24328.94921875
Date:2025-04-24|Coin_Crytpo_Prices8003280.21321444|Nifty_prices24246.69921875
Date:2025-04-24|Coin_Crytpo_Prices153384.6912264906|Nifty_prices24246.69921875
Date:2025-04-24|Coin_Crytpo_Prices85.53309052358021|Nifty_prices24246.69921875
Date:2025-04-25|Coin_Crytpo_Prices8000169.783417303|Nifty_prices24039.349609375
Date:2025-04-25|Coin_Crytpo_Prices150793.82263866183|Nifty_prices24039.349609375
Date:2025-04-25|Coin_Crytpo_Prices85.25665212218877|Nifty_prices24039.349609375
Date:2025-04-28|Coin_Crytpo_Prices8009924.38113424|Nifty_prices24328.5
Date:2025-04-28|Coin_Crytpo_Prices153154.64715995087|Nifty_prices24328.5
Date:2025-04-28|Coin_Crytpo_Prices85.41364771445048|Nifty_prices24328.5
Date:2025-04-29|Coin_Crytpo_Prices8092853.390805625|Nifty_prices24335.94921875
Date:2025-04-29|Coin_Crytpo_Prices153246.47199208362|Nifty_prices24335.94921875
Date:2025-04-29|Coin_Crytpo_Prices85.1792488506429|Nifty_prices24335.94921875
Date:2025-04-30|Coin_Crytpo_Prices8027696.597798843|Nifty_prices24334.19921875
Date:2025-04-30|Coin_Crytpo_Prices153045.86830616|Nifty_prices24334.19921875
Date:2025-04-30|Coin_Crytpo_Prices85.19186692504695|Nifty_prices24334.19921875
Date:2025-05-02|Coin_Crytpo_Prices8167058.515487802|Nifty_prices24346.69921875
Date:2025-05-02|Coin_Crytpo_Prices155745.16924065605|Nifty_prices24346.69921875
Date:2025-05-02|Coin_Crytpo_Prices84.72143692477849|Nifty_prices24346.69921875
Date:2025-05-05|Coin_Crytpo_Prices7973099.086450076|Nifty_prices24461.150390625
Date:2025-05-05|Coin_Crytpo_Prices152837.10606631296|Nifty_prices24461.150390625
Date:2025-05-05|Coin_Crytpo_Prices84.52978130383568|Nifty_prices24461.150390625
Date:2025-05-06|Coin_Crytpo_Prices7980688.008703099|Nifty_prices24379.599609375
Date:2025-05-06|Coin_Crytpo_Prices153282.69389658255|Nifty_prices24379.599609375
Date:2025-05-06|Coin_Crytpo_Prices84.21417463632208|Nifty_prices24379.599609375
Date:2025-05-07|Coin_Crytpo_Prices8207545.052481962|Nifty_prices24414.400390625
Date:2025-05-07|Coin_Crytpo_Prices153903.86052217713|Nifty_prices24414.400390625
Date:2025-05-07|Coin_Crytpo_Prices84.73599019648395|Nifty_prices24414.400390625
Date:2025-05-08|Coin_Crytpo_Prices8229539.783984127|Nifty_prices24273.80078125
Date:2025-05-08|Coin_Crytpo_Prices153546.46543390723|Nifty_prices24273.80078125
Date:2025-05-08|Coin_Crytpo_Prices84.83282740724479|Nifty_prices24273.80078125
Date:2025-05-09|Coin_Crytpo_Prices8868161.595114123|Nifty_prices24008
Date:2025-05-09|Coin_Crytpo_Prices189067.0538600533|Nifty_prices24008
Date:2025-05-09|Coin_Crytpo_Prices86.02914921640757|Nifty_prices24008
Date:2025-05-12|Coin_Crytpo_Prices8882429.185761888|Nifty_prices24924.69921875
Date:2025-05-12|Coin_Crytpo_Prices214170.10011952536|Nifty_prices24924.69921875
Date:2025-05-12|Coin_Crytpo_Prices85.42898961498291|Nifty_prices24924.69921875
Date:2025-05-13|Coin_Crytpo_Prices8739740.641206343|Nifty_prices24578.349609375
Date:2025-05-13|Coin_Crytpo_Prices211740.19586880849|Nifty_prices24578.349609375
Date:2025-05-13|Coin_Crytpo_Prices84.95652139253393|Nifty_prices24578.349609375
Date:2025-05-14|Coin_Crytpo_Prices8860925.91388854|Nifty_prices24666.900390625
Date:2025-05-14|Coin_Crytpo_Prices227649.06017478785|Nifty_prices24666.900390625
Date:2025-05-14|Coin_Crytpo_Prices85.06156417476146|Nifty_prices24666.900390625
Date:2025-05-15|Coin_Crytpo_Prices8854656.259617174|Nifty_prices25062.099609375
Date:2025-05-15|Coin_Crytpo_Prices222550.86125964453|Nifty_prices25062.099609375
Date:2025-05-15|Coin_Crytpo_Prices85.48823723690717|Nifty_prices25062.099609375
Date:2025-05-16|Coin_Crytpo_Prices8861418.050018335|Nifty_prices25019.80078125
Date:2025-05-16|Coin_Crytpo_Prices217226.91460543944|Nifty_prices25019.80078125
Date:2025-05-16|Coin_Crytpo_Prices85.45656192963469|Nifty_prices25019.80078125
Date:2025-05-19|Coin_Crytpo_Prices9065676.354329923|Nifty_prices24945.44921875
Date:2025-05-19|Coin_Crytpo_Prices210787.9756927576|Nifty_prices24945.44921875
Date:2025-05-19|Coin_Crytpo_Prices85.5270435261299|Nifty_prices24945.44921875
Date:2025-05-20|Coin_Crytpo_Prices9017978.28123392|Nifty_prices24683.900390625
Date:2025-05-20|Coin_Crytpo_Prices215738.55684027018|Nifty_prices24683.900390625
Date:2025-05-20|Coin_Crytpo_Prices85.39817385178996|Nifty_prices24683.900390625
Date:2025-05-21|Coin_Crytpo_Prices9134061.037906067|Nifty_prices24813.44921875
Date:2025-05-21|Coin_Crytpo_Prices215915.19935485243|Nifty_prices24813.44921875
Date:2025-05-21|Coin_Crytpo_Prices85.5574306577747|Nifty_prices24813.44921875
Date:2025-05-22|Coin_Crytpo_Prices9387459.456660772|Nifty_prices24609.69921875
Date:2025-05-22|Coin_Crytpo_Prices219047.5756337483|Nifty_prices24609.69921875
Date:2025-05-22|Coin_Crytpo_Prices85.63163566501078|Nifty_prices24609.69921875
Date:2025-05-23|Coin_Crytpo_Prices9591418.421810476|Nifty_prices24853.150390625
Date:2025-05-23|Coin_Crytpo_Prices228450.3696380665|Nifty_prices24853.150390625
Date:2025-05-23|Coin_Crytpo_Prices85.99115187130867|Nifty_prices24853.150390625
Date:2025-05-26|Coin_Crytpo_Prices9274975.732278159|Nifty_prices25001.150390625
Date:2025-05-26|Coin_Crytpo_Prices216970.8522801864|Nifty_prices25001.150390625
Date:2025-05-26|Coin_Crytpo_Prices85.22865612080716|Nifty_prices25001.150390625
Date:2025-05-27|Coin_Crytpo_Prices9314436.685236426|Nifty_prices24826.19921875
Date:2025-05-27|Coin_Crytpo_Prices218190.67523487698|Nifty_prices24826.19921875
Date:2025-05-27|Coin_Crytpo_Prices85.18093962269563|Nifty_prices24826.19921875
Date:2025-05-28|Coin_Crytpo_Prices9310175.102671716|Nifty_prices24752.44921875
Date:2025-05-28|Coin_Crytpo_Prices227238.5848495167|Nifty_prices24752.44921875
Date:2025-05-28|Coin_Crytpo_Prices85.39669345824056|Nifty_prices24752.44921875
Date:2025-05-29|Coin_Crytpo_Prices9208280.990679564|Nifty_prices24833.599609375
Date:2025-05-29|Coin_Crytpo_Prices228525.93909568293|Nifty_prices24833.599609375
Date:2025-05-29|Coin_Crytpo_Prices85.4052947205679|Nifty_prices24833.599609375
Date:2025-05-30|Coin_Crytpo_Prices9026592.666677358|Nifty_prices24750.69921875
Date:2025-05-30|Coin_Crytpo_Prices224768.84403505738|Nifty_prices24750.69921875
Date:2025-05-30|Coin_Crytpo_Prices85.35724386429538|Nifty_prices24750.69921875
Date:2025-06-02|Coin_Crytpo_Prices9040802.274014382|Nifty_prices24716.599609375
Date:2025-06-02|Coin_Crytpo_Prices217089.5740742275|Nifty_prices24716.599609375
Date:2025-06-02|Coin_Crytpo_Prices85.5563529489217|Nifty_prices24716.599609375
Date:2025-06-03|Coin_Crytpo_Prices9038740.617012177|Nifty_prices24542.5
Date:2025-06-03|Coin_Crytpo_Prices222777.49872829148|Nifty_prices24542.5
Date:2025-06-03|Coin_Crytpo_Prices85.39681423567808|Nifty_prices24542.5
Date:2025-06-04|Coin_Crytpo_Prices9036688.899610182|Nifty_prices24620.19921875
Date:2025-06-04|Coin_Crytpo_Prices222455.17860950096|Nifty_prices24620.19921875
Date:2025-06-04|Coin_Crytpo_Prices85.7564471650407|Nifty_prices24620.19921875
Date:2025-06-05|Coin_Crytpo_Prices9003749.459208991|Nifty_prices24750.900390625
Date:2025-06-05|Coin_Crytpo_Prices224236.44416331983|Nifty_prices24750.900390625
Date:2025-06-05|Coin_Crytpo_Prices85.93913530548173|Nifty_prices24750.900390625
Date:2025-06-06|Coin_Crytpo_Prices8729536.730077919|Nifty_prices25003.05078125
Date:2025-06-06|Coin_Crytpo_Prices207961.65418872624|Nifty_prices25003.05078125
Date:2025-06-06|Coin_Crytpo_Prices85.90869091197705|Nifty_prices25003.05078125
Date:2025-06-09|Coin_Crytpo_Prices9066867.46885247|Nifty_prices25103.19921875
Date:2025-06-09|Coin_Crytpo_Prices215217.42336418747|Nifty_prices25103.19921875
Date:2025-06-09|Coin_Crytpo_Prices85.81535004059877|Nifty_prices25103.19921875
Date:2025-06-10|Coin_Crytpo_Prices9455619.179043707|Nifty_prices25104.25
Date:2025-06-10|Coin_Crytpo_Prices230255.54711844953|Nifty_prices25104.25
Date:2025-06-10|Coin_Crytpo_Prices85.78084450272435|Nifty_prices25104.25
Date:2025-06-11|Coin_Crytpo_Prices9440056.689266069|Nifty_prices25141.400390625
Date:2025-06-11|Coin_Crytpo_Prices240556.86572695823|Nifty_prices25141.400390625
Date:2025-06-11|Coin_Crytpo_Prices85.65857775303438|Nifty_prices25141.400390625
Date:2025-06-12|Coin_Crytpo_Prices9288882.88186932|Nifty_prices24888.19921875
Date:2025-06-12|Coin_Crytpo_Prices237276.58179525606|Nifty_prices24888.19921875
Date:2025-06-12|Coin_Crytpo_Prices85.4820574765995|Nifty_prices24888.19921875
Date:2025-06-13|Coin_Crytpo_Prices9081227.025134273|Nifty_prices24718.599609375
Date:2025-06-13|Coin_Crytpo_Prices227345.61024210224|Nifty_prices24718.599609375
Date:2025-06-13|Coin_Crytpo_Prices85.71186331793116|Nifty_prices24718.599609375
Date:2025-06-16|Coin_Crytpo_Prices9090411.27477335|Nifty_prices24946.5
Date:2025-06-16|Coin_Crytpo_Prices219421.86983518038|Nifty_prices24946.5
Date:2025-06-16|Coin_Crytpo_Prices86.12327231151762|Nifty_prices24946.5
Date:2025-06-17|Coin_Crytpo_Prices9208980.453923177|Nifty_prices24853.400390625
Date:2025-06-17|Coin_Crytpo_Prices220541.89744913176|Nifty_prices24853.400390625
Date:2025-06-17|Coin_Crytpo_Prices86.13602992064845|Nifty_prices24853.400390625
Date:2025-06-18|Coin_Crytpo_Prices9039952.955659283|Nifty_prices24812.05078125
Date:2025-06-18|Coin_Crytpo_Prices217182.0562912451|Nifty_prices24812.05078125
Date:2025-06-18|Coin_Crytpo_Prices86.35699142609901|Nifty_prices24812.05078125
Date:2025-06-19|Coin_Crytpo_Prices9070436.848135183|Nifty_prices24793.25
Date:2025-06-19|Coin_Crytpo_Prices218382.42014738446|Nifty_prices24793.25
Date:2025-06-19|Coin_Crytpo_Prices86.62723601577105|Nifty_prices24793.25
Date:2025-06-20|Coin_Crytpo_Prices9080584.318377115|Nifty_prices25112.400390625
Date:2025-06-20|Coin_Crytpo_Prices218767.0130883784|Nifty_prices25112.400390625
Date:2025-06-20|Coin_Crytpo_Prices86.74229506504231|Nifty_prices25112.400390625
Date:2025-06-23|Coin_Crytpo_Prices8731873.284684414|Nifty_prices24971.900390625
Date:2025-06-23|Coin_Crytpo_Prices192852.03096719063|Nifty_prices24971.900390625
Date:2025-06-23|Coin_Crytpo_Prices86.59580048336504|Nifty_prices24971.900390625
Date:2025-06-24|Coin_Crytpo_Prices9111429.945371069|Nifty_prices25044.349609375
Date:2025-06-24|Coin_Crytpo_Prices209315.24780590468|Nifty_prices25044.349609375
Date:2025-06-24|Coin_Crytpo_Prices86.40380690891152|Nifty_prices25044.349609375
Date:2025-06-25|Coin_Crytpo_Prices9111165.38661966|Nifty_prices25244.75
Date:2025-06-25|Coin_Crytpo_Prices210338.28060317386|Nifty_prices25244.75
Date:2025-06-25|Coin_Crytpo_Prices86.00974451148616|Nifty_prices25244.75
Date:2025-06-26|Coin_Crytpo_Prices9223086.808659252|Nifty_prices25549
Date:2025-06-26|Coin_Crytpo_Prices207894.42363255343|Nifty_prices25549
Date:2025-06-26|Coin_Crytpo_Prices86.04675823077042|Nifty_prices25549
Date:2025-06-27|Coin_Crytpo_Prices9165684.099752242|Nifty_prices25637.80078125
Date:2025-06-27|Coin_Crytpo_Prices206903.99097231845|Nifty_prices25637.80078125
Date:2025-06-27|Coin_Crytpo_Prices85.70312960692094|Nifty_prices25637.80078125
Date:2025-06-30|Coin_Crytpo_Prices9263092.465181679|Nifty_prices25517.05078125
Date:2025-06-30|Coin_Crytpo_Prices213866.80820581852|Nifty_prices25517.05078125
Date:2025-06-30|Coin_Crytpo_Prices85.46600406267324|Nifty_prices25517.05078125
Date:2025-07-01|Coin_Crytpo_Prices9181709.414667957|Nifty_prices25541.80078125
Date:2025-07-01|Coin_Crytpo_Prices213247.902753943|Nifty_prices25541.80078125
Date:2025-07-01|Coin_Crytpo_Prices85.72185130518295|Nifty_prices25541.80078125
Date:2025-07-02|Coin_Crytpo_Prices9054321.250569785|Nifty_prices25453.400390625
Date:2025-07-02|Coin_Crytpo_Prices206191.53795072352|Nifty_prices25453.400390625
Date:2025-07-02|Coin_Crytpo_Prices85.73789654348656|Nifty_prices25453.400390625
Date:2025-07-03|Coin_Crytpo_Prices9325640.339018358|Nifty_prices25405.30078125
Date:2025-07-03|Coin_Crytpo_Prices220583.0677146267|Nifty_prices25405.30078125
Date:2025-07-03|Coin_Crytpo_Prices85.72260504432407|Nifty_prices25405.30078125
Date:2025-07-04|Coin_Crytpo_Prices9360532.463404836|Nifty_prices25461
Date:2025-07-04|Coin_Crytpo_Prices221209.20718607036|Nifty_prices25461

**6.Compare stock prices (^GSPC) with crude oil prices on the same dates**

In [ ]:
cursor.execute("""
    SELECT
      s.date,
      s.close AS sp500_price,
      o.price_inr AS crude_oil_price
    FROM stock_prices s
    JOIN oil_prices o
       ON s.date=o.date
    WHERE s.ticker='^GSPC'
    ORDER BY s.date;
""")
rows=cursor.fetchall()
for row in rows:
  __builtins__.print(f"Date:{row[0]}|S&P 500 Price{row[1]}|Crude Oil Price{row[2]}")

Date:2020-01-02|S&P 500 Price3257.85009765625|Crude Oil Price61.17
Date:2020-01-03|S&P 500 Price3234.85009765625|Crude Oil Price63
Date:2020-01-06|S&P 500 Price3246.280029296875|Crude Oil Price63.27
Date:2020-01-07|S&P 500 Price3237.179931640625|Crude Oil Price62.7
Date:2020-01-08|S&P 500 Price3253.050048828125|Crude Oil Price59.65
Date:2020-01-09|S&P 500 Price3274.699951171875|Crude Oil Price59.56
Date:2020-01-10|S&P 500 Price3265.35009765625|Crude Oil Price59.02
Date:2020-01-13|S&P 500 Price3288.1298828125|Crude Oil Price58.17
Date:2020-01-14|S&P 500 Price3283.14990234375|Crude Oil Price58.34
Date:2020-01-15|S&P 500 Price3289.2900390625|Crude Oil Price57.86
Date:2020-01-16|S&P 500 Price3316.81005859375|Crude Oil Price58.52
Date:2020-01-17|S&P 500 Price3329.6201171875|Crude Oil Price58.55
Date:2020-01-21|S&P 500 Price3320.7900390625|Crude Oil Price58.25
Date:2020-01-22|S&P 500 Price3321.75|Crude Oil Price56.76
Date:2020-01-23|S&P 500 Price3325.5400390625|Crude Oil Price55.51
Date:2020-01-24|S&P 500 Price3295.469970703125|Crude Oil Price54.09
Date:2020-01-27|S&P 500 Price3243.6298828125|Crude Oil Price53.09
Date:2020-01-28|S&P 500 Price3276.239990234375|Crude Oil Price53.33
Date:2020-01-29|S&P 500 Price3273.39990234375|Crude Oil Price53.29
Date:2020-01-30|S&P 500 Price3283.659912109375|Crude Oil Price52.19
Date:2020-01-31|S&P 500 Price3225.52001953125|Crude Oil Price51.58
Date:2020-02-03|S&P 500 Price3248.919921875|Crude Oil Price50.06
Date:2020-02-04|S&P 500 Price3297.590087890625|Crude Oil Price49.59
Date:2020-02-05|S&P 500 Price3334.68994140625|Crude Oil Price50.87
Date:2020-02-06|S&P 500 Price3345.780029296875|Crude Oil Price50.94
Date:2020-02-07|S&P 500 Price3327.7099609375|Crude Oil Price50.34
Date:2020-02-10|S&P 500 Price3352.090087890625|Crude Oil Price49.59
Date:2020-02-11|S&P 500 Price3357.75|Crude Oil Price50
Date:2020-02-12|S&P 500 Price3379.449951171875|Crude Oil Price51.13
Date:2020-02-13|S&P 500 Price3373.93994140625|Crude Oil Price51.41
Date:2020-02-14|S&P 500 Price3380.159912109375|Crude Oil Price52.03
Date:2020-02-18|S&P 500 Price3370.2900390625|Crude Oil Price52.1
Date:2020-02-19|S&P 500 Price3386.14990234375|Crude Oil Price53.31
Date:2020-02-20|S&P 500 Price3373.22998046875|Crude Oil Price53.77
Date:2020-02-21|S&P 500 Price3337.75|Crude Oil Price53.36
Date:2020-02-24|S&P 500 Price3225.889892578125|Crude Oil Price51.36
Date:2020-02-25|S&P 500 Price3128.2099609375|Crude Oil Price49.78
Date:2020-02-26|S&P 500 Price3116.389892578125|Crude Oil Price48.67
Date:2020-02-27|S&P 500 Price2978.760009765625|Crude Oil Price47.17
Date:2020-02-28|S&P 500 Price2954.219970703125|Crude Oil Price44.83
Date:2020-03-02|S&P 500 Price3090.22998046875|Crude Oil Price46.78
Date:2020-03-03|S&P 500 Price3003.3701171875|Crude Oil Price47.27
Date:2020-03-04|S&P 500 Price3130.1201171875|Crude Oil Price46.78
Date:2020-03-05|S&P 500 Price3023.93994140625|Crude Oil Price45.9
Date:2020-03-06|S&P 500 Price2972.3701171875|Crude Oil Price41.14
Date:2020-03-09|S&P 500 Price2746.56005859375|Crude Oil Price31.05
Date:2020-03-10|S&P 500 Price2882.22998046875|Crude Oil Price34.47
Date:2020-03-11|S&P 500 Price2741.3798828125|Crude Oil Price33.13
Date:2020-03-12|S&P 500 Price2480.639892578125|Crude Oil Price31.56
Date:2020-03-13|S&P 500 Price2711.02001953125|Crude Oil Price31.72
Date:2020-03-16|S&P 500 Price2386.1298828125|Crude Oil Price28.96
Date:2020-03-17|S&P 500 Price2529.18994140625|Crude Oil Price26.96
Date:2020-03-18|S&P 500 Price2398.10009765625|Crude Oil Price20.48
Date:2020-03-19|S&P 500 Price2409.389892578125|Crude Oil Price25.09
Date:2020-03-20|S&P 500 Price2304.919921875|Crude Oil Price19.48
Date:2020-03-23|S&P 500 Price2237.39990234375|Crude Oil Price23.33
Date:2020-03-24|S&P 500 Price2447.330078125|Crude Oil Price21.03
Date:2020-03-25|S&P 500 Price2475.56005859375|Crude Oil Price20.75
Date:2020-03-26|S&P 500 Price2630.070068359375|Crude Oil Price16.6
Date:2020-03-27|S&P 500 Price2541.469970703125|Crude Oil Price15.48
Date:2020-03-30|S&P 500 Price2626.64990234375|Crude Oil Price14.1
Date:2020-03-31|S&P 500 Price2584.590087890625|Crude Oil Price20.51
Date:2020-04-01|S&P 500 Price2470.5|Crude Oil Price20.28
Date:2020-04-02|S&P 500 Price2526.89990234375|Crude Oil Price25.18
Date:2020-04-03|S&P 500 Price2488.64990234375|Crude Oil Price28.36
Date:2020-04-06|S&P 500 Price2663.679931640625|Crude Oil Price26.21
Date:2020-04-07|S&P 500 Price2659.409912109375|Crude Oil Price23.54
Date:2020-04-08|S&P 500 Price2749.97998046875|Crude Oil Price24.97
Date:2020-04-09|S&P 500 Price2789.820068359375|Crude Oil Price22.9
Date:2020-04-13|S&P 500 Price2761.6298828125|Crude Oil Price22.36
Date:2020-04-14|S&P 500 Price2846.06005859375|Crude Oil Price20.15
Date:2020-04-15|S&P 500 Price2783.360107421875|Crude Oil Price19.96
Date:2020-04-16|S&P 500 Price2799.550048828125|Crude Oil Price19.82
Date:2020-04-17|S&P 500 Price2874.56005859375|Crude Oil Price18.31
Date:2020-04-20|S&P 500 Price2823.159912109375|Crude Oil Price-36.98
Date:2020-04-21|S&P 500 Price2736.56005859375|Crude Oil Price8.91
Date:2020-04-22|S&P 500 Price2799.31005859375|Crude Oil Price13.64
Date:2020-04-23|S&P 500 Price2797.800048828125|Crude Oil Price15.06
Date:2020-04-24|S&P 500 Price2836.739990234375|Crude Oil Price15.99
Date:2020-04-27|S&P 500 Price2878.47998046875|Crude Oil Price12.17
Date:2020-04-28|S&P 500 Price2863.389892578125|Crude Oil Price12.4
Date:2020-04-29|S&P 500 Price2939.510009765625|Crude Oil Price15.04
Date:2020-04-30|S&P 500 Price2912.429931640625|Crude Oil Price19.23
Date:2020-05-01|S&P 500 Price2830.7099609375|Crude Oil Price19.72
Date:2020-05-04|S&P 500 Price2842.739990234375|Crude Oil Price20.47
Date:2020-05-05|S&P 500 Price2868.43994140625|Crude Oil Price24.56
Date:2020-05-06|S&P 500 Price2848.419921875|Crude Oil Price23.88
Date:2020-05-07|S&P 500 Price2881.18994140625|Crude Oil Price23.68
Date:2020-05-08|S&P 500 Price2929.800048828125|Crude Oil Price24.73
Date:2020-05-11|S&P 500 Price2930.18994140625|Crude Oil Price24.02
Date:2020-05-12|S&P 500 Price2870.1201171875|Crude Oil Price25.76
Date:2020-05-13|S&P 500 Price2820|Crude Oil Price25.37
Date:2020-05-14|S&P 500 Price2852.5|Crude Oil Price27.4
Date:2020-05-15|S&P 500 Price2863.699951171875|Crude Oil Price29.44
Date:2020-05-18|S&P 500 Price2953.909912109375|Crude Oil Price31.83
Date:2020-05-19|S&P 500 Price2922.93994140625|Crude Oil Price32.3
Date:2020-05-20|S&P 500 Price2971.610107421875|Crude Oil Price33.56
Date:2020-05-21|S&P 500 Price2948.510009765625|Crude Oil Price34.3
Date:2020-05-22|S&P 500 Price2955.449951171875|Crude Oil Price33.49
Date:2020-05-26|S&P 500 Price2991.77001953125|Crude Oil Price34.7
Date:2020-05-27|S&P 500 Price3036.1298828125|Crude Oil Price32.8
Date:2020-05-28|S&P 500 Price3029.72998046875|Crude Oil Price33.67
Date:2020-05-29|S&P 500 Price3044.31005859375|Crude Oil Price35.57
Date:2020-06-01|S&P 500 Price3055.72998046875|Crude Oil Price35.49
Date:2020-06-02|S&P 500 Price3080.820068359375|Crude Oil Price36.88
Date:2020-06-03|S&P 500 Price3122.8701171875|Crude Oil Price37.33
Date:2020-06-04|S&P 500 Price3112.35009765625|Crude Oil Price37.42
Date:2020-06-05|S&P 500 Price3193.929931640625|Crude Oil Price39.49
Date:2020-06-08|S&P 500 Price3232.389892578125|Crude Oil Price38.17
Date:2020-06-09|S&P 500 Price3207.179931640625|Crude Oil Price38.98
Date:2020-06-10|S&P 500 Price3190.139892578125|Crude Oil Price39.54
Date:2020-06-11|S&P 500 Price3002.10009765625|Crude Oil Price36.43
Date:2020-06-12|S&P 500 Price3041.31005859375|Crude Oil Price36.24
Date:2020-06-15|S&P 500 Price3066.590087890625|Crude Oil Price37.07
Date:2020-06-16|S&P 500 Price3124.739990234375|Crude Oil Price38.26
Date:2020-06-17|S&P 500 Price3113.489990234375|Crude Oil Price37.91
Date:2020-06-18|S&P 500 Price3115.340087890625|Crude Oil Price38.79
Date:2020-06-19|S&P 500 Price3097.739990234375|Crude Oil Price39.72
Date:2020-06-22|S&P 500 Price3117.860107421875|Crude Oil Price40.6
Date:2020-06-23|S&P 500 Price3131.2900390625|Crude Oil Price40.4
Date:2020-06-24|S&P 500 Price3050.330078125|Crude Oil Price37.91
Date:2020-06-25|S&P 500 Price3083.760009765625|Crude Oil Price38.66
Date:2020-06-26|S&P 500 Price3009.050048828125|Crude Oil Price38.53
Date:2020-06-29|S&P 500 Price3053.239990234375|Crude Oil Price39.67
Date:2020-06-30|S&P 500 Price3100.2900390625|Crude Oil Price39.27
Date:2020-07-01|S&P 500 Price3115.860107421875|Crude Oil Price39.88
Date:2020-07-02|S&P 500 Price3130.010009765625|Crude Oil Price40.57
Date:2020-07-06|S&P 500 Price3179.719970703125|Crude Oil Price40.51
Date:2020-07-07|S&P 500 Price3145.320068359375|Crude Oil Price40.59
Date:2020-07-08|S&P 500 Price3169.93994140625|Crude Oil Price40.91
Date:2020-07-09|S&P 500 Price3152.050048828125|Crude Oil Price39.64
Date:2020-07-10|S&P 500 Price3185.0400390625|Crude Oil Price40.56
Date:2020-07-13|S&P 500 Price3155.219970703125|Crude Oil Price40.06
Date:2020-07-14|S&P 500 Price3197.52001953125|Crude Oil Price40.3
Date:2020-07-15|S&P 500 Price3226.56005859375|Crude Oil Price41.2
Date:2020-07-16|S&P 500 Price3215.570068359375|Crude Oil Price40.74
Date:2020-07-17|S&P 500 Price3224.72998046875|Crude Oil Price40.55
Date:2020-07-20|S&P 500 Price3251.840087890625|Crude Oil Price40.83
Date:2020-07-21|S&P 500 Price3257.300048828125|Crude Oil Price41.76
Date:2020-07-22|S&P 500 Price3276.02001953125|Crude Oil Price41.88
Date:2020-07-23|S&P 500 Price3235.659912109375|Crude Oil Price40.99
Date:2020-07-24|S&P 500 Price3215.6298828125|Crude Oil Price41.23
Date:2020-07-27|S&P 500 Price3239.409912109375|Crude Oil Price41.46
Date:2020-07-28|S&P 500 Price3218.43994140625|Crude Oil Price40.89
Date:2020-07-29|S&P 500 Price3258.43994140625|Crude Oil Price41.13
Date:2020-07-30|S&P 500 Price3246.219970703125|Crude Oil Price39.85
Date:2020-07-31|S&P 500 Price3271.1201171875|Crude Oil Price40.1
Date:2020-08-03|S&P 500 Price3294.610107421875|Crude Oil Price40.83
Date:2020-08-04|S&P 500 Price3306.510009765625|Crude Oil Price41.67
Date:2020-08-05|S&P 500 Price3327.77001953125|Crude Oil Price42.25
Date:2020-08-06|S&P 500 Price3349.159912109375|Crude Oil Price41.93
Date:2020-08-07|S&P 500 Price3351.280029296875|Crude Oil Price41.16
Date:2020-08-10|S&P 500 Price3360.469970703125|Crude Oil Price41.94
Date:2020-08-11|S&P 500 Price3333.68994140625|Crude Oil Price41.53
Date:2020-08-12|S&P 500 Price3380.35009765625|Crude Oil Price42.6
Date:2020-08-13|S&P 500 Price3373.429931640625|Crude Oil Price42.26
Date:2020-08-14|S&P 500 Price3372.85009765625|Crude Oil Price42.05
Date:2020-08-17|S&P 500 Price3381.989990234375|Crude Oil Price42.89
Date:2020-08-18|S&P 500 Price3389.780029296875|Crude Oil Price42.89
Date:2020-08-19|S&P 500 Price3374.85009765625|Crude Oil Price42.91
Date:2020-08-20|S&P 500 Price3385.510009765625|Crude Oil Price42.62
Date:2020-08-21|S&P 500 Price3397.159912109375|Crude Oil Price42.32
Date:2020-08-24|S&P 500 Price3431.280029296875|Crude Oil Price42.44
Date:2020-08-25|S&P 500 Price3443.6201171875|Crude Oil Price43.17
Date:2020-08-26|S&P 500 Price3478.72998046875|Crude Oil Price43.21
Date:2020-08-27|S&P 500 Price3484.550048828125|Crude Oil Price42.88
Date:2020-08-28|S&P 500 Price3508.010009765625|Crude Oil Price42.96
Date:2020-08-31|S&P 500 Price3500.31005859375|Crude Oil Price42.61
Date:2020-09-01|S&P 500 Price3526.64990234375|Crude Oil Price42.76
Date:2020-09-02|S&P 500 Price3580.840087890625|Crude Oil Price42.76
Date:2020-09-03|S&P 500 Price3455.06005859375|Crude Oil Price41.39
Date:2020-09-04|S&P 500 Price3426.9599609375|Crude Oil Price39.69
Date:2020-09-08|S&P 500 Price3331.840087890625|Crude Oil Price36.87
Date:2020-09-09|S&P 500 Price3398.9599609375|Crude Oil Price38.05
Date:2020-09-10|S&P 500 Price3339.18994140625|Crude Oil Price37.25
Date:2020-09-11|S&P 500 Price3340.969970703125|Crude Oil Price37.33
Date:2020-09-14|S&P 500 Price3383.5400390625|Crude Oil Price37.23
Date:2020-09-15|S&P 500 Price3401.199951171875|Crude Oil Price38.29
Date:2020-09-16|S&P 500 Price3385.489990234375|Crude Oil Price40.17
Date:2020-09-17|S&P 500 Price3357.010009765625|Crude Oil Price40.99
Date:2020-09-18|S&P 500 Price3319.469970703125|Crude Oil Price41.09
Date:2020-09-21|S&P 500 Price3281.06005859375|Crude Oil Price39.26
Date:2020-09-22|S&P 500 Price3315.570068359375|Crude Oil Price39.55
Date:2020-09-23|S&P 500 Price3236.919921875|Crude Oil Price39.92
Date:2020-09-24|S&P 500 Price3246.590087890625|Crude Oil Price40.11
Date:2020-09-25|S&P 500 Price3298.4599609375|Crude Oil Price40.06
Date:2020-09-28|S&P 500 Price3351.60009765625|Crude Oil Price40.47
Date:2020-09-29|S&P 500 Price3335.469970703125|Crude Oil Price39.03
Date:2020-09-30|S&P 500 Price3363|Crude Oil Price40.05
Date:2020-10-01|S&P 500 Price3380.800048828125|Crude Oil Price38.51
Date:2020-10-02|S&P 500 Price3348.419921875|Crude Oil Price36.9
Date:2020-10-05|S&P 500 Price3408.60009765625|Crude Oil Price39.12
Date:2020-10-06|S&P 500 Price3360.969970703125|Crude Oil Price40.52
Date:2020-10-07|S&P 500 Price3419.43994140625|Crude Oil Price39.82
Date:2020-10-08|S&P 500 Price3446.830078125|Crude Oil Price41.04
Date:2020-10-09|S&P 500 Price3477.139892578125|Crude Oil Price40.44
Date:2020-10-12|S&P 500 Price3534.219970703125|Crude Oil Price39.22
Date:2020-10-13|S&P 500 Price3511.929931640625|Crude Oil Price40.03
Date:2020-10-14|S&P 500 Price3488.669921875|Crude Oil Price40.86
Date:2020-10-15|S&P 500 Price3483.340087890625|Crude Oil Price40.84
Date:2020-10-16|S&P 500 Price3483.81005859375|Crude Oil Price40.7
Date:2020-10-19|S&P 500 Price3426.919921875|Crude Oil Price40.69
Date:2020-10-20|S&P 500 Price3443.1201171875|Crude Oil Price41.37
Date:2020-10-21|S&P 500 Price3435.56005859375|Crude Oil Price39.88
Date:2020-10-22|S&P 500 Price3453.489990234375|Crude Oil Price40.46
Date:2020-10-23|S&P 500 Price3465.389892578125|Crude Oil Price39.73
Date:2020-10-26|S&P 500 Price3400.969970703125|Crude Oil Price38.39
Date:2020-10-27|S&P 500 Price3390.679931640625|Crude Oil Price39.34
Date:2020-10-28|S&P 500 Price3271.030029296875|Crude Oil Price37.27
Date:2020-10-29|S&P 500 Price3310.110107421875|Crude Oil Price35.94
Date:2020-10-30|S&P 500 Price3269.9599609375|Crude Oil Price35.64
Date:2020-11-02|S&P 500 Price3310.239990234375|Crude Oil Price36.6
Date:2020-11-03|S&P 500 Price3369.159912109375|Crude Oil Price37.44
Date:2020-11-04|S&P 500 Price3443.43994140625|Crude Oil Price38.97
Date:2020-11-05|S&P 500 Price3510.449951171875|Crude Oil Price38.56
Date:2020-11-06|S&P 500 Price3509.43994140625|Crude Oil Price36.97
Date:2020-11-09|S&P 500 Price3550.5|Crude Oil Price40.05
Date:2020-11-10|S&P 500 Price3545.530029296875|Crude Oil Price41.18
Date:2020-11-11|S&P 500 Price3572.659912109375|Crude Oil Price41.23
Date:2020-11-12|S&P 500 Price3537.010009765625|Crude Oil Price40.9
Date:2020-11-13|S&P 500 Price3585.14990234375|Crude Oil Price39.93
Date:2020-11-16|S&P 500 Price3626.909912109375|Crude Oil Price41.14
Date:2020-11-17|S&P 500 Price3609.530029296875|Crude Oil Price41.24
Date:2020-11-18|S&P 500 Price3567.7900390625|Crude Oil Price41.64
Date:2020-11-19|S&P 500 Price3581.8701171875|Crude Oil Price41.57
Date:2020-11-20|S&P 500 Price3557.5400390625|Crude Oil Price41.99
Date:2020-11-23|S&P 500 Price3577.590087890625|Crude Oil Price42.91
Date:2020-11-24|S&P 500 Price3635.409912109375|Crude Oil Price44.71
Date:2020-11-25|S&P 500 Price3629.64990234375|Crude Oil Price45.58
Date:2020-11-30|S&P 500 Price3621.6298828125|Crude Oil Price45.2
Date:2020-12-01|S&P 500 Price3662.449951171875|Crude Oil Price44.54
Date:2020-12-02|S&P 500 Price3669.010009765625|Crude Oil Price45.23
Date:2020-12-03|S&P 500 Price3666.719970703125|Crude Oil Price45.65
Date:2020-12-04|S&P 500 Price3699.1201171875|Crude Oil Price46.23
Date:2020-12-07|S&P 500 Price3691.9599609375|Crude Oil Price45.72
Date:2020-12-08|S&P 500 Price3702.25|Crude Oil Price45.64
Date:2020-12-09|S&P 500 Price3672.820068359375|Crude Oil Price45.48
Date:2020-12-10|S&P 500 Price3668.10009765625|Crude Oil Price46.76
Date:2020-12-11|S&P 500 Price3663.4599609375|Crude Oil Price46.59
Date:2020-12-14|S&P 500 Price3647.489990234375|Crude Oil Price47.02
Date:2020-12-15|S&P 500 Price3694.6201171875|Crude Oil Price47.58
Date:2020-12-16|S&P 500 Price3701.169921875|Crude Oil Price47.86
Date:2020-12-17|S&P 500 Price3722.47998046875|Crude Oil Price48.34
Date:2020-12-18|S&P 500 Price3709.409912109375|Crude Oil Price49.04
Date:2020-12-21|S&P 500 Price3694.919921875|Crude Oil Price47.79
Date:2020-12-22|S&P 500 Price3687.260009765625|Crude Oil Price47.02
Date:2020-12-23|S&P 500 Price3690.010009765625|Crude Oil Price47.94
Date:2020-12-24|S&P 500 Price3703.06005859375|Crude Oil Price48.18
Date:2020-12-28|S&P 500 Price3735.360107421875|Crude Oil Price47.5
Date:2020-12-29|S&P 500 Price3727.0400390625|Crude Oil Price47.85
Date:2020-12-30|S&P 500 Price3732.0400390625|Crude Oil Price48.24
Date:2020-12-31|S&P 500 Price3756.070068359375|Crude Oil Price48.35
Date:2021-01-04|S&P 500 Price3700.64990234375|Crude Oil Price47.47
Date:2021-01-05|S&P 500 Price3726.860107421875|Crude Oil Price49.78
Date:2021-01-06|S&P 500 Price3748.139892578125|Crude Oil Price50.45
Date:2021-01-07|S&P 500 Price3803.7900390625|Crude Oil Price50.63
Date:2021-01-08|S&P 500 Price3824.679931640625|Crude Oil Price52.14
Date:2021-01-11|S&P 500 Price3799.610107421875|Crude Oil Price52.15
Date:2021-01-12|S&P 500 Price3801.18994140625|Crude Oil Price53.08
Date:2021-01-13|S&P 500 Price3809.840087890625|Crude Oil Price52.81
Date:2021-01-14|S&P 500 Price3795.5400390625|Crude Oil Price53.47
Date:2021-01-15|S&P 500 Price3768.25|Crude Oil Price52.25
Date:2021-01-19|S&P 500 Price3798.909912109375|Crude Oil Price52.87
Date:2021-01-20|S&P 500 Price3851.85009765625|Crude Oil Price53.16
Date:2021-01-21|S&P 500 Price3853.070068359375|Crude Oil Price53
Date:2021-01-22|S&P 500 Price3841.469970703125|Crude Oil Price52.28
Date:2021-01-25|S&P 500 Price3855.360107421875|Crude Oil Price52.78
Date:2021-01-26|S&P 500 Price3849.6201171875|Crude Oil Price52.61
Date:2021-01-27|S&P 500 Price3750.77001953125|Crude Oil Price52.81
Date:2021-01-28|S&P 500 Price3787.3798828125|Crude Oil Price52.26
Date:2021-01-29|S&P 500 Price3714.239990234375|Crude Oil Price52.16
Date:2021-02-01|S&P 500 Price3773.860107421875|Crude Oil Price53.55
Date:2021-02-02|S&P 500 Price3826.31005859375|Crude Oil Price54.77
Date:2021-02-03|S&P 500 Price3830.169921875|Crude Oil Price55.67
Date:2021-02-04|S&P 500 Price3871.739990234375|Crude Oil Price56.19
Date:2021-02-05|S&P 500 Price3886.830078125|Crude Oil Price56.8
Date:2021-02-08|S&P 500 Price3915.590087890625|Crude Oil Price57.95
Date:2021-02-09|S&P 500 Price3911.22998046875|Crude Oil Price58.34
Date:2021-02-10|S&P 500 Price3909.8798828125|Crude Oil Price58.69
Date:2021-02-11|S&P 500 Price3916.3798828125|Crude Oil Price58.22
Date:2021-02-12|S&P 500 Price3934.830078125|Crude Oil Price59.5
Date:2021-02-16|S&P 500 Price3932.590087890625|Crude Oil Price60.07
Date:2021-02-17|S&P 500 Price3931.330078125|Crude Oil Price61.09
Date:2021-02-18|S&P 500 Price3913.969970703125|Crude Oil Price60.4
Date:2021-02-19|S&P 500 Price3906.7099609375|Crude Oil Price59.12
Date:2021-02-22|S&P 500 Price3876.5|Crude Oil Price61.67
Date:2021-02-23|S&P 500 Price3881.3701171875|Crude Oil Price61.66
Date:2021-02-24|S&P 500 Price3925.429931640625|Crude Oil Price63.21
Date:2021-02-25|S&P 500 Price3829.340087890625|Crude Oil Price63.43
Date:2021-02-26|S&P 500 Price3811.14990234375|Crude Oil Price61.55
Date:2021-03-01|S&P 500 Price3901.820068359375|Crude Oil Price60.54
Date:2021-03-02|S&P 500 Price3870.2900390625|Crude Oil Price59.7
Date:2021-03-03|S&P 500 Price3819.719970703125|Crude Oil Price61.33
Date:2021-03-04|S&P 500 Price3768.469970703125|Crude Oil Price63.81
Date:2021-03-05|S&P 500 Price3841.93994140625|Crude Oil Price66.08
Date:2021-03-08|S&P 500 Price3821.35009765625|Crude Oil Price65.03
Date:2021-03-09|S&P 500 Price3875.43994140625|Crude Oil Price64.02
Date:2021-03-10|S&P 500 Price3898.81005859375|Crude Oil Price64.45
Date:2021-03-11|S&P 500 Price3939.340087890625|Crude Oil Price66.02

**7.Correlate Bitcoin closing price with crude oil closing price (same date)**

In [ ]:
cursor.execute("""
    SELECT
      c.date,
      c.price_inr AS bitcoin_price,
      o.price_inr AS crude_oil_price
    FROM crypto_prices c
    JOIN oil_prices o
       ON c.date=o.date
    WHERE c.coin_id='bitcoin'
    ORDER BY c.date;
""")
rows=cursor.fetchall()
df=pd.DataFrame(rows,columns=["Date","Bitcoin","Crude Oil"])
correlation=df["Bitcoin"].corr(df["Crude Oil"])
print("Correlation:",correlation)
for row in rows:
  print(f"Date:{row[0]}|Bitcoin Price:{row[1]}| Crude Oil Price:{row[2]}")

Correlation: 0.13877058115730476
Date:2025-02-28|Bitcoin Price:7397416.663356487| Crude Oil Price:69.97
Date:2025-03-03|Bitcoin Price:8244472.61232367| Crude Oil Price:68.63
Date:2025-03-04|Bitcoin Price:7521257.854514662| Crude Oil Price:68.47
Date:2025-03-05|Bitcoin Price:7615008.334491884| Crude Oil Price:66.58
Date:2025-03-06|Bitcoin Price:7869430.047939962| Crude Oil Price:66.62
Date:2025-03-07|Bitcoin Price:7841736.557001183| Crude Oil Price:67.29
Date:2025-03-10|Bitcoin Price:7035607.792612969| Crude Oil Price:66.31
Date:2025-03-11|Bitcoin Price:6882112.04135304| Crude Oil Price:66.52
Date:2025-03-12|Bitcoin Price:7220111.199834512| Crude Oil Price:67.65
Date:2025-03-13|Bitcoin Price:7311397.167011021| Crude Oil Price:66.82
Date:2025-03-14|Bitcoin Price:7049331.751158462| Crude Oil Price:67.43
Date:2025-03-17|Bitcoin Price:7182714.546311197| Crude Oil Price:67.84
Date:2025-03-18|Bitcoin Price:7307625.213417549| Crude Oil Price:67.49
Date:2025-03-19|Bitcoin Price:7166130.900539224| Crude Oil Price:67.4
Date:2025-03-20|Bitcoin Price:7495414.341859128| Crude Oil Price:68.55
Date:2025-03-21|Bitcoin Price:7275140.94449613| Crude Oil Price:68.52
Date:2025-03-24|Bitcoin Price:7377568.408827406| Crude Oil Price:69.46
Date:2025-03-25|Bitcoin Price:7471026.999919416| Crude Oil Price:69.48
Date:2025-03-26|Bitcoin Price:7490943.665690553| Crude Oil Price:70.05
Date:2025-03-27|Bitcoin Price:7448415.462567322| Crude Oil Price:70.3
Date:2025-03-28|Bitcoin Price:7474953.075439318| Crude Oil Price:69.74
Date:2025-03-31|Bitcoin Price:7044678.366106417| Crude Oil Price:71.87
Date:2025-04-01|Bitcoin Price:7049110.1215911815| Crude Oil Price:71.61
Date:2025-04-02|Bitcoin Price:7295181.762562074| Crude Oil Price:72.12
Date:2025-04-03|Bitcoin Price:7072204.244187081| Crude Oil Price:67.43
Date:2025-04-04|Bitcoin Price:7092361.1660758825| Crude Oil Price:62.42
Date:2025-04-07|Bitcoin Price:6689389.08502666| Crude Oil Price:61.05
Date:2025-04-08|Bitcoin Price:6810911.664670934| Crude Oil Price:60.04
Date:2025-04-09|Bitcoin Price:6597493.475585312| Crude Oil Price:62.63
Date:2025-04-10|Bitcoin Price:7122745.761241968| Crude Oil Price:60.57
Date:2025-04-11|Bitcoin Price:6866025.560636041| Crude Oil Price:61.91
Date:2025-04-14|Bitcoin Price:7187425.846627208| Crude Oil Price:61.99
Date:2025-04-15|Bitcoin Price:7271599.950976666| Crude Oil Price:61.74
Date:2025-04-16|Bitcoin Price:7171572.949306771| Crude Oil Price:62.88
Date:2025-04-17|Bitcoin Price:7201187.29755112| Crude Oil Price:65.07
Date:2025-04-21|Bitcoin Price:7263849.726468839| Crude Oil Price:63.48
Date:2025-04-22|Bitcoin Price:7447341.987486609| Crude Oil Price:64.6
Date:2025-04-23|Bitcoin Price:7975735.892697773| Crude Oil Price:62.64
Date:2025-04-24|Bitcoin Price:8003280.21321444| Crude Oil Price:63.55
Date:2025-04-25|Bitcoin Price:8000169.783417303| Crude Oil Price:63.85
Date:2025-04-28|Bitcoin Price:8009924.38113424| Crude Oil Price:63.3
Date:2025-04-29|Bitcoin Price:8092853.390805625| Crude Oil Price:61.84
Date:2025-04-30|Bitcoin Price:8027696.597798843| Crude Oil Price:59.55
Date:2025-05-01|Bitcoin Price:7968688.759781316| Crude Oil Price:60.59
Date:2025-05-02|Bitcoin Price:8167058.515487802| Crude Oil Price:59.67
Date:2025-05-05|Bitcoin Price:7973099.086450076| Crude Oil Price:58.5
Date:2025-05-06|Bitcoin Price:7980688.008703099| Crude Oil Price:60.42
Date:2025-05-07|Bitcoin Price:8207545.052481962| Crude Oil Price:59.42
Date:2025-05-08|Bitcoin Price:8229539.783984127| Crude Oil Price:61.25
Date:2025-05-09|Bitcoin Price:8868161.595114123| Crude Oil Price:62.37
Date:2025-05-12|Bitcoin Price:8882429.185761888| Crude Oil Price:63.32
Date:2025-05-13|Bitcoin Price:8739740.641206343| Crude Oil Price:65.04
Date:2025-05-14|Bitcoin Price:8860925.91388854| Crude Oil Price:64.48
Date:2025-05-15|Bitcoin Price:8854656.259617174| Crude Oil Price:63.03
Date:2025-05-16|Bitcoin Price:8861418.050018335| Crude Oil Price:63.84
Date:2025-05-19|Bitcoin Price:9065676.354329923| Crude Oil Price:63.98
Date:2025-05-20|Bitcoin Price:9017978.28123392| Crude Oil Price:63.97
Date:2025-05-21|Bitcoin Price:9134061.037906067| Crude Oil Price:62.93
Date:2025-05-22|Bitcoin Price:9387459.456660772| Crude Oil Price:62.55
Date:2025-05-23|Bitcoin Price:9591418.421810476| Crude Oil Price:62.89
Date:2025-05-27|Bitcoin Price:9314436.685236426| Crude Oil Price:61.61
Date:2025-05-28|Bitcoin Price:9310175.102671716| Crude Oil Price:62.54
Date:2025-05-29|Bitcoin Price:9208280.990679564| Crude Oil Price:61.66
Date:2025-05-30|Bitcoin Price:9026592.666677358| Crude Oil Price:61.46
Date:2025-06-02|Bitcoin Price:9040802.274014382| Crude Oil Price:63.27
Date:2025-06-03|Bitcoin Price:9038740.617012177| Crude Oil Price:64.1
Date:2025-06-04|Bitcoin Price:9036688.899610182| Crude Oil Price:63.57
Date:2025-06-05|Bitcoin Price:9003749.459208991| Crude Oil Price:64.06
Date:2025-06-06|Bitcoin Price:8729536.730077919| Crude Oil Price:65.3
Date:2025-06-09|Bitcoin Price:9066867.46885247| Crude Oil Price:65.99
Date:2025-06-10|Bitcoin Price:9455619.179043707| Crude Oil Price:65.66
Date:2025-06-11|Bitcoin Price:9440056.689266069| Crude Oil Price:68.91
Date:2025-06-12|Bitcoin Price:9288882.88186932| Crude Oil Price:68.73
Date:2025-06-13|Bitcoin Price:9081227.025134273| Crude Oil Price:73.84
Date:2025-06-16|Bitcoin Price:9090411.27477335| Crude Oil Price:72.53
Date:2025-06-17|Bitcoin Price:9208980.453923177| Crude Oil Price:75.62
Date:2025-06-18|Bitcoin Price:9039952.955659283| Crude Oil Price:75.89
Date:2025-06-20|Bitcoin Price:9080584.318377115| Crude Oil Price:75.72
Date:2025-06-23|Bitcoin Price:8731873.284684414| Crude Oil Price:69.36
Date:2025-06-24|Bitcoin Price:9111429.945371069| Crude Oil Price:65.45
Date:2025-06-25|Bitcoin Price:9111165.38661966| Crude Oil Price:65.98
Date:2025-06-26|Bitcoin Price:9223086.808659252| Crude Oil Price:66.44
Date:2025-06-27|Bitcoin Price:9165684.099752242| Crude Oil Price:66.66
Date:2025-06-30|Bitcoin Price:9263092.465181679| Crude Oil Price:66.3
Date:2025-07-01|Bitcoin Price:9181709.414667957| Crude Oil Price:66.64
Date:2025-07-02|Bitcoin Price:9054321.250569785| Crude Oil Price:68.66
Date:2025-07-03|Bitcoin Price:9325640.339018358| Crude Oil Price:68.13
Date:2025-07-07|Bitcoin Price:9337523.923073687| Crude Oil Price:69.16
Date:2025-07-08|Bitcoin Price:9302203.177316865| Crude Oil Price:69.55
Date:2025-07-09|Bitcoin Price:9338122.035800587| Crude Oil Price:69.61
Date:2025-07-10|Bitcoin Price:9541743.483380785| Crude Oil Price:67.78
Date:2025-07-11|Bitcoin Price:9934947.612549465| Crude Oil Price:69.63
Date:2025-07-14|Bitcoin Price:10222853.345055208| Crude Oil Price:68.19
Date:2025-07-15|Bitcoin Price:10301939.218478084| Crude Oil Price:67.76
Date:2025-07-16|Bitcoin Price:10119542.204331392| Crude Oil Price:67.13
Date:2025-07-17|Bitcoin Price:10198739.393321177| Crude Oil Price:68.76
Date:2025-07-18|Bitcoin Price:10277885.47839658| Crude Oil Price:68.53
Date:2025-07-21|Bitcoin Price:10101549.352407157| Crude Oil Price:68.39
Date:2025-07-22|Bitcoin Price:10136533.758092493| Crude Oil Price:67.56
Date:2025-07-23|Bitcoin Price:10357349.26643955| Crude Oil Price:66.05
Date:2025-07-24|Bitcoin Price:10249425.74900696| Crude Oil Price:67.16
Date:2025-07-25|Bitcoin Price:10229427.683390176| Crude Oil Price:66.38
Date:2025-07-28|Bitcoin Price:10330494.375551593| Crude Oil Price:67.81
Date:2025-07-29|Bitcoin Price:10240072.841855934| Crude Oil Price:70.27
Date:2025-07-30|Bitcoin Price:10260715.669243045| Crude Oil Price:71.09
Date:2025-07-31|Bitcoin Price:10330510.927890545| Crude Oil Price:70.36
Date:2025-08-01|Bitcoin Price:10122552.718401065| Crude Oil Price:68.39
Date:2025-08-04|Bitcoin Price:9963363.104407016| Crude Oil Price:67.33
Date:2025-08-05|Bitcoin Price:10119947.866363142| Crude Oil Price:66.2
Date:2025-08-06|Bitcoin Price:10011721.5506572| Crude Oil Price:65.38
Date:2025-08-07|Bitcoin Price:10094655.435390146| Crude Oil Price:64.9
Date:2025-08-08|Bitcoin Price:10270107.263258504| Crude Oil Price:64.94
Date:2025-08-11|Bitcoin Price:10434491.300112702| Crude Oil Price:65.03
Date:2025-08-12|Bitcoin Price:10412275.449238887| Crude Oil Price:64.22
Date:2025-08-13|Bitcoin Price:10529495.638104321| Crude Oil Price:63.68
Date:2025-08-14|Bitcoin Price:10805439.78369676| Crude Oil Price:64.99
Date:2025-08-15|Bitcoin Price:10383230.847886154| Crude Oil Price:63.78
Date:2025-08-18|Bitcoin Price:10286533.101169772| Crude Oil Price:64.51
Date:2025-08-19|Bitcoin Price:10148644.242275473| Crude Oil Price:63.38
Date:2025-08-20|Bitcoin Price:9819786.419050021| Crude Oil Price:64.19
Date:2025-08-21|Bitcoin Price:9942066.543754837| Crude Oil Price:64.56
Date:2025-08-22|Bitcoin Price:9813063.27750558| Crude Oil Price:64.08
Date:2025-08-25|Bitcoin Price:9903221.35080575| Crude Oil Price:65.18
Date:2025-08-26|Bitcoin Price:9653212.189243559| Crude Oil Price:63.6
Date:2025-08-27|Bitcoin Price:9801777.668906499| Crude Oil Price:64.49
Date:2025-08-28|Bitcoin Price:9749130.25886824| Crude Oil Price:64.96
Date:2025-08-29|Bitcoin Price:9856302.06893481| Crude Oil Price:64.36
Date:2025-09-02|Bitcoin Price:9606486.0790093| Crude Oil Price:65.95
Date:2025-09-03|Bitcoin Price:9784574.242949013| Crude Oil Price:64.36
Date:2025-09-04|Bitcoin Price:9838796.609221794| Crude Oil Price:63.81
Date:2025-09-05|Bitcoin Price:9765163.284050079| Crude Oil Price:62.22
Date:2025-09-08|Bitcoin Price:9800346.003033817| Crude Oil Price:62.6
Date:2025-09-09|Bitcoin Price:9856054.84901548| Crude Oil Price:62.97
Date:2025-09-10|Bitcoin Price:9840553.151484529| Crude Oil Price:64.01
Date:2025-09-11|Bitcoin Price:10035954.764445597| Crude Oil Price:62.71
Date:2025-09-12|Bitcoin Price:10195205.098488238| Crude Oil Price:63.02
Date:2025-09-15|Bitcoin Price:10184894.127284445| Crude Oil Price:63.66
Date:2025-09-16|Bitcoin Price:10169238.650025213| Crude Oil Price:64.89
Date:2025-09-17|Bitcoin Price:10261685.530263504| Crude Oil Price:64.41
Date:2025-09-18|Bitcoin Price:10237752.888404036| Crude Oil Price:63.91
Date:2025-09-19|Bitcoin Price:10333070.25718556| Crude Oil Price:63.02
Date:2025-09-22|Bitcoin Price:10158260.693491202| Crude Oil Price:62.99
Date:2025-09-23|Bitcoin Price:9951646.271657305| Crude Oil Price:63.76
Date:2025-09-24|Bitcoin Price:9948492.512889242| Crude Oil Price:65.4
Date:2025-09-25|Bitcoin Price:10060469.351465985| Crude Oil Price:65.51
Date:2025-09-26|Bitcoin Price:9673068.167457229| Crude Oil Price:66.5
Date:2025-09-29|Bitcoin Price:9944472.608696878| Crude Oil Price:64.27
Date:2025-09-30|Bitcoin Price:10139763.924082505| Crude Oil Price:63.17
Date:2025-10-01|Bitcoin Price:10130020.723922314| Crude Oil Price:62.59
Date:2025-10-02|Bitcoin Price:10509252.859358784| Crude Oil Price:61.28
Date:2025-10-03|Bitcoin Price:10700725.995237181| Crude Oil Price:61.65
Date:2025-10-06|Bitcoin Price:10959365.064936124| Crude Oil Price:62.49
Date:2025-10-07|Bitcoin Price:11070472.246732509| Crude Oil Price:62.52
Date:2025-10-08|Bitcoin Price:10783920.730192943| Crude Oil Price:63.37
Date:2025-10-09|Bitcoin Price:10949945.97908964| Crude Oil Price:62.36
Date:2025-10-10|Bitcoin Price:10814774.599012492| Crude Oil Price:59.75
Date:2025-10-14|Bitcoin Price:10216224.051870666| Crude Oil Price:59.52
Date:2025-10-15|Bitcoin Price:10046351.075825775| Crude Oil Price:59.08
Date:2025-10-16|Bitcoin Price:9721344.884648668| Crude Oil Price:58.29
Date:2025-10-17|Bitcoin Price:9509774.024195194| Crude Oil Price:58.3
Date:2025-10-20|Bitcoin Price:9558930.877185136| Crude Oil Price:58.34
Date:2025-10-21|Bitcoin Price:9720308.914971137| Crude Oil Price:58.66
Date:2025-10-22|Bitcoin Price:9549158.301143315| Crude Oil Price:59.3
Date:2025-10-23|Bitcoin Price:9442499.946295625| Crude Oil Price:62.44
Date:2025-10-24|Bitcoin Price:9659976.397607893| Crude Oil Price:62.27
Date:2025-10-27|Bitcoin Price:10055171.794296525| Crude Oil Price:62.13
Date:2025-10-28|Bitcoin Price:10073474.454011032| Crude Oil Price:60.97
Date:2025-10-29|Bitcoin Price:9965129.220872145| Crude Oil Price:61.26
Date:2025-10-30|Bitcoin Price:9722166.86543983| Crude Oil Price:61.36
Date:2025-10-31|Bitcoin Price:9593893.17104472| Crude Oil Price:61.75
Date:2025-11-03|Bitcoin Price:9824421.072227614| Crude Oil Price:61.79
Date:2025-11-04|Bitcoin Price:9450928.858755054| Crude Oil Price:61.38
Date:2025-11-05|Bitcoin Price:9018317.599498693| Crude Oil Price:60.4
Date:2025-11-06|Bitcoin Price:9199126.082980732| Crude Oil Price:60.24
Date:2025-11-07|Bitcoin Price:8984607.813501872| Crude Oil Price:60.54
Date:2025-11-10|Bitcoin Price:9283589.00601575| Crude Oil Price:60.94
Date:2025-11-12|Bitcoin Price:9108594.696793688| Crude Oil Price:59.3
Date:2025-11-13|Bitcoin Price:8994239.327086337| Crude Oil Price:59.54
Date:2025-11-14|Bitcoin Price:8857694.85444411| Crude Oil Price:60.87
Date:2025-11-17|Bitcoin Price:8373085.239387692| Crude Oil Price:60.66
Date:2025-11-18|Bitcoin Price:8157780.455111292| Crude Oil Price:61.51
Date:2025-11-19|Bitcoin Price:8219844.429070548| Crude Oil Price:60.27
Date:2025-11-20|Bitcoin Price:8084502.70583037| Crude Oil Price:60.07
Date:2025-11-21|Bitcoin Price:7685198.360480496| Crude Oil Price:58.86
Date:2025-11-24|Bitcoin Price:7778520.446850556| Crude Oil Price:59.11
Date:2025-11-25|Bitcoin Price:7865475.253834086| Crude Oil Price:58.25
Date:2025-11-26|Bitcoin Price:7783791.323601658| Crude Oil Price:58.81
Date:2025-11-28|Bitcoin Price:8157156.351483771| Crude Oil Price:58.58
Date:2025-12-01|Bitcoin Price:8078246.317717989| Crude Oil Price:59.47
Date:2025-12-02|Bitcoin Price:7731939.31508293| Crude Oil Price:58.81
Date:2025-12-03|Bitcoin Price:8213485.439946512| Crude Oil Price:59.09
Date:2025-12-04|Bitcoin Price:8441734.894689914| Crude Oil Price:59.82
Date:2025-12-05|Bitcoin Price:8277612.193785475| Crude Oil Price:60.23
Date:2025-12-08|Bitcoin Price:8110183.521497487| Crude Oil Price:59.04
Date:2025-12-09|Bitcoin Price:8167418.75650716| Crude Oil Price:58.4
Date:2025-12-10|Bitcoin Price:8337407.11660591| Crude Oil Price:58.67
Date:2025-12-11|Bitcoin Price:8261440.281355997| Crude Oil Price:57.76
Date:2025-12-12|Bitcoin Price:8347818.307928058| Crude Oil Price:57.61
Date:2025-12-15|Bitcoin Price:7992348.231966222| Crude Oil Price:56.97
Date:2025-12-16|Bitcoin Price:7844409.288926788| Crude Oil Price:55.44
Date:2025-12-17|Bitcoin Price:7987315.985984798| Crude Oil Price:56.07
Date:2025-12-18|Bitcoin Price:7781471.915537124| Crude Oil Price:56.22
Date:2025-12-19|Bitcoin Price:7712879.171308659| Crude Oil Price:56.8
Date:2025-12-22|Bitcoin Price:7933999.65474005| Crude Oil Price:58.18
Date:2025-12-23|Bitcoin Price:7929162.75966298| Crude Oil Price:58.55
Date:2025-12-24|Bitcoin Price:7820620.968822208| Crude Oil Price:58.72
Date:2025-12-26|Bitcoin Price:7860175.221034703| Crude Oil Price:56.6
Date:2025-12-29|Bitcoin Price:7887770.596681177| Crude Oil Price:57.89
Date:2025-12-30|Bitcoin Price:7835388.056690424| Crude Oil Price:57.79
Date:2025-12-31|Bitcoin Price:7936951.056508718| Crude Oil Price:57.26
Date:2026-01-02|Bitcoin Price:7982611.090931888| Crude Oil Price:57.21
Date:2026-01-05|Bitcoin Price:8224912.970329631| Crude Oil Price:58.1
Date:2026-01-06|Bitcoin Price:8475311.204337161| Crude Oil Price:56.97
Date:2026-01-07|Bitcoin Price:8443838.294347357| Crude Oil Price:56.01
Date:2026-01-08|Bitcoin Price:8200790.873528976| Crude Oil Price:57.74
Date:2026-01-09|Bitcoin Price:8179932.125614385| Crude Oil Price:58.96
Date:2026-01-12|Bitcoin Price:8196362.9552232| Crude Oil Price:59.39
Date:2026-01-13|Bitcoin Price:8214254.506811856| Crude Oil Price:60.85
Date:2026-01-14|Bitcoin Price:8600260.479528198| Crude Oil Price:61.84
Date:2026-01-15|Bitcoin Price:8754772.557780331| Crude Oil Price:59.13
Date:2026-01-16|Bitcoin Price:8637202.771129187| Crude Oil Price:59.4
Date:2026-01-20|Bitcoin Price:8414003.970645163| Crude Oil Price:60.3
Date:2026-01-21|Bitcoin Price:8046939.8302773405| Crude Oil Price:60.38
Date:2026-01-22|Bitcoin Price:8179241.969294843| Crude Oil Price:59.24
Date:2026-01-23|Bitcoin Price:8189307.776814618| Crude Oil Price:60.7
Date:2026-01-26|Bitcoin Price:7931480.8104405| Crude Oil Price:60.46
Date:2026-01-27|Bitcoin Price:8098992.121060789| Crude Oil Price:62.04
Date:2026-01-28|Bitcoin Price:8165356.488930265| Crude Oil Price:62.75
Date:2026-01-29|Bitcoin Price:8206661.924142179| Crude Oil Price:64.77
Date:2026-01-30|Bitcoin Price:7762053.970031044| Crude Oil Price:64.5

**8.Compare NASDAQ (^IXIC) with Ethereum price trends**

In [ ]:
cursor.execute("""
    SELECT
      s.date,
      s.close AS nasdaq_price,
      c.price_inr AS ethereum_price
    FROM stock_prices s
    JOIN crypto_prices c
       ON s.date=c.date
    WHERE s.ticker='^IXIC'
      AND c.coin_id='ethereum'
    ORDER BY s.date;
""")
rows=cursor.fetchall()
for row in rows:
  print(f"Date:{row[0]}|NASDAQ Price:{row[1]}|ETHEREUM Price:{row[2]}")

Date:2025-02-28|NASDAQ Price:18847.279296875|ETHEREUM Price:201317.5125202556
Date:2025-03-03|NASDAQ Price:18350.189453125|ETHEREUM Price:220175.98842114926
Date:2025-03-04|NASDAQ Price:18285.16015625|ETHEREUM Price:187601.93013882774
Date:2025-03-05|NASDAQ Price:18552.73046875|ETHEREUM Price:189391.99179852934
Date:2025-03-06|NASDAQ Price:18069.259765625|ETHEREUM Price:194675.72885365813
Date:2025-03-07|NASDAQ Price:18196.220703125|ETHEREUM Price:191886.11355343607
Date:2025-03-10|NASDAQ Price:17468.3203125|ETHEREUM Price:175758.37045736366
Date:2025-03-11|NASDAQ Price:17436.099609375|ETHEREUM Price:164149.389538545
Date:2025-03-12|NASDAQ Price:17648.44921875|ETHEREUM Price:167538.8977230319
Date:2025-03-13|NASDAQ Price:17303.009765625|ETHEREUM Price:166533.75651871518
Date:2025-03-14|NASDAQ Price:17754.08984375|ETHEREUM Price:161919.08161409126
Date:2025-03-17|NASDAQ Price:17808.66015625|ETHEREUM Price:164134.74219204995
Date:2025-03-18|NASDAQ Price:17504.119140625|ETHEREUM Price:167679.9006033522
Date:2025-03-19|NASDAQ Price:17750.7890625|ETHEREUM Price:167319.001543521
Date:2025-03-20|NASDAQ Price:17691.630859375|ETHEREUM Price:177917.82793888426
Date:2025-03-21|NASDAQ Price:17784.05078125|ETHEREUM Price:171006.12473780697
Date:2025-03-24|NASDAQ Price:18188.58984375|ETHEREUM Price:172085.9718554942
Date:2025-03-25|NASDAQ Price:18271.859375|ETHEREUM Price:177753.92370784696
Date:2025-03-26|NASDAQ Price:17899.01953125|ETHEREUM Price:177052.68464483944
Date:2025-03-27|NASDAQ Price:17804.029296875|ETHEREUM Price:172151.5682806194
Date:2025-03-28|NASDAQ Price:17322.990234375|ETHEREUM Price:171697.82772804037
Date:2025-03-31|NASDAQ Price:17299.2890625|ETHEREUM Price:154426.70647452315
Date:2025-04-01|NASDAQ Price:17449.890625|ETHEREUM Price:155840.4924805317
Date:2025-04-02|NASDAQ Price:17601.05078125|ETHEREUM Price:163227.64895741257
Date:2025-04-03|NASDAQ Price:16550.609375|ETHEREUM Price:153890.04212059852
Date:2025-04-04|NASDAQ Price:15587.7900390625|ETHEREUM Price:155066.27550185894
Date:2025-04-07|NASDAQ Price:15603.259765625|ETHEREUM Price:134677.50142669896
Date:2025-04-08|NASDAQ Price:15267.91015625|ETHEREUM Price:133837.57278106204
Date:2025-04-09|NASDAQ Price:17124.970703125|ETHEREUM Price:127176.85742857557
Date:2025-04-10|NASDAQ Price:16387.310546875|ETHEREUM Price:143324.73934384843
Date:2025-04-11|NASDAQ Price:16724.4609375|ETHEREUM Price:131454.92128790365
Date:2025-04-14|NASDAQ Price:16831.48046875|ETHEREUM Price:137163.51905527923
Date:2025-04-15|NASDAQ Price:16823.169921875|ETHEREUM Price:139502.26918137303
Date:2025-04-16|NASDAQ Price:16307.16015625|ETHEREUM Price:136118.34029958773
Date:2025-04-17|NASDAQ Price:16286.4501953125|ETHEREUM Price:135084.25007491114
Date:2025-04-21|NASDAQ Price:15870.900390625|ETHEREUM Price:135372.22120159038
Date:2025-04-22|NASDAQ Price:16300.419921875|ETHEREUM Price:134334.00818529903
Date:2025-04-23|NASDAQ Price:16708.05078125|ETHEREUM Price:149984.44480204728
Date:2025-04-24|NASDAQ Price:17166.0390625|ETHEREUM Price:153384.6912264906
Date:2025-04-25|NASDAQ Price:17382.939453125|ETHEREUM Price:150793.82263866183
Date:2025-04-28|NASDAQ Price:17366.130859375|ETHEREUM Price:153154.64715995087
Date:2025-04-29|NASDAQ Price:17461.3203125|ETHEREUM Price:153246.47199208362
Date:2025-04-30|NASDAQ Price:17446.33984375|ETHEREUM Price:153045.86830616
Date:2025-05-01|NASDAQ Price:17710.740234375|ETHEREUM Price:151706.98921091956
Date:2025-05-02|NASDAQ Price:17977.73046875|ETHEREUM Price:155745.16924065605
Date:2025-05-05|NASDAQ Price:17844.240234375|ETHEREUM Price:152837.10606631296
Date:2025-05-06|NASDAQ Price:17689.66015625|ETHEREUM Price:153282.69389658255
Date:2025-05-07|NASDAQ Price:17738.16015625|ETHEREUM Price:153903.86052217713
Date:2025-05-08|NASDAQ Price:17928.140625|ETHEREUM Price:153546.46543390723
Date:2025-05-09|NASDAQ Price:17928.919921875|ETHEREUM Price:189067.0538600533
Date:2025-05-12|NASDAQ Price:18708.33984375|ETHEREUM Price:214170.10011952536
Date:2025-05-13|NASDAQ Price:19010.08984375|ETHEREUM Price:211740.19586880849
Date:2025-05-14|NASDAQ Price:19146.810546875|ETHEREUM Price:227649.06017478785
Date:2025-05-15|NASDAQ Price:19112.3203125|ETHEREUM Price:222550.86125964453
Date:2025-05-16|NASDAQ Price:19211.099609375|ETHEREUM Price:217226.91460543944
Date:2025-05-19|NASDAQ Price:19215.4609375|ETHEREUM Price:210787.9756927576
Date:2025-05-20|NASDAQ Price:19142.7109375|ETHEREUM Price:215738.55684027018
Date:2025-05-21|NASDAQ Price:18872.640625|ETHEREUM Price:215915.19935485243
Date:2025-05-22|NASDAQ Price:18925.740234375|ETHEREUM Price:219047.5756337483
Date:2025-05-23|NASDAQ Price:18737.2109375|ETHEREUM Price:228450.3696380665
Date:2025-05-27|NASDAQ Price:19199.16015625|ETHEREUM Price:218190.67523487698
Date:2025-05-28|NASDAQ Price:19100.939453125|ETHEREUM Price:227238.5848495167
Date:2025-05-29|NASDAQ Price:19175.869140625|ETHEREUM Price:228525.93909568293
Date:2025-05-30|NASDAQ Price:19113.76953125|ETHEREUM Price:224768.84403505738
Date:2025-06-02|NASDAQ Price:19242.609375|ETHEREUM Price:217089.5740742275
Date:2025-06-03|NASDAQ Price:19398.9609375|ETHEREUM Price:222777.49872829148
Date:2025-06-04|NASDAQ Price:19460.490234375|ETHEREUM Price:222455.17860950096
Date:2025-06-05|NASDAQ Price:19298.44921875|ETHEREUM Price:224236.44416331983
Date:2025-06-06|NASDAQ Price:19529.94921875|ETHEREUM Price:207961.65418872624
Date:2025-06-09|NASDAQ Price:19591.240234375|ETHEREUM Price:215217.42336418747
Date:2025-06-10|NASDAQ Price:19714.990234375|ETHEREUM Price:230255.54711844953
Date:2025-06-11|NASDAQ Price:19615.880859375|ETHEREUM Price:240556.86572695823
Date:2025-06-12|NASDAQ Price:19662.490234375|ETHEREUM Price:237276.58179525606
Date:2025-06-13|NASDAQ Price:19406.830078125|ETHEREUM Price:227345.61024210224
Date:2025-06-16|NASDAQ Price:19701.2109375|ETHEREUM Price:219421.86983518038
Date:2025-06-17|NASDAQ Price:19521.08984375|ETHEREUM Price:220541.89744913176
Date:2025-06-18|NASDAQ Price:19546.26953125|ETHEREUM Price:217182.0562912451
Date:2025-06-20|NASDAQ Price:19447.41015625|ETHEREUM Price:218767.0130883784
Date:2025-06-23|NASDAQ Price:19630.970703125|ETHEREUM Price:192852.03096719063
Date:2025-06-24|NASDAQ Price:19912.529296875|ETHEREUM Price:209315.24780590468
Date:2025-06-25|NASDAQ Price:19973.55078125|ETHEREUM Price:210338.28060317386
Date:2025-06-26|NASDAQ Price:20167.91015625|ETHEREUM Price:207894.42363255343
Date:2025-06-27|NASDAQ Price:20273.4609375|ETHEREUM Price:206903.99097231845
Date:2025-06-30|NASDAQ Price:20369.73046875|ETHEREUM Price:213866.80820581852
Date:2025-07-01|NASDAQ Price:20202.890625|ETHEREUM Price:213247.902753943
Date:2025-07-02|NASDAQ Price:20393.130859375|ETHEREUM Price:206191.53795072352
Date:2025-07-03|NASDAQ Price:20601.099609375|ETHEREUM Price:220583.0677146267
Date:2025-07-07|NASDAQ Price:20412.51953125|ETHEREUM Price:219842.28509645213
Date:2025-07-08|NASDAQ Price:20418.4609375|ETHEREUM Price:218478.50703220506
Date:2025-07-09|NASDAQ Price:20611.33984375|ETHEREUM Price:224192.01293457407
Date:2025-07-10|NASDAQ Price:20630.66015625|ETHEREUM Price:237634.3285912139
Date:2025-07-11|NASDAQ Price:20585.529296875|ETHEREUM Price:252785.18261104374
Date:2025-07-14|NASDAQ Price:20640.330078125|ETHEREUM Price:255256.0749124428
Date:2025-07-15|NASDAQ Price:20677.80078125|ETHEREUM Price:258953.02296009834
Date:2025-07-16|NASDAQ Price:20730.490234375|ETHEREUM Price:269423.17285168904
Date:2025-07-17|NASDAQ Price:20885.650390625|ETHEREUM Price:289273.06195820443
Date:2025-07-18|NASDAQ Price:20895.650390625|ETHEREUM Price:299604.7001320289
Date:2025-07-21|NASDAQ Price:20974.1796875|ETHEREUM Price:323799.5635112756
Date:2025-07-22|NASDAQ Price:20892.689453125|ETHEREUM Price:324888.02667051577
Date:2025-07-23|NASDAQ Price:21020.01953125|ETHEREUM Price:323522.2855073287
Date:2025-07-24|NASDAQ Price:21057.9609375|ETHEREUM Price:313632.80993368995
Date:2025-07-25|NASDAQ Price:21108.3203125|ETHEREUM Price:320521.28663827025
Date:2025-07-28|NASDAQ Price:21178.580078125|ETHEREUM Price:334271.3356334813
Date:2025-07-29|NASDAQ Price:21098.2890625|ETHEREUM Price:328567.3072022601
Date:2025-07-30|NASDAQ Price:21129.669921875|ETHEREUM Price:329848.44489638496
Date:2025-07-31|NASDAQ Price:21122.44921875|ETHEREUM Price:333798.49786685634
Date:2025-08-01|NASDAQ Price:20650.130859375|ETHEREUM Price:323419.73918441863
Date:2025-08-04|NASDAQ Price:21053.580078125|ETHEREUM Price:305147.6597239278
Date:2025-08-05|NASDAQ Price:20916.55078125|ETHEREUM Price:326586.85608261486
Date:2025-08-06|NASDAQ Price:21169.419921875|ETHEREUM Price:316895.55183794844
Date:2025-08-07|NASDAQ Price:21242.69921875|ETHEREUM Price:323322.0010279766
Date:2025-08-08|NASDAQ Price:21450.01953125|ETHEREUM Price:341975.0422938313
Date:2025-08-11|NASDAQ Price:21385.400390625|ETHEREUM Price:372140.5970629246
Date:2025-08-12|NASDAQ Price:21681.900390625|ETHEREUM Price:370718.8174494866
Date:2025-08-13|NASDAQ Price:21713.140625|ETHEREUM Price:403547.06190802733
Date:2025-08-14|NASDAQ Price:21710.669921875|ETHEREUM Price:416582.6051270567
Date:2025-08-15|NASDAQ Price:21622.98046875|ETHEREUM Price:399375.2127189976
Date:2025-08-18|NASDAQ Price:21629.76953125|ETHEREUM Price:392681.4189909559
Date:2025-08-19|NASDAQ Price:21314.94921875|ETHEREUM Price:376878.0982824829
Date:2025-08-20|NASDAQ Price:21172.859375|ETHEREUM Price:354772.70430919825
Date:2025-08-21|NASDAQ Price:21100.310546875|ETHEREUM Price:376832.66666282027
Date:2025-08-22|NASDAQ Price:21496.5390625|ETHEREUM Price:368766.6639472321
Date:2025-08-25|NASDAQ Price:21449.2890625|ETHEREUM Price:417273.9071184703
Date:2025-08-26|NASDAQ Price:21544.26953125|ETHEREUM Price:383869.2304155191
Date:2025-08-27|NASDAQ Price:21590.140625|ETHEREUM Price:403346.84673449927
Date:2025-08-28|NASDAQ Price:21705.16015625|ETHEREUM Price:394479.82107990474
Date:2025-08-29|NASDAQ Price:21455.55078125|ETHEREUM Price:394824.62858350464
Date:2025-09-02|NASDAQ Price:21279.630859375|ETHEREUM Price:378688.487081064
Date:2025-09-03|NASDAQ Price:21497.73046875|ETHEREUM Price:380669.0608269572
Date:2025-09-04|NASDAQ Price:21707.689453125|ETHEREUM Price:391914.25736500154
Date:2025-09-05|NASDAQ Price:21700.390625|ETHEREUM Price:379062.50711160863
Date:2025-09-08|NASDAQ Price:21798.69921875|ETHEREUM Price:379557.7315665512
Date:2025-09-09|NASDAQ Price:21879.490234375|ETHEREUM Price:379169.3803941581
Date:2025-09-10|NASDAQ Price:21886.060546875|ETHEREUM Price:380163.9598970403
Date:2025-09-11|NASDAQ Price:22043.0703125|ETHEREUM Price:382811.6356012148
Date:2025-09-12|NASDAQ Price:22141.099609375|ETHEREUM Price:393614.0739117057
Date:2025-09-15|NASDAQ Price:22348.75|ETHEREUM Price:406940.596240047
Date:2025-09-16|NASDAQ Price:22333.9609375|ETHEREUM Price:398693.42995223537
Date:2025-09-17|NASDAQ Price:22261.330078125|ETHEREUM Price:395856.797622927
Date:2025-09-18|NASDAQ Price:22470.720703125|ETHEREUM Price:403666.7568900215
Date:2025-09-19|NASDAQ Price:22631.48046875|ETHEREUM Price:404926.98327490315
Date:2025-09-22|NASDAQ Price:22788.98046875|ETHEREUM Price:392295.47524281475
Date:2025-09-23|NASDAQ Price:22573.470703125|ETHEREUM Price:370875.27142150694
Date:2025-09-24|NASDAQ Price:22497.859375|ETHEREUM Price:369992.0919011612
Date:2025-09-25|NASDAQ Price:22384.69921875|ETHEREUM Price:368312.96560615575
Date:2025-09-26|NASDAQ Price:22484.0703125|ETHEREUM Price:342937.4440185811
Date:2025-09-29|NASDAQ Price:22591.150390625|ETHEREUM Price:367286.12298418215

**9.Join top 3 crypto coins with stock indices for 2025**

In [ ]:
cursor.execute("""
    SELECT
      c.date,
      c.coin_id,
      c.price_inr AS crypto_price,
      s.date,
      s.close AS stock_price
    FROM crypto_prices c
    JOIN stock_prices s
       ON c.date=s.date
    WHERE c.coin_id IN ('bitcoin','ethereum','tether')
    AND s.ticker IN ('^GSPC', '^IXIC', '^NSEI')
    AND strftime('%Y',c.date)='2025'
    ORDER BY c.date;
""")
rows=cursor.fetchall()
df=pd.DataFrame(rows,columns=["Date","Coin","Crypto Price","Stock Index","Stock Price"])
df

            Date      Coin  Crypto Price Stock Index   Stock Price
0     2025-02-28   bitcoin  7.397417e+06  2025-02-28   5954.500000
1     2025-02-28   bitcoin  7.397417e+06  2025-02-28  18847.279297
2     2025-02-28   bitcoin  7.397417e+06  2025-02-28  22124.699219
3     2025-02-28  ethereum  2.013175e+05  2025-02-28   5954.500000
4     2025-02-28  ethereum  2.013175e+05  2025-02-28  18847.279297
...          ...       ...           ...         ...           ...
1309  2025-09-29  ethereum  3.672861e+05  2025-09-29  22591.150391
1310  2025-09-29  ethereum  3.672861e+05  2025-09-29  24634.900391
1311  2025-09-29    tether  8.870541e+01  2025-09-29   6661.209961
1312  2025-09-29    tether  8.870541e+01  2025-09-29  22591.150391
1313  2025-09-29    tether  8.870541e+01  2025-09-29  24634.900391

[1314 rows x 5 columns]

**10.Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison**

In [ ]:
import sqlite3
conn=sqlite3.connect("Marketing_data.db")
cursor=conn.cursor()
cursor.execute("""
    SELECT
      s.date,
      s.close AS stock_price,
      o.price_inr as oil_price,
      c.price_inr AS bitcoin_price
    FROM stock_prices s
    JOIN oil_prices o
     ON s.date=o.date
    JOIN crypto_prices c
     ON s.date=c.date
    WHERE s.ticker ='^GSPC'
    AND c.coin_id ='bitcoin'
    ORDER BY s.date;
""")

rows=cursor.fetchall()
df=pd.DataFrame(rows,columns=["Date","Stock Price","Oil Price","Bitcoin Price"])
df

In [ ]:
from google.colab import files
files.download("market_database.db")